### ISSUE TITLE
AWS Cloud SDK needs support for SessionToken for SQS

### ISSUE THREAD

**Issue by somal-vora** [awspring/spring-cloud-aws#1015]
**Type**: Bug

**Component**: AWS Cloud SQS 

**Describe the bug**
We are using awsspringcloud.version 3.0.3 in our service and trying to use SQS in it using SqsTemplate. For tests, we are using localstack 3.0.2 and testcontainers.version as 1.19.3. I have attached 3 classes for reference. 

It seems we can setup just access key and secret key with aws cloud library, but there is no way to setup session token.
1. spring.cloud.aws.credentials.secret-key
2. spring.cloud.aws.credentials.access-key 

But, unfortunately, there is no support for session-token yet. Hence, I always get session token invalid when I try do Sqstemplate.send. Because of which my test always fails since there is no way to add environment variable or set java property for session token with AWS cloud sdk currently. 

**Sample**
Here is example of my test class with AWSCloud + testcontainers + localstack. 
[SqsQueueServiceTest.java.zip](https://github.com/awspring/spring-cloud-aws/files/13883441/SqsQueueServiceTest.java.zip)

**Comment by tomazfernandes** [comment]
No clue on this one, but it looks like a feature out of SQS's scope and rather a core one.

@maciejwalkowiak WDYT?

**Comment by somal-vora** [comment]
Thanks @tomazfernandes for taking a look. We connected with SQS team initially, and they recommended to start request in this repo as sessionKey is missing with cloud sdk.

**Comment by tomazfernandes** [comment]
Sure, I mean SCAWS core, not AWS SDK 🙂

**Comment by maciejwalkowiak** [comment]
Yes, this is part of the core. @somal-vora can you explain exactly what's missing? We do have support for STS. If you need something that we do not support, you can also configure custom credentials provider bean: https://docs.awspring.io/spring-cloud-aws/docs/3.1.0/reference/html/index.html#custom-awscredentialsprovider

**Comment by somal-vora** [comment]
@maciejwalkowiak 
I believe to have  AWSCloud + testcontainers + localstack work, we need to have a way to add Session Key too. In Cloud SDK, there is no way to send session key properties yet. It seems SQS, you need session token, without it, it can't work I think.

**Comment by maciejwalkowiak** [comment]
@somal-vora we do support STS, we have a way to provide custom credentials provider. I am not sure what's missing exactly. Can you draft a PR that helps me to understand what you mean?

**Comment by somal-vora** [comment]
Closing this ask since we are unblocked now.
