### ISSUE TITLE
spring boot native image is not able to read message from AWS SQS

### ISSUE THREAD

**Issue by pulsar-gupta** [awspring/spring-cloud-aws#1021]
**Type**: Bug

**Component**: SQS

**Describe the bug**

I have an application and it reads messages from sqs when run locally but as soon as I deploy it's native image on EKS nothing happens and messages are queued on SQS.
It looks as is my native image is not reading messages from SQS. No logs are printed and no exception.

Here is my code:

@Configuration
public class ReaderConfiguration {

	@Bean
	public SqsClient sqsClient() {
		try {		
			AwsBasicCredentials credentials = AwsBasicCredentials.create("access-key", "secret");
			return SqsClient.builder().region(Region.of("eu-central-1")).credentialsProvider(() -> credentials).build();
		} catch (Exception e) {
			e.printStackTrace();
			throw new AwsAuthenticationError("Aws Authentication Error");
		}
	}

}
@Component
public class SQSListner {

	private SqsClient sqsClient = null;

	@Autowired
	public SQSListner(SqsClient sqsClient) {
		this.sqsClient = sqsClient;
	}

	@SqsListener("notification")
	public void recieveMessage(Message msg) {
		System.out.println("Received Message" + msg.body());
		// processMsg();
	}

}
<dependency>
	<groupId>io.awspring.cloud</groupId>
	<artifactId>spring-cloud-aws-starter-sqs</artifactId>
</dependency>
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>3.0.0</version>
	<relativePath /> 
</parent>
image is build using mvn -Pnative spring-boot:build-image

**Comment by MatejNedic** [comment]
Hey @pulsar-gupta , we have open PR for this it is known issue.

**Comment by pulsar-gupta** [comment]
with some changes I was able to resolve the issue
first step was to upgrade the spring boot and spring cloud version 

1. io.awspring.cloud - spring-cloud-aws-dependencies - 3.1.o
2. software.amazon.awssdk - bom - 2.20.45
3. spring-boot - 3.2.1

second step was to register hints 
* MyListener class is where I have @SqsListener method 'recieveMessage' to receive and process the messages from queue
  
   @Override
    public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
        // Register method for reflection
        Method sqsReceiveMethod = ReflectionUtils.findMethod(MyListener.class, "recieveMessage", Message.class);
        hints.reflection().registerMethod(sqsReceiveMethod, ExecutableMode.INVOKE);
        hints.resources().registerPattern("io/awspring/cloud/core/SpringCloudClientConfiguration.properties");
    } 

and created image mvn -Pnative spring-boot:build-image

Now works absolutely fine

**Comment by maciejwalkowiak** [comment]
Fixed in #856
