### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by andrewedstrom** [awspring/spring-cloud-aws#103]
This is a duplicate of https://github.com/spring-cloud/spring-cloud-aws/issues/766. I know that ownership of this project has changed so I wasn't sure where to file the bug.

**Type**: Bug

**Component**:
Documentation

**Describe the bug**
The link to the documentation for Spring Cloud AWS 2.3.0 is broken here: https://spring.io/projects/spring-cloud-aws#learn

I believe the link should be this: https://docs.awspring.io/spring-cloud-aws/docs/2.3.0-RC2/reference/html/index.html

Additionally, it seems like the newest version number is out of date here: https://awspring.io/learn/introduction/. It says 2.3.0 RC2 is the version of spring-cloud-aws that is compatible with Spring Boot 2.4.x. However, now that Spring Cloud AWS 2.3.0 has been released, the version number should be updated accordingly in the docs.

**Comment by maciejwalkowiak** [comment]
Thanks for reporting, the docs are fixed: https://docs.awspring.io/spring-cloud-aws/docs/current/reference/html/index.html
