### ISSUE TITLE
Spring Cloud AWS: Unable to map JSON to a different object when we have multiple listeners in a single service

### ISSUE THREAD

**Issue by kevvvvyp** [awspring/spring-cloud-aws#1037]
**Type**: Bug

**Component**:

SQS

**Describe the bug**

The issue discussion can be found here: https://github.com/awspring/spring-cloud-aws/discussions/1036

- Java 21
- Spring Boot 3.2.2
- spring-cloud-aws 3.1.0

**Sample**

Sample project that replicates the issue: https://github.com/kevvvvyp/spring-cloud-aws-sample

**Comment by tomazfernandes** [comment]
> Unable to map JSON to a different object when we have multiple listeners in a single service 

Not sure what this means...

You have plenty of deserialization options as described in the docs:
https://docs.awspring.io/spring-cloud-aws/docs/3.0.0/reference/html/index.html#configuring-a-messagingmessageconverter

**Comment by kevinmcp123** [comment]
> > Unable to map JSON to a different object when we have multiple listeners in a single service
> 
> Not sure what this means...
> 
> You have plenty of deserialization options as described in the docs: https://docs.awspring.io/spring-cloud-aws/docs/3.0.0/reference/html/index.html#configuring-a-messagingmessageconverter

Thanks @tomazfernandes , I probably could of phrased this better but thank you for picking this up on the discussion thread - https://github.com/awspring/spring-cloud-aws/discussions/1036#discussioncomment-8351627 

This non-issue can be marked as closed.
