### ISSUE TITLE
AbstractMessageListenerContainer ignores unknown SQS queues

### ISSUE THREAD

**Issue by birnbuazn** [awspring/spring-cloud-aws#104]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
`io.awspring.cloud.messaging.listener.AbstractMessageListenerContainer#initialize` validates queue attributes and silently ignores unknown SQS queues. 

This is problematic in our case, where we configure different queue names for different environments (DEV/TEST/PROD/...), and configuration problems should show at application boot time. 

If queue names are misconfigured, the application will become healthy with the current implementation, but will fail to consume any messages, which is less than ideal if we stage this error to production.

**Describe the solution you'd like**
`AbstractMessageListenerContainer` should have a flag `ignoreUnknown` or similar, and should throw an Exception, if this flag is set and an unknown queue is encountered during initialisation.

Happy to contribute code, if you like.

**Comment by maciejwalkowiak** [comment]
Similar to RabbitMQ integration, application should fail to start if the queue does not exist.

**Comment by maciejwalkowiak** [comment]
Solved by #374

**Comment by maciejwalkowiak** [comment]
Fixed in #374
