### ISSUE TITLE
Spring Cloud AWS SQS - factory properties of @SqsListener are not applied in Native Image.

### ISSUE THREAD

**Issue by bgr02** [awspring/spring-cloud-aws#1040]
**Type**: Bug

**Component**:  SQS

**Describe the bug**
GraalVM: GraalVM for JDK 17 Community 17.0.9
spring-cloud-aws-dependencies : 3.1.0
org.springframework.boot: 3.2.0

In the Native Image, SqsMessageListenerContainerFactory is specified in @SqsListener's factory, but it is ignored.

`defaultSqsListenerContainerFactory` registered as Bean, but it does not apply to `@SqsListener`.

**Sample**
```
@Bean
public SqsMessageListenerContainerFactory<Object> defaultSqsListenerContainerFactory() {
	return SqsMessageListenerContainerFactory
			.builder()
			.configure (
				options ->
					options.acknowledgementMode (AcknowledgementMode.valueOf ("MANUAL"))
			)
			.sqsAsyncClient(sqsAsyncClient())
			.build();
}

@SqsListener(value = "Test.fifo", factory = "defaultSqsListenerContainerFactory")
public void messageListener(String message, Acknowledgement ack) {
	System.out.println(message);

	ack.acknowledge();
}
```

**Comment by maciejwalkowiak** [comment]
Fixed in #856
