### ISSUE TITLE
class <DynamoDBBean>cannot be cast to <DynamoDBBean> class  ( <DynamoDBBean> is in unnamed module of loader 'app'; <DynamoDBBean> is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader

### ISSUE THREAD

**Issue by peeteko** [awspring/spring-cloud-aws#1043]
**Type**: Bug

**Component**:

**Describe the bug**
When I use Dspring.devtools.restart.enabled=true I have the following ClassCastException when i try to save or load dynamoDBBeans
Only when I disable the devtools restart then it works

I have this problem when I try to the save or load this via dynamoDBTemplate

__dynamoDbTemplate.load(
                Key.builder().partitionValue(clientReferenceCode).build(), StatusUpdate.class);

dynamoDbTemplate.save(statusUpdate);__

Exact error message
class be.bpost.isend.epf.partner.service.store.StatusUpdate cannot be cast to class be.bpost.isend.epf.partner.service.store.StatusUpdate (be.bpost.isend.epf.partner.service.store.StatusUpdate is in unnamed module of loader 'app'; be.bpost.isend.epf.partner.service.store.StatusUpdate is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @1e1a4b25)

@DynamoDbBean
public class StatusUpdate {
....

....
}

pom.xml
         <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-starter-dynamodb</artifactId>
        </dependency>
<dependencyManagement>
      <dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>3.1.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

**Comment by maciejwalkowiak** [comment]
This is known issue in AWS SDK: https://github.com/aws/aws-sdk-java-v2/issues/2604

In our docs we mention that to use devtools, you need to create schema manually: https://docs.awspring.io/spring-cloud-aws/docs/3.1.0/reference/html/index.html#resolving-table-schema

Unfortunately nothing we can do about it.

**Comment by peeteko** [comment]
I have done the following changes. I have removed all aws sdk dynamoDB annotations @DynamoDBBean, @DynamoDBPartitationKey ,... and added TableSchema

After this I can use -Dspring.devtools.restart.enabled=true 

private static final TableSchema<StatusUpdate> STATUS_UPDATE_TABLE_SCHEMA =
            StaticTableSchema.builder(StatusUpdate.class)
                    .newItemSupplier(StatusUpdate::new)
                    .addAttribute(String.class, a -> a.name("clientReferenceCode")
                            .getter(StatusUpdate::getClientReferenceCode)
                            .setter(StatusUpdate::setClientReferenceCode)
                            .tags(primaryPartitionKey()))
                    .addAttribute(String.class, a -> a.name("status")
                            .getter(StatusUpdate::getStatus)
                            .setter(StatusUpdate::setStatus))
                    .addAttribute(Long.class, a -> a.name("deletionDate")
                            .getter(StatusUpdate::getDeletionDate)
                            .setter(StatusUpdate::setDeletionDate))
                    .build();

@Bean
    public TableSchema<StatusUpdate> myStatusTableSchema(){
        return STATUS_UPDATE_TABLE_SCHEMA;
    }

**Comment by maciejwalkowiak** [comment]
@peeteko and then it worked?

**Comment by rorticus0502** [comment]
I too would like to know, did it then work?

**Comment by peeteko** [comment]
I made it working by switching to TableSchema approach

**Comment by helospark** [comment]
I also encountered the same with the latest `2.55.0` dynamodb and dynamodb-enhanced version.

The workaround I used is to add the dynamodb libraries to the devtool's RestartClassloader, by creating `src/main/resources/META-INF/spring-devtools.properties` with config:
```
restart.include.dynamodb=/dynamodb-[\\w\\d-\\.]+\\.jar
restart.include.dynamodb-enhanced=/dynamodb-enhanced-[\\w\\d-\\.]+\\.jar
```

With this in place devtools still works and I don't get the ClassCastException.
