### ISSUE TITLE
SQS Fails to deserialize in kotlin using Any

### ISSUE THREAD

**Issue by germanflighel** [awspring/spring-cloud-aws#1049]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
Trying to poll with `Any` as parameter throws a 500 error

**Sample**
A dummy listener using the annotation should do the trick:
```
@Component
class TransactionEventsListener(
    private val log: LogProvider,
) {

    @SqsListener(
        queueNames = ["http://localhost:4566/000000000000/transaction-events-sqs"]
    )
    fun decorateTransactionEvent(event: Any) {
        log.info("Handling transaction event $event") // or just printing it
    }
}
```
The environment variables are setup as:
`AWS_ACCESS_KEY_ID=admin;AWS_REGION=us-east-1;AWS_SECRET_ACCESS_KEY=admin`

Using a localstack setup with docker-compose:
```
version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: search-trx-localstack
    environment:
      - SERVICES=sqs,sns,s3
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - EDGE_PORT=4566
      - DEBUG=1
      - LS_LOG=trace-internal
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_ACCESS_KEY_ID=admin
    ports:
      - '4566:4566'
    volumes:
      - ./volumes/localstack:/docker-entrypoint-initaws.d
      - ${TEMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  localstack:
    external: false
    driver: bridge
    name: localstack
```

The app does not have any additional configuration

**Comment by tomazfernandes** [comment]
Hey @germanflighel,

What do you mean by "throws a 500 error"?

Can you share the full stacktrace?

Thanks.

**Comment by germanflighel** [comment]
Hey @tomazfernandes, thanks for the response.
I am currently unable to replicate this issue at the moment. I was tinkering with my code and the polling was failing to get the polling working, and must have changed some other stuff, in addition to the listener annotation usage.
Sorry to bother 😞
