### ISSUE TITLE
Document behavior change when sending / receiving List of messages.

### ISSUE THREAD

**Issue by tomazfernandes** [awspring/spring-cloud-aws#1053]
In Spring Cloud AWS 2.x, when a `List` was passed as an argument to send or receive payloads, it would serialize / deserialize the list in a single message payload.

Now the framework supports sending and receiving several messages at a time using a list, which enables better overall throughput since we can parallelize and send / receive as many messages in parallel or in a batch as we'd like.

But  to send / receive an actual List of POJOs in a single payload requires wrapping the list on a wrapper object.

We should properly document this for users coming form the 2.x version.

See https://github.com/awspring/spring-cloud-aws/issues/879

**Comment by alexisgra** [comment]
Hi @tomazfernandes,

I can take care of modifying the documentation.

Would you like me to add a paragraph to the `Sending Messages` section of `SQS Integration` chapter?
Or in the `Migration from 2.x to 3.x` section? 

Thanks

**Comment by tomazfernandes** [comment]
Thanks @alexisgra!

> Would you like me to add a paragraph to the Sending Messages section of SQS Integration chapter?
Or in the Migration from 2.x to 3.x section?

That's an excellent question. @maciejwalkowiak, wdyt?

**Comment by maciejwalkowiak** [comment]
Very good idea. I think it should be added in both places. Migration can mention that handling lists have changed and link to main docs

**Comment by alexisgra** [comment]
@tomazfernandes @maciejwalkowiak Thanks for your answer.

I created a PR. 
I did a few tests in local to understand the change. I don't know if I need to explain further, if necessary I can add more elements.

Thanks!

**Comment by maciejwalkowiak** [comment]
Fixed in #1101
