### ISSUE TITLE
Allow to partial acknowledge messages in SqsListener

### ISSUE THREAD

**Issue by coolcut69** [awspring/spring-cloud-aws#1054]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
If 1 of the 10 messages fails, only the failing message should be put back in the queue, the rest should be ack'ed

**Describe the solution you'd like**
It could be implemented like aws lambda handles it cfr. https://aws.amazon.com/about-aws/whats-new/2021/11/aws-lambda-partial-batch-response-sqs-event-source/

**Comment by tomazfernandes** [comment]
Hey @coolcut69 , I'm not sure exactly what you are referring to.

When using single message listener, messages are acknowledged independently of other ones that might be received in the same batch.

Can you please elaborate?

**Comment by tomazfernandes** [comment]
Closing due to lack of feedback.
