### ISSUE TITLE
aws spring  cloud 3.x : what the replacement for SimpleMessageListenerContainer for Aws cloud 2.x.x | SqsMessageListenerContainer

### ISSUE THREAD

**Issue by VaibhavTheVicar** [awspring/spring-cloud-aws#1055]
Looks like in aws spring  cloud 3.x SqsMessageListenerContainer is the replacement for SimpleMessageListenerContainer and similarly the factory.

I am having problems setting a setDestinationResolver. @maciejwalkowiak any clues?

**Comment by VaibhavTheVicar** [comment]
Found 
https://velog.io/@junghyeon/Spring-Boot-3.0-Migration

**Comment by VaibhavTheVicar** [comment]
Done

**Comment by maciejwalkowiak** [comment]
@VaibhavTheVicar destination resolver has not been ported to 3.x

**Comment by VaibhavTheVicar** [comment]
Hi @maciejwalkowiak , so we do not have a way to resolve the destination dynamically? Say based on some profile etc. Or am I missing something?

**Comment by VaibhavTheVicar** [comment]
For anyone looking for a solution, ovverride the SqsListenerContainerFactory the create container method, and transform th

**Comment by BalamuruganS46** [comment]
How do you set the following things in the SqsMessageListenerContainer
setAmazonSqs(amazonSqs);
factory.setAutoStartup(true);
factory.setMaxNumberOfMessages(10);
factory.setTaskExecutor(createDefaultTaskExecutor());
