### ISSUE TITLE
Unable to start the application after adding dep on aws parameter store config

### ISSUE THREAD

**Issue by surajaloksinha** [awspring/spring-cloud-aws#106]
Question

I am trying to use aws parameter store with springboot 2.4.4
however i am having problem. https://stackoverflow.com/questions/66823363/springboot-2-4-4-and-awspramstore

I Simply added a dependency on the spring-cloud-starter-aws-parameter-store-config 
when i deploy the app to aws it starts up fetches the parameters but crashes after few seconds.

***************************
APPLICATION FAILED TO START
***************************
Description:
A component required a bean named 'aws.paramstore-io.awspring.cloud.paramstore.AwsParamStoreProperties' that could not be found.
Action:
Consider defining a bean named 'aws.paramstore-io.awspring.cloud.paramstore.AwsParamStoreProperties' in your configuration.
About Support File a Bug Documentation Privacy Policy

this started happening after adding spring-cloud-starter-aws-parameter-store-config
With springboot 2.3.9 and old springcloud everything was working fine but with the new one for aws io.awsspring.cloud i have started to face this issue.

**Comment by arunkpatra** [comment]
An open issue #101 exists for this. The PR #102 is being worked upon.

**Comment by maciejwalkowiak** [comment]
Fixed in #102
