### ISSUE TITLE
SQS Reactive Streams support

### ISSUE THREAD

**Issue by v1nc3n4** [awspring/spring-cloud-aws#107]
Hello,

**Type**: Feature

**Is your feature request related to a problem? Please describe.**
I'm working on a Spring Webflux application, and by now, it seems to me very hard to process each messages received from a SQS queue sequentially, with a fixed rate. More generally, it is difficult to override/change the default behaviour of classes such as `SimpleMessageListenerContainer`, because many private classes are involved and cannot be overriden.

**Describe the solution you'd like**
With reactive streams support, developers could choose the threading model that is relevant for their applications.
In my case, the following interface could allow me to do whatever I want with the flux of messages received in a batch:
```java
@SqsListener(value = "queue-name", deletionPolicy = SqsMessageDeletionPolicy.NEVER)
public Flux<Acknowledgment> processMessage(Flux<SqsMessage> sqsMessages) {
    return sqsMessages.delay(Duration.ofSeconds(1))
        .flatMap(this::doSomethingAndMapToAcknowledgment);
}

public static class SqsMessage {
    private final Object message;
    private final Acknowledgment acknowledgment,
    private final Visibility visibility;
    // ...
}
```

Is there any plan to add support of reactive streams in the short term (3.x)?
Feel free to correct me if I am mistaken, and explain how I could achieve my use case with current release (2.3+).

Thanks in advance for your help.
BR

**Comment by MatejNedic** [comment]
Hey @v1nc3n4 ,
Thanks for opening issue! We are going to rewrite sqs integration in 3.x. so we are going to look at  supportimg reactive streams then.

**Comment by v1nc3n4** [comment]
Hi @MatejNedic, glad to read this. Thank you!

**Comment by maciejwalkowiak** [comment]
Processing batches has been addressed in 3.0 - not reactive but perhaps fits your needs. Listeners themselves are non-blocking and can return completable futures.

**Comment by maciejwalkowiak** [comment]
@tomazfernandes I'd appreciate your opinion here, considering you've authored the SQS integration. 

Is it something in your opinion worth pursuing? Is the return of investment worth it considering the efforts needed to support reactive streams?

**Comment by maciejwalkowiak** [comment]
I think it would be nice if framework allows extending it so that someone can make an adapter themselves, but there's no need for us to provide reactive adapters.

**Comment by maciejwalkowiak** [comment]
Considering the efforts needed to support reactive APIs we took the decision to not develop it in near future. We may embrace in the future async clients more than we do right now, which would make it easier for users to adapt to reactive apis themselves.
