### ISSUE TITLE
Add option to set DynamoDB table suffix

### ISSUE THREAD

**Issue by vldr-ivakhnenko** [awspring/spring-cloud-aws#1073]
**Type**: Feature

**Problem**

We currently employ a naming convention to separate or group DynamoDB tables by utilizing a prefix for namespace and a suffix to denote environment and region, structured as `{prefix}-{table_name}-{suffix}`. 
An example would be: `products-order-dev-eu1`

Currently  spring-cloud-aws-starter-dynamodb supports setting prefix via `spring.cloud.aws.dynamodb.table-prefix` property and `DefaultDynamoDbTableNameResolver`.

**Solution**

Extend support to automatically append suffix to a table name. 
- Add `spring.cloud.aws.dynamodb.table-suffix` property
- Extend `DefaultDynamoDbTableNameResolver` to support suffix property
- Update `DynamoDbAutoConfiguration` to initialize correct bean based on the provided properties

**Alternatives**

We could create a custom extension of `DefaultDynamoDbTableNameResolver` and implement the necessary functionality where it's required. However, this approach diminishes the benefits of the spring-cloud-aws-starter-dynamodb's no additional configuration approach.

Given that prefix configuration is already supported, it seems natural to include suffix support as well.

**Comment by MatejNedic** [comment]
Makes sense lets go for it!

**Comment by maciejwalkowiak** [comment]
@vldr-ivakhnenko would you like to contribute?

**Comment by vldr-ivakhnenko** [comment]
@maciejwalkowiak Hi! Sure! I can take it.

**Comment by maciejwalkowiak** [comment]
Fixed in #1081
