### ISSUE TITLE
@Timed annotation not working after upgrade

### ISSUE THREAD

**Issue by michaelwasser** [awspring/spring-cloud-aws#1074]
Hello

We have upgraded our Java microservice to use Spring boot 3.2.3, and Spring 6.1.4

In addition, we changed our dependencies to use:
<dependency>
      <groupId>io.awspring.cloud</groupId>
      <artifactId>spring-cloud-aws-starter</artifactId>
      <version>3.1.0</version>
</dependency>

We also upgraded micrometer library to send metrices to AWS Cloudwatch (from "cloudwatch" to "clouwatch2")
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-registry-cloudwatch2</artifactId>
</dependency>

The problem is that our **methods that use the @Timed annotation stopped working** and no data is sent to Cloudwatch.

Any idea what are we missing in the upgrade process ?

Thank You!!

**Comment by MatejNedic** [comment]
Could you please produce a sample?

**Comment by michaelwasser** [comment]
Hey @MatejNedic 

Here's an example of one of the methods that use to send the "http.server.requests.*" metrices and stop working after the upgrade:
(I have some widgets inside Cloudwatch that after the upgrade stop showing any new data)

`
@Override
    @Timed(value = "external.calls", description = "POST ActOne", percentiles = {PERCENTILE_9})
    public <T, S> T post(@MonitorTag("apiurl") String url, S requestBody, Class<T> responseClass) {
        return post(url, null, requestBody, responseClass);
    }

    @Override
    @Timed(description = "POST ActOne", percentiles = {PERCENTILE_9})
    @Retryable(value = {HttpServerErrorException.class, ResourceAccessException.class},
            maxAttemptsExpression = "${actone.retry.max.attempt}",
            backoff = @Backoff(delayExpression = "${actone.retry.delay}"))
    public <T, S> T post(@MonitorTag("apiurl") String url, HttpHeaders headers, S requestBody, Class<T> responseClass) {
        printLog(url, requestBody, "POST");
        HttpEntity<String> request = getRequest(headers, requestBody);
        ResponseEntity<T> tResponseEntity = this.restTemplate.postForEntity(url, request, responseClass);
        return tResponseEntity.getBody();
    }
`

Thanks!

**Comment by michaelwasser** [comment]
problem found

**Comment by lamanaghabayova** [comment]
@michaelwasser What was the problem?

**Comment by rick-alp** [comment]
@michaelwasser Indeed, what was the problem?
