### ISSUE TITLE
aws spring cloud 3.x : There is no queue stop timeout, that is creating problems by increasing buid timeout.

### ISSUE THREAD

**Issue by VaibhavTheVicar** [awspring/spring-cloud-aws#1077]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
	public void stop(String logicalQueueName) {
		stopQueue(logicalQueueName);

		try {
			if (isRunning(logicalQueueName)) {
				Future<?> future = this.scheduledFutureByQueue.remove(logicalQueueName);
				if (future != null) {
					future.get(this.queueStopTimeout, TimeUnit.MILLISECONDS);
				}
			}
		}
		catch (InterruptedException e) {
			Thread.currentThread().interrupt();
		}
		catch (ExecutionException | TimeoutException e) {
			getLogger().warn("Error stopping queue with name: '" + logicalQueueName + "'", e);
		}
	}
	
	There used to be a queueStopTimeout in the previous version, that let us, shut the queue down by interrupting the thread, when the application shuts down. In v3

	@Override
	public void stop() {
		if (!this.isRunning) {
			return;
		}
		logger.debug("Stopping container {}", this.id);
		synchronized (this.lifecycleMonitor) {
			this.isRunning = false;
			doStop();
		}
		logger.info("Container {} stopped", this.id);
	}
	
	Please advice if this exists, leave implementation, do you see a "hacky" way?

Another hacky thing I had to do: https://github.com/awspring/spring-cloud-aws/issues/1055

**Comment by VaibhavTheVicar** [comment]
@maciejwalkowiak

**Comment by tomazfernandes** [comment]
@VaibhavTheVicar , please take a look at the [ContainerOptions](https://docs.awspring.io/spring-cloud-aws/docs/3.1.0/reference/html/index.html#sqscontaineroptions-descriptions).

You'll find `listenerShutdownTimeout` and `acknowledgementShutdownTimeout` there which you can configure to achieve your goal. Set to `Duration.ZERO` if you don't want any wait.

Let me know if that works for you.

**Comment by tomazfernandes** [comment]
Closing due to lack of feedback.
