### ISSUE TITLE
Messages not consumed from SQS queue

### ISSUE THREAD

**Issue by sabarees19** [awspring/spring-cloud-aws#1132]
**Type**: Bug

**Component**:
"SQS" -->

**Describe the bug**
I am currently having **two queues** and using **separate @SqsListener** , while spinning in Dev environment it's start listening 
and receiving by both queues but after some time it's stop listening only to one queue.

But while am trying in Local with the stopped Queue the messages have been received also in **Messages in flight** state and before i running my Local all the messages in **Messages available** state but the queue configurations are all same. Don't the what the exact issue is happening.

**Sample**
@SqlListener(value="${queue.name.req}", deletionPolicy=SqsMessageDeletionPolicy.ON_SUCCESS) {
...
}

@SqlListener(value="${queue.name.pro}", deletionPolicy=SqsMessageDeletionPolicy.ON_SUCCESS) {
...
}

**Comment by maciejwalkowiak** [comment]
@sabarees19 which Spring Cloud AWS version? Can you provide a git repo with a sample that reproduces this issue?

**Comment by sabarees19** [comment]
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-aws-messaging</artifactId>
			<version>2.2.6.RELEASE</version>
		</dependency>

i facing this issue in my current working project. Will update with sample ASAP.

**Current versions :** 
1. Java version --> 11
2. spring version --> 2.7.12

**Comment by maciejwalkowiak** [comment]
@sabarees19 2.x is out of support and maintenance. Please upgrade to 3.x (you'd have to upgrade to Spring Boot 3.x too).

**Comment by sabarees19** [comment]
The higher version of Spring Cloud AWS is 2.2.6 available on mvnrepository. is there any higher ?

**Comment by maciejwalkowiak** [comment]
Look at releases in GitHub repo to see the latest versions, also at the reference docs. Starting from 3.0, SQS and SNS have separate modules

**Comment by tomazfernandes** [comment]
I'll close this issue for lack of feedback, but we can reopen if necessary. Thanks.
