### ISSUE TITLE
Add MessagingMessageConverter to SQS Auto-configuration

### ISSUE THREAD

**Issue by tomazfernandes** [awspring/spring-cloud-aws#1145]
Currently the only way to set a custom `MessagingMessageConverter` is to declare a `SqsMessageListenerContainerFactory` and set it manually, which generates friction since when a factory bean is declared the user no longer benefits from its auto configuration.

We should make it possible to declare a `MessagingMessageConverter` bean and having it set in auto configuration.

**Comment by injae-kim** [comment]
PR: https://github.com/awspring/spring-cloud-aws/pull/1150
