### ISSUE TITLE
How to get lastEvaluatedKey ?

### ISSUE THREAD

**Issue by ipsi-apant** [awspring/spring-cloud-aws#1153]
**Type**: Question

**Component**:

DynamoDB

**Describe**
I am using `io.awspring.cloud.dynamodb.DynamoDbTemplate` for querying records by global secondary index.
The result of this API is `PageIterable<T>` which works if I need to return these records. However, the table contain millions of records, therefore planning query in chunks with filter criteria and use `lastEvaluatedKey` to fetch next set of records.
I am unable to find any workable example using `DynamoDbTemplate`.

Can you please advise?

**Tech stack**
- Springboot  `3.2.5`
- awspring     `3.1.1`
- AWS SDK     `2.25.47`
- Java             `21`
- WebFlux functional routes

**Sample**

```java

private Flux<Person> getAllByIndex(String globalSecondaryIndex, final Consumer<Builder> expressionConsumer,)  {

    Expression.Builder expressionBuilder = Expression.builder();
    expressionConsumer.accept(expressionBuilder);

    return Flux.fromIterable(dynamoDbTemplate
                                 .query(
                                     QueryEnhancedRequest.builder()
                                                         .queryConditional(
                                                             QueryConditional
                                                                 .keyEqualTo(keyBuilder -> keyBuilder
                                                                     .partitionValue(globalSecondaryIndex)
                                                                 )
                                                         )
                                                         .filterExpression(expressionBuilder.build())
                                                         .build(),
                                     Person.class,
                                     PERSON_INDEX
                                 )
                                 .items()
    );
}
```

**Comment by MatejNedic** [comment]
Hey @ipsi-apant , Instead of using `.items()` you have to use for example `.iterator().next().lastEvaluatedKey()` on that level you have `.items()` as well

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback
