### ISSUE TITLE
DynamoDbTemplate.delete() does not return although AWS SDK deleteItem() returns

### ISSUE THREAD

**Issue by ipsi-apant** [awspring/spring-cloud-aws#1154]
**Type**: Bug

**Component**:
DynamoDB

**Describe the bug**
I am using DynamoDbTemplate for querying dynamodb records. The `delete()` method in the API is `void`, therefore unable to perform further actions using the response from AWS SDK `deleteItem()`

https://github.com/awspring/spring-cloud-aws/blob/4e9cd0ef33e722eefa616d634938cecfb5b9e3a4/spring-cloud-aws-dynamodb/src/main/java/io/awspring/cloud/dynamodb/DynamoDbTemplate.java#L69

https://github.com/awspring/spring-cloud-aws/blob/4e9cd0ef33e722eefa616d634938cecfb5b9e3a4/spring-cloud-aws-dynamodb/src/main/java/io/awspring/cloud/dynamodb/DynamoDbTemplate.java#L75

**Comment by MatejNedic** [comment]
Hey @ipsi-apant ,

what is use case for returning deleted items, just out of curiosity? 
We followed Spring Data templates where delete is always void but we can change this ofc.

**Comment by ipsi-apant** [comment]
> Hey @ipsi-apant ,
> 
> what is use case for returning deleted items, just out of curiosity? We followed Spring Data templates where delete is always void but we can change this ofc.

Hi @MatejNedic, we are using WebFlux reactor. I need to provide messages in the response based on the result of the delete operation (including the partition id and other fields). Having this delete as void method led to use `Mono<Void>` and we are returning 204 No contents. This is deviating from returning a uniform response structure from the app I am working on.
We maybe able to get partition id form request, but Mono<Void> always resolve as success unless exception in underlaying API execution. Result from delete will allow me to capture success and to other transformations.

`DynamoDbTable.deleteItem()` returns a value therefore it would be helpful if this API returns the result of it.

**Comment by ipsi-apant** [comment]
Hi @MatejNedic , is it possible to get returned response from DynamoDB API for these delete methods ? Let me know if you need more information.

**Comment by MatejNedic** [comment]
Hey hey @ipsi-apant It is.
Will target it for next release!

**Comment by ipsi-apant** [comment]
> Hey hey @ipsi-apant It is. Will target it for next release!

Thank you @MatejNedic for consideration. I will test in next release. Whenever possible please add a link of the change to this open issue so, I will update and test in our code base. Appreciate it!
