### ISSUE TITLE
Support for aws-sdk-java-v2

### ISSUE THREAD

**Issue by jakubgruber** [awspring/spring-cloud-aws#116]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
I started integrating spring-cloud-aws together with SQS, SNS and X-Ray tracing, but it seems like yhe solution now relies on aws-sdk-java v1.

When integrating spring-cloud-aws with X-Ray tracing, it is necessary to use `ClientOverrideConfiguration` to be able to set `TracingInterceptor` ([docs](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-awssdkclients.html)). 

DynamoDB Client example:
```java
import com.amazonaws.xray.interceptors.TracingInterceptor;
import software.amazon.awssdk.core.client.config.ClientOverrideConfiguration
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
//...
public class MyModel {
private DynamoDbClient client = DynamoDbClient.builder()
.region(Region.US_WEST_2)
.overrideConfiguration(ClientOverrideConfiguration.builder()
.addExecutionInterceptor(new TracingInterceptor())
.build()
)
.build();
//...
```

**Describe the solution you'd like**
Would it be please possible to rely on aws-sdk-java-v2 and support `ClientOverrideConfiguration` for AWS SDK clients' settings?

**Describe alternatives you've considered**
I noticed you support `ClientConfiguration` since version 2.3, it would be nice to upgrade to newer AWS SDK versions then.

**Comment by MatejNedic** [comment]
Hey @jakubgruber , we are currently working on 3.x which will use AWS sdk v2. Some new features will be introduced and some old integrations will be rewritten from scratch. You can check 3.x branch to see how it is going. :)

**Comment by jonatan-ivanov** [comment]
After this is implemented, what are your plans with the V1 SDK? Are you planning to completely remove (or deprecate) it? If so, do you have a timeline?
I'm asking because as far as I know, there V2 SDK hasn't reached feature parity with V1, and we have the same issue with Micrometer: https://github.com/awspring/spring-cloud-aws/issues/116 (right now we are supporting both but we are looking into removing V1).

**Comment by maciejwalkowiak** [comment]
Ideally we would like to have it done till the end of 2021, but I am not sure yet how realistic is it. 

I think all or great majority of functionality we need is implemented in V2. If not, V1 and V2 can work side by side in the same project as the package name in v2 has changed.

**Comment by maciejwalkowiak** [comment]
Closing in favour of #20.
