### ISSUE TITLE
Specify content-MD5 when generating presigned URL for uploading object

### ISSUE THREAD

**Issue by hardikSinghBehl** [awspring/spring-cloud-aws#1161]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
When generating a presigned URL for uploading an object, two headers of `contentMD5` and `contentLength` are recommended to be added to avoid phishing attacks and improve overall security. 

The ObjectMetadata class allows me to specify the `contentLength`, but not `contentMD5`.

**Describe the solution you'd like**
The ability to configure the contentMD5 hash when generating a PUT presigned URL, like below:

```java
final var metadata = ObjectMetadata.builder().contentLength(length).contentMD5(contentMD5).build();
return s3Template.createSignedPutURL(bucketName, objectKey, urlValidity, metadata, null);
```

**Describe alternatives you've considered**

Currently, I used the `S3Client` class directly instead of `S3Template`.

**Additional context**
Can raise a PR for this!

**Comment by maciejwalkowiak** [comment]
@hardikSinghBehl sounds good! If you're still interested, please submit a PR!

**Comment by hardikSinghBehl** [comment]
I've raised a [PR](https://github.com/awspring/spring-cloud-aws/pull/1252) for this issue @maciejwalkowiak. It's ready to be reviewed!
