### ISSUE TITLE
The behaviour of spring.config.import=aws-parameterstore: when aws.paramstore.enabled=false seems wrong

### ISSUE THREAD

**Issue by eloranta-timo** [awspring/spring-cloud-aws#117]
**Type**: Bug

**Component**: Parameter Store

**Describe the bug**
Spring Boot 2.4.4 / Spring Cloud AWS 2.3.1
We are in the process of upgrading from Spring Boot 2.3.x to Spring Boot 2.4.4.
In application.properties we have currently following settings:

```
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

aws.paramstore.enabled=${AWS_PARAMSTORE_ENABLED:true}
spring.config.import=aws-parameterstore:
```

When running our app in AWS things work great - parameters are correctly read from Parameter Store.
However, when trying to run the app locally - i.e. with aws.paramstore.enabled=false - we get:

```
IllegalStateException: Unable to load config data from 'aws-parameterstore:'
```

Since **spring.config.import=aws-parameterstore:** is apparently the recommended way to read the Parameter Store, then I'm guessing that a workaround to our issue would be to introduce some profile based solution, like:

```
#---
spring.config.activate.on-profile=<some-aws-related-spring-profile-here>
spring.config.import=aws-parameterstore:
```

However, if at all possible, I'd wish to avoid introducing a new Spring profile for this, as I feel this could/should be "fixed" in Spring Cloud AWS code. Here are a pair of potential solutions:

1.) Shouldn't the processing of spring.config.import=aws-parameterstore: take into account the value of aws.paramstore.enabled? If that property is set to false, then - instead of stopping the application from starting - shouldn't the failing import lead to at most a warning?

2.) At the end of https://docs.awspring.io/spring-cloud-aws/docs/2.3.1/reference/html/index.html#integrating-your-spring-cloud-application-with-the-aws-parameter-store there is an example property like this:

```
spring.config.import=optional:aws-parameterstore:config-key;other-config-key
```
with description:

> With optional application will start even if there is no parameter found for specified parameter.

After finding this, we went ahead and tried:
```
spring.config.import=optional:aws-parameterstore:
```
but this didn't work, i.e. apparently this approach allows one to say that individual non-found parameters can be ignored, but one cannot this way say that it is ok if the Parameter Store cannot be found at all - which would have solved our issue with running our app locally.

What do you think? Have we fully misunderstood something regarding how spring.config.import should be used?

Thank you for your time!

**Comment by eddumelendez** [comment]
@eloranta-timo the way config data resolver works is, first making sure the prefix used is something can be resolved and then resolve it. So, `aws.paramstore.enabled=false` means `aws-parameterstore:` resolution will be disabled and then by using `spring.config.import=aws-parameterstore:` an exception like the one you get is thrown because the resolution for that prefix was disabled. My suggestion is to have a property file for local with no `spring.config.import=aws-parameterstore:` and the one for production with it. The other option is to use `optional:aws-parameterstore:`. I hope this is clear now.
