### ISSUE TITLE
Autowiring SsmClient not working

### ISSUE THREAD

**Issue by fkjaekel** [awspring/spring-cloud-aws#1179]
**Type**: Bug

**Component**:
"Parameter Store

**Describe the bug**
According to the documentation a SsmClient should automatically created, but I'm getting No qualifying bean of type 'software.amazon.awssdk.services.ssm.SsmClient

Could you tell me in what class is the @Bean method for the SsmClient so I can debug it? I only found it for other services like S3 and SQS.

Thanks

**Sample**
Dependencies used:
 <dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>3.1.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
		<dependency>
			<groupId>io.awspring.cloud</groupId>
			<artifactId>spring-cloud-aws-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>io.awspring.cloud</groupId>
			<artifactId>spring-cloud-aws-starter-parameter-store</artifactId>
		</dependency>

**Comment by srknkbs** [comment]
Hi @fkjaekel , I would like to ask that how you resolved this issue since I am facing the similar issue as well.
Thanks

**Comment by maciejwalkowiak** [comment]
@srknkbs there's an open issue about it https://github.com/awspring/spring-cloud-aws/issues/1231
