### ISSUE TITLE
Mention Spring Integration AWS and Spring Cloud Stream AWS Kinesis Binder projects in docs

### ISSUE THREAD

**Issue by artembilan** [awspring/spring-cloud-aws#118]
Since this project has been moved outside of Spring portfolio it would be nice to have cross links to projects which still exist over there and are based on this one.

The info I would like to see is something like `References` chapter with a brief mentioning for these projects:

https://github.com/spring-projects/spring-integration-aws/

https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis

Thank you!

**Comment by nickcaballero** [comment]
https://github.com/spring-projects/spring-integration-aws/issues/193

**Comment by eddumelendez** [comment]
Hi @artembilan, thanks for raising this issue! I agree, we can improve the docs mentioning those spring projects.

**Comment by maciejwalkowiak** [comment]
Apologies for a delay. Docs will include it in the next release but at this stage we have it at least in the readme: https://github.com/awspring/spring-cloud-aws
