### ISSUE TITLE
Container io.awspring.cloud.sqs.sqsListenerEndpointContainer#0 stopped. 

### ISSUE THREAD

**Issue by jangolano** [awspring/spring-cloud-aws#1189]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
 Container io.awspring.cloud.sqs.sqsListenerEndpointContainer#0 stopped.    It then shows memory data in the logs.
 This seems to happen randomly.

I know the example below doesn't give a lot of information.  The code is running in a docker container within ECS/Fargate.

**Sample**
```kotlin

    @SqsListener("generate-report-queue")
    fun onReceiveMessage(message: String) {
        logger.info("Received the following message to generate a report: $message")
        if(message.uppercase()=="CURRENT"){
            CurrentReportGenerator(dynamoDbUtils, slackUtils, hrChannel).generate()
        }
        else if(StringUtils.isUserRequest(message)){
            UserReportGenerator(dynamoDbUtils, slackUtils, hrChannel, message).generate()
        }
    }
```

**Comment by tomazfernandes** [comment]
Hi @jangolano, perhaps your business logic is consuming too much memory and you're getting an `OutOfMemory`?

Really difficult to help with as little information, if you can please add more info, or set up a small sample project that reproduces the issue.

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback. If feedback comes we are happy to reopen.
