### ISSUE TITLE
SQS Documentation: Incorrect Default Values

### ISSUE THREAD

**Issue by jmrah** [awspring/spring-cloud-aws#1202]
**Type**: Bug 

**Component**: SQS Documentation 

**Describe the bug** 
Spring Boot: v3.3.3 
Spring Cloud: v3.0.0 

[In the short 8.3.7 section of the current SQS documentation](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0/reference/html/index.html#container-options), the documentation for three properties should be amended: 

1. Under the [Using Autoconfiguration](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0/reference/html/index.html#using-auto-configuration) subsection, it isn't obvious that the `spring.cloud.aws.sqs.listener.poll-timeout` property needs to be specified in milliseconds, especially when the documented default is listed in seconds. It would be helpful if the property description mentioned the expected unit of time (ms). 
2. Under the [SqsContainerOptions Description](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0/reference/html/index.html#sqscontaineroptions-descriptions) subsection, there are two incorrectly documented default values: 
2.1 `listenerShutdownTimeout` is documented with a default value of 10s, but is really 20s. 
2.2 `acknowledgementShutdownTimeout` is documented with a default value of 10s, but is really 20s. 

**Sample** I've created a minimal example located at https://github.com/jmrah/spring-cloud-aws-sqs-test. You can clone the repo, and run the tests, which assert on the correct values as they should be, and not how they are documented as being. Additionally, you can attach a debugger to the tests and use your IDE to inspect the container options.

**Comment by maciejwalkowiak** [comment]
`spring.cloud.aws.sqs.listener.poll-timeout` has a type `Duration` and Boot has a [dedicated support](https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.conversion.durations) for parsing different string values.

Regarding `listenerShutdownTimeout` and `acknowledgementShutdownTimeout` you're correct - thanks for pointing that.
