### ISSUE TITLE
QueueMessageChannel.receive() implementation doesn't align with PollableChannel 's definition

### ISSUE THREAD

**Issue by jorgenota** [awspring/spring-cloud-aws#122]
**Type**: Bug

**Component**:
SQS

**Describe the bug**

- According to javadoc of PollableChannel, MessageChannel.INDEFINITE_TIMEOUT should be used to represent indefinite timeout (instead of 0).
- The timeout parameter of PollableChannel.receive() method represents the timeout in milliseconds (so it should be transformed into seconds when building the ReceiveMessageRequest).

**Comment by jorgenota** [comment]
Suggested fix in PR #123

**Comment by maciejwalkowiak** [comment]
As mentioned in #123 - we are not going to fix it to not introduce breaking change.
