### ISSUE TITLE
SecretsManagerAutoConfiguration should have AwsAutoConfiguration in AutoConfigureAfter

### ISSUE THREAD

**Issue by marcindabrowski** [awspring/spring-cloud-aws#1232]
**Type**: Bug

**Component**:  Secrets Manager

**Describe the bug**
In version 3.2.0 `SecretsManagerAutoConfiguration` was added that requires bean `AwsClientBuilderConfigurer`, but `SecretsManagerAutoConfiguration` didn't added `AwsAutoConfiguration` in `AutoConfigureAfter` but relies on `CredentialsProviderAutoConfiguration` and `RegionProviderAutoConfiguration` but do not relies on `AwsCredentialsProvider` and `AwsRegionProvider` beans.

I think that `@AutoConfigureAfter({ CredentialsProviderAutoConfiguration.class, RegionProviderAutoConfiguration.class })` should be added to `AwsAutoConfiguration`, and `AwsAutoConfiguration` should be put as prerequisite for  `SecretsManagerAutoConfiguration`.

**Sample**
When trying to start app with secret manager I'm getting:
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'secretsManagerClient' defined in class path resource [io/awspring/cloud/autoconfigure/config/secretsmanager/SecretsManagerAutoConfiguration.class]: Unsatisfied dependency expressed through method 'secretsManagerClient' parameter 1: No qualifying bean of type 'io.awspring.cloud.autoconfigure.core.AwsClientBuilderConfigurer' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by maciejwalkowiak** [comment]
Thanks for reporting. Would you like to send a PR with fix?

**Comment by marcindabrowski** [comment]
created a PR https://github.com/awspring/spring-cloud-aws/pull/1235
