### ISSUE TITLE
Only process FIFO queue messages with same MessageGroupId if previous ones were acknowledged

### ISSUE THREAD

**Issue by sebastianistoblame** [awspring/spring-cloud-aws#124]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
When receiving FIFO queue messages as batches of more than 1, it can happen that a newer message with the same `MessageGroupId` is processed before older ones are acknowledged.

Lets consider this example: We have two messages: A, B
A is first in the FIFO queue, B second.

Let's set our Deletion Policy to `NEVER` to manually acknowledge our messages. Now put both message A and B into the queue and receive them with maximum number of messages set to 10. Currently, if message A is not acknowledged, message B will be processed.

**Describe the solution you'd like**
I would like, that if message A is not acknowledged, message B will not be processed. Sure, setting the max. number of messages to receive to 1 will work. But I want to avoid using a value of 1 in order to reduce the number of calls made to AWS while still retaining correct ordering.

I'd like to have a configuration flag here. By turning it on, Spring AWS Messaging will not process messages, that have an identical `MessageGroupId`, if an earlier message with this `MessageGroupId` in the same batch was not acknowledged.

**Describe alternatives you've considered**
The downside of my proposed solution is, that you are moving more FIFO logic into the consumer. Therefore I can understand if you choose not to implement this. But in this case, I'd like to have a warning if Spring Cloud AWS messaging is configured with `maxNumberOfMessages` > 1 in combination with a FIFO queue.

**Additional context**
Here is my `AmazonSQSAsync` config:
```
  @Bean
  @Primary
  public AmazonSQSAsync amazonSQSClient() {
    return AmazonSQSAsyncClientBuilder.standard().build();
  }
```

Here is my `SimpleMessageListenerContainerFactory` config:
```
  @Bean
  public SimpleMessageListenerContainerFactory messageListenerContainerFactory(AmazonSQSAsync amazonSQSClient) {
    var factory = new SimpleMessageListenerContainerFactory();
    factory.setAmazonSqs(amazonSQSClient);
    factory.setMaxNumberOfMessages(10);
    factory.setWaitTimeOut(10);
    factory.setBackOffTime(1000L);
    return factory;
  }
```

**Comment by sdusza1** [comment]
I've been analyzing the same issue. I think the problem lies in `MessageGroupExecutor.run()`. 

There when an exception is caught the loop continues to process messages from the group.
And I think it shouldn't continue so that the next time messages from this group are recieved 
they should be processed in the same order.

I suspect that adding a break in this method could solve this problem:

`
for (Message message : this.messageGroup.getMessages()) {
	String receiptHandle = message.getReceiptHandle();
	org.springframework.messaging.Message<String> queueMessage = getMessageForExecution(message);
	try {
		executeMessage(queueMessage);
		applyDeletionPolicyOnSuccess(receiptHandle);
	}
	catch (MessagingException messagingException) {
		applyDeletionPolicyOnError(receiptHandle);
		break; // <- quit for loop
	}
}
`

**Comment by codingtim** [comment]
I would also prefer this behavior in my FIFO queues.

However I think the break is too simple. 
If the deletion policy is for example ALWAYS there is no need to break out of the for loop. 

So the behavior could be specified by: 
- the deletion policy meaning if the message is removed on failure then the for loop continues (applyDeletionPolicyOnError does not have a return so at the moment we don't know what happened in the for loop)
- a new setting that always you to specify the FIFO failure behavior

**Comment by sdusza1** [comment]
@codingtim I think You're right. We could check the value of `this.deletionPolicy` and execute break if  `ON_SUCCESS`. I'm not sure about the other policies.
