### ISSUE TITLE
Can't add AWSTraceHeader as system attribute because is replaced with "null"

### ISSUE THREAD

**Issue by acomofcg** [awspring/spring-cloud-aws#1262]
**Type**: Bug

**Component**:
"SQS"

**Describe the bug**
In Spring Cloud 3.1.1 I can't send the MessageSystemAttribute `AWSTraceHeader`: when setting the attribute, in the system attribute map of `software.amazon.awssdk.services.sqs.model.Message` object, the key is replaced with `"null"` string when converted to `SendMessageRequest`, and SQS return 400.

Debugging the code, I found that the problem is the `SqsTemplate` class when converting `MessageSystemAttributeName` into `MessageSystemAttributeNameForSends`, method `mapMessageSystemAttributes` at line [457](https://github.com/awspring/spring-cloud-aws/blob/0c8b974f24b98bcafcf8655fe25048ea7a93c18f/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/operations/SqsTemplate.java#L457).

Possible fixes:

replace
```
MessageSystemAttributeNameForSends.fromValue(entry.getKey().name())
```
with 

```
MessageSystemAttributeNameForSends.fromValue(entry.getKey().toString())
```
or
```
MessageSystemAttributeNameForSends.valueOf(entry.getKey().name())
```

What happening now is that the system attribute sent is 

```
"null" -> "Root=1-c29f4bf9-2c45b3e36f5984be173ddfaf;Parent=5b48b4b16bff358a;Sampled=1"
```
instead of 
```
"AWSTraceHeader" -> "Root=1-c29f4bf9-2c45b3e36f5984be173ddfaf;Parent=5b48b4b16bff358a;Sampled=1"
```
which is rejected by AWS.

**Comment by acomofcg** [comment]
Hi @maciejwalkowiak @tomazfernandes any news on this?

**Comment by maciejwalkowiak** [comment]
@acomofcg not yet. If you would like to contribute fix, PRs welcome!

**Comment by tomazfernandes** [comment]
@acomofcg, thanks for bringing this up. 

I wonder why this fails for this particular attribute and not the other ones?

Thanks

**Comment by acomofcg** [comment]
Hi @tomazfernandes,

as far as I understand, the tracing header is the only attribute allowed to be used among [system attributes](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-metadata.html#sqs-message-system-attributes), which is not mixed with the "normal" message attributes. This is why `MessageSystemAttributeNameForSends` has only one allowed value I guess.

Thanks for your help.

**Comment by acomofcg** [comment]
Hi @tomazfernandes @maciejwalkowiak I opened a PR (https://github.com/awspring/spring-cloud-aws/pull/1287)  for fixing the problem.

Please let me know if the tests are enough 

Thanks
