### ISSUE TITLE
aws-crt dependency version missing

### ISSUE THREAD

**Issue by vchrisb** [awspring/spring-cloud-aws#1271]
**Type**: Bug

**Component**:
[spring-cloud-aws-s3](https://github.com/awspring/spring-cloud-aws/tree/main/spring-cloud-aws-s3)

**Describe the bug**
`spring-cloud-aws-starter-s3` does not include a version for `aws-crt`.
According to [using-s3transfermanager-and-crt-based-s3-client](https://github.com/awspring/spring-cloud-aws/blob/d59ca4ae58ba4b757d3ff5afd783134302064d0a/docs/src/main/asciidoc/s3.adoc#using-s3transfermanager-and-crt-based-s3-client) it is enough to add the following dependency (without a version)

```
<dependency>
  <groupId>software.amazon.awssdk.crt</groupId>
  <artifactId>aws-crt</artifactId>
</dependency>
```

But https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-dependencies/pom.xml does not include a version for `aws-crt`.

**Sample**
```
<dependency>
  <groupId>software.amazon.awssdk.crt</groupId>
  <artifactId>aws-crt</artifactId>
</dependency>
```

**Comment by vchrisb** [comment]
Happy to create a PR to add a Version to `spring-cloud-aws-dependencies/pom.xml ` 

```
<aws-crt.version>0.33.0</aws-crt.version>
```
and
```
<dependency>
	<groupId>software.amazon.awssdk.crt</groupId>
	<artifactId>aws-crt</artifactId>
	<version>${aws-crt.version}</version>
	<optional>true</optional>
</dependency>
```

**Comment by maciejwalkowiak** [comment]
@vchrisb it is actually a mistake in docs. It should be `aws-crt-client` instead of `aws-crt`. PR with fix welcome!

**Comment by vchrisb** [comment]
@maciejwalkowiak is it a mistake in the docs and the dependencies?
`aws-crt-client` isn't part of the `spring-cloud-aws-dependencies/pom.xml` neither.

**Comment by maciejwalkowiak** [comment]
`aws-crt-client` is managed through AWS SDK bom which is already imported in dependencies' `pom.xml`.

**Comment by vchrisb** [comment]
Thank you. I found my mistake. It also needs to be a different groupId. Will create a PR.
```
<dependency>
	<groupId>software.amazon.awssdk</groupId>
	<artifactId>aws-crt-client</artifactId>
</dependency>
```

On that note, `spring-cloud-aws-dependencies/pom.xml` does include `s3-transfer-manager` but `software.amazon.awssdk:bom` has this dependency already, making it redundant?

**Comment by maciejwalkowiak** [comment]
Likely. There was a time when transfer manager was not managed by AWS SDK BOM but this has probably changed in meantime.

Thanks!
