### ISSUE TITLE
Document that the Secrets Manager code supports ARNs

### ISSUE THREAD

**Issue by buckett** [awspring/spring-cloud-aws#1285]
**Type**: Bug?

The Secrets Manager Integration specifies that you can supply a secret name to load configuration from that secret in https://docs.awspring.io/spring-cloud-aws/docs/3.2.0/reference/html/index.html#loading-external-configuration. It also supports passing an ARN. This isn't documented in spring cloud aws but works well. The underlying request in the AWS API https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html supports it.

Using an ARN is useful for cross account requests, but also for linking up secrets in cloudformation as the secret name isn't exposed as a return value when creating a secret: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html

**Comment by MatejNedic** [comment]
Hey @buckett , thanks on submitting the issue. Are you willing to make a PR to solve this issue?

**Comment by maciejwalkowiak** [comment]
Fixed in #1302
