### ISSUE TITLE
Parameter Store is not found in native version

### ISSUE THREAD

**Issue by mmuniz75** [awspring/spring-cloud-aws#1293]
I have simple Spring Boot project that works fine in JVM version.
After compile with ./gradlew nativeCompile and try execute I got :

Config data resource '[ParameterStoreConfigDataResource@41369e7b context = '/muniz/lab/', optional = false]' via location 'aws-parameterstore:/muniz/lab/' does not exist

Looks like it is not found the credentials to achieve the resource that contain the parameter store.

JDK : 21
Spring Boot : 3.3.6
Spring Cloud : 2023.0.4
Spring Cloud AWS : 3.2
GrallVM Compiler : Liberica 23.1.5.r21

To test project just need call : http://localhost:8080/param

Spring Boot project attached.
[parameter-store.zip](https://github.com/user-attachments/files/18129101/parameter-store.zip)

**Comment by MatejNedic** [comment]
Hey @mmuniz75 , 
Native hints will be found in 3.3.0-M2 release. 

With following hints I have samples that are loading properties normally on the start up with localstack 

```

        hints.reflection().registerType(TypeReference.of(ParameterStorePropertySources.class),
                hint -> hint.withMembers(MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
                        MemberCategory.INTROSPECT_DECLARED_METHODS, MemberCategory.DECLARED_FIELDS));

        hints.reflection().registerType(TypeReference.of(SecretsManagerPropertySources.class),
                hint -> hint.withMembers(MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
                        MemberCategory.INTROSPECT_DECLARED_METHODS, MemberCategory.DECLARED_FIELDS));

        hints.resources().registerPattern("io/awspring/cloud/core/SpringCloudClientConfiguration.properties");
 
```


Please make sample and publish it on a github instead of zip since we don't accept zips.

**Comment by MatejNedic** [comment]
Hey @mmuniz75 ,

Please check provided github sample [`here`](https://github.com/MatejNedic/Spring-Cloud-AWS-native)

Please tell me if you example has something different. For me all loading works and I am seeing message printed out. Also, I see fail if parameter is not in localstack.

**Comment by mmuniz75** [comment]
Hi MatejNedic,

After I add the : hints.resources().registerPattern("io/awspring/cloud/core/SpringCloudClientConfiguration.properties");

It works !!

Thanks for all
