### ISSUE TITLE
Add possibility to set up credentials for the Secrets Manager

### ISSUE THREAD

**Issue by SergeiKhmelevSPA** [awspring/spring-cloud-aws#144]
**Type**: Feature

**Tech details**: Spring boot 2.5.0, spring-cloud-aws-dependencies 2.3.1.

**Is your feature request related to a problem? Please describe.**
I was surprised about the effort you should put to make a Secrets manager work with a non-default `DefaultAWSCredentialsProviderChain` credentials. The only solution I found is to have a bootstrap Configuration with the `AWSSecretsManager` bean defined.

BootstrapAwsSecretsManagerClientConfig.kt:
```kotlin
/**
 * More or less copy of [io.awspring.cloud.autoconfigure.secretsmanager.AwsSecretsManagerBootstrapConfiguration]
 */
@Profile("prod")
@Configuration
class BootstrapAwsSecretsManagerClientConfig {

  @Bean
  fun smClient(environment: Environment, properties: AwsSecretsManagerProperties): AWSSecretsManager {
    val builder = AWSSecretsManagerClientBuilder.standard()
      .withCredentials(getAWSCredentialsProvider(environment))
      .withClientConfiguration(SpringCloudClientConfiguration.getClientConfiguration())
    if (!StringUtils.isNullOrEmpty(properties.region)) {
      builder.withRegion(properties.region)
    }
    if (properties.endpoint != null) {
      val endpointConfiguration = EndpointConfiguration(
        properties.endpoint.toString(),
        null,
      )
      builder.withEndpointConfiguration(endpointConfiguration)
    }
    return builder.build()
  }

  private fun getAWSCredentialsProvider(environment: Environment): AWSCredentialsProvider {
    val basicCredentials = BasicAWSCredentials(
      environment.getProperty("myapp.aws.secrets-manager.accessKey"),
      environment.getProperty("myapp.aws.secrets-manager.secretKey"),
    )
    return AWSStaticCredentialsProvider(basicCredentials)
  }
}
```

**Describe the solution you'd like**
It would be perfect if credentials could be specified in *bootstrap.yml* and used in the `AwsSecretsManagerBootstrapConfiguration`. Assuming having a `spring-cloud-aws-autoconfigure` dependency. E.g.
```yml
# should be replaced after 2.3.2 with `spring.config.import=aws-secretsmanager:`
aws:
  secretsmanager:
    enabled: true
    region: eu-central-1
    fail-fast: false

cloud:
  aws:
    credentials:
      access-key: access
      secret-key: secret
```

With 
```java
@Bean
@ConditionalOnMissingBean
AWSSecretsManager smClient(AWSCredentialsProvider credentialsProvider, AwsSecretsManagerProperties properties) {
  return createSecretsManagerClient(credentialsProvider, properties);
}
```

**Additional context**
I'm using a *bootstrap* and not `spring.config.import=aws-secretsmanager:` because of Cloud Stream context problem https://github.com/awspring/spring-cloud-aws/issues/108. P.S. cannot wait for the https://github.com/awspring/spring-cloud-aws/pull/142 to be released.

**Comment by MatejNedic** [comment]
Hey @SergeiKhmelevSPA ,
The thing is we will be deprecating Bootstrap in 3.x.  so I am not sure this feature would provide any benefits in the future.

**Comment by SergeiKhmelevSPA** [comment]
Glad to hear that! Hope there will be an easy way to set up credentials.
