### ISSUE TITLE
Secrets Manager aws.secretsmanager.prefix does not allow addition segments

### ISSUE THREAD

**Issue by marcuslange** [awspring/spring-cloud-aws#146]
**Type**: Bug

**Component**:
Secrets Manager

**Describe the bug**
The old library and current documentation says:

Prefix indicating first level for every property loaded from the Secrets Manager. Value must start with a forward slash followed by one or more valid path segments or be empty.

The new regex does not allow for additional path segments, only validates that it starts with slash:
Old regex: (/[a-zA-Z0-9.\\-_]+)*
New regex: (/)?([a-zA-Z0-9.\\-_]+)*

I have not validated, but I would guess that Parameter Store would have the same issue.

**Sample**
In this impl only "/foo" validates, not "/foo/bar/baz".

**Comment by MatejNedic** [comment]
Hey @marcuslange ,
Thanks for reporting. Regex will be updated soon.
