### ISSUE TITLE
Add support to auto-configure if session token present

### ISSUE THREAD

**Issue by GCHQDeveloper926** [awspring/spring-cloud-aws#149]
**Type: Feature**

**Is your feature request related to a problem? Please describe.**
As mentioned in a few issues:
https://github.com/spring-cloud/spring-cloud-vault/pull/575
https://github.com/awspring/spring-cloud-aws/issues/73

Spring doesn't create a context with a session token in the AWS properties for an application. 

**Describe the solution you'd like**

I would like to extend spring-cloud-aws to automatically create a credentials provider with a session token if it exists. This would involve adding the token to the [properties class](https://github.com/awspring/spring-cloud-aws/blob/2.3.x/spring-cloud-aws-autoconfigure/src/main/java/io/awspring/cloud/autoconfigure/context/properties/AwsCredentialsProperties.java) and modifying the [AutoConfguration](https://github.com/awspring/spring-cloud-aws/blob/94ad5ac4015be5491e0dc29d551d06531d75e28a/spring-cloud-aws-autoconfigure/src/main/java/io/awspring/cloud/autoconfigure/context/ContextCredentialsAutoConfiguration.java#L96)

**Describe alternatives you've considered**
I could provide my own AWS credentials Bean (current workaround I am using) but I think it would be nice if spring could do this in its own configuration if the sessionKey is present. 

**Additional Context**
Please let me know if you think this will break any existing session code or rotation. 

I will also update the documentation where needed. Are people happy for me to open a PR against this issue, if it is deemed useful?

Regards
GCHQDeveloper926

**Comment by GCHQDeveloper926** [comment]
I am happy to close this in favour of existing #73

**Comment by maciejwalkowiak** [comment]
No worries @GCHQDeveloper926. Closing in favour of #73
