### ISSUE TITLE
Question regarding next release

### ISSUE THREAD

**Issue by Larisho** [awspring/spring-cloud-aws#154]
Hello,

I noticed that #142 was committed to the 2.3.X branch a few days ago. I was wondering when that fix will be released to maven central?
The applications I am working on all suffer from the issue that was fixed and I was wondering when I could take advantage of the bugfix.

**Comment by Cimballi** [comment]
Is there any trick to avoid that bug while waiting for the fix to be pushed to Maven central ?

**Comment by maciejwalkowiak** [comment]
@Cimballi you can always fork it and release to your local Maven repository (if you have one). We will try to release more often once bugs are fixes, sorry guys for inconvenience.
