### ISSUE TITLE
Add optout option for profile-specific property loading

### ISSUE THREAD

**Issue by celcius112** [awspring/spring-cloud-aws#159]
**Type**: Feature

Hello, 

In one project we are using both the **secrets manager** and **parameter store** integrations. This project has 4 Spring profiles. As secrets name and parameter prefix we have a clear nomenclature that does not involve the Spring profiles. However, when the application starts up, spring-cloud-aws will always try to retrieve the properties by suffixing it with each profile, which is not something that we want.

With 4 profiles and two different integrations, that makes 8 requests that could be avoided when starting up the application. We also need to disable the `fail-fast` option so that the first request does not stop the start-up, but fail-fast is something that we would like to have in order to stop the start-up if the expected properties are no found.

This is basically what happens:
```
Loading secrets from AWS Secret Manager secret with name: /MyApp/application_dev, optional: true
Unable to load AWS secret from /MyApp/application_dev...

Loading secrets from AWS Secret Manager secret with name: /MyApp/application_awss3, optional: true
Unable to load AWS secret from /MyApp/application_awss3...

...

Loading property from AWS Secret Manager with name: /MyApp/application/, optional: true
Located property source: [BootstrapPropertySource {name='bootstrapProperties-/MyApp/application/'}]
```

It would be great if there was a way to disable profile-specific property loading, like a configuration property:
```
aws:
  secretsmanager:
    profile-loading: false
  paramstore:
    profile-loading: false
```

**Comment by MatejNedic** [comment]
Hey @celcius112 ,

we are planning to do that and we will deprecate it fully in 3.x. In 2.3.0 we introduced spring.config.import where you can specify which secrets or parameters you want (by path) which will not include load per profile. More can be found on: https://docs.awspring.io/spring-cloud-aws/docs/2.3.0-RC2/reference/html/index.html#integrating-your-spring-cloud-application-with-the-aws-secrets-manager
We are aware that there is a problem currently with spring.config.import which is already fixed and we are looking into a release!

**Comment by Larisho** [comment]
@MatejNedic Do you have a timeline or any other details regarding the next release?

**Comment by celcius112** [comment]
Hello @MatejNedic and thank you for your answer. It is quite useful to know that the bootstrap way will be deprecated in the next major release :).

Indeed the spring.config.import way was not working as expected previously, and we took the easy solution by using the legacy bootstrap. We will try using spring.config.import using the snapshot. 

If there is an issue we will open another issue.

If that's ok with you we can close this issue.

**Comment by MatejNedic** [comment]
@Larisho we are working on it. Since Bintray has been shut down we are migrating release scripts. This will take some time.
@celcius112 this issue can be closed.

**Comment by Larisho** [comment]
@MatejNedic Let me know if you guys need/want any help. Happy to lend a hand
