### ISSUE TITLE
Not loading properties from secrets manager

### ISSUE THREAD

**Issue by michalgorka** [awspring/spring-cloud-aws#162]
**Type**: Bug

**Component**: Secrets Manager

**Describe the bug**
Spring boot: 2.4.8
spring-cloud-starter-aws-secrets-manager-config: 2.3.1

I'm using your example and  module not loading data from secrets manager. It's look like the AwsSecretsManagerBootstrapConfiguration isn't called.

**Sample**
application.properties

```
aws.secretsmanager.default-context=backend
aws.secretsmanager.prefix=/secret

```
main class

```
@SpringBootApplication
public class DemoApplication {
	private static final Logger LOGGER = LoggerFactory.getLogger(DemoApplication.class);

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@Bean
	ApplicationRunner applicationRunner(@Value("${password}") String password) {
		return args -> {
			LOGGER.info("`password` loaded from the AWS Secret Manager: {}", password);
		};
	}
}
```

**Comment by MatejNedic** [comment]
Hey @michalgorka,
could you please provide pom.xml

**Comment by michalgorka** [comment]
@MatejNedic 

AWS cli is showing correctly properties from secret manager.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.8</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>io.awspring.cloud</groupId>
			<artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
			<version>2.3.1</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

```

**Comment by MatejNedic** [comment]
@michalgorka I miss read your first message. You should use Bootstrap.properties since old way of loading secret manager is done in Boostraping phase. Put prefix and default context values into Bootstrap.properties and it should work without issue.

**Comment by michalgorka** [comment]
@MatejNedic  i moved prefix na default context into bootstrap.properties and still i have the same problem error:

java.lang.IllegalArgumentException: Could not resolve placeholder 'password' in value "${password}"

This is my response from aws cli: 
```
{
    ........
    "Name": "/secret/backend",
    "VersionId":  ------,
    "SecretString": "{\"password\":\"qwerty\"}",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": "2021-07-09T17:39:14.308000+02:00"
}
```

**Comment by MatejNedic** [comment]
Hey @michalgorka ,
you are missing dependency to spring cloud boostrap. Please add

`<dependency> <groupId>org.springframework.cloud</groupId> <artifactId>spring-cloud-starter-bootstrap</artifactId> 
</dependency>`

**Comment by jonhines** [comment]
I've run into the same exact issue.

@MatejNedic ive added all of my config back into bootstrap, and the properties still are never properly fetched:

`bootstrap.properties`:
```
aws.secretsmanager.enabled=true
aws.secretsmanager.name=secret_name
aws.secretsmanager.endpoint=secretsmanager.eu-west-1.amazonaws.com
aws.secretsmanager.region=eu-west-1
aws.secretsmanager.prefix=/secrets
```


in `application.properties`:
```
spring.config.use-legacy-processing=true
```

and in pom.xml:
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.8</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <properties>
        <java.version>11</java.version>
        <spring-cloud.version>2020.0.3</spring-cloud.version>
        <spring.cloud.aws.version>2.3.1</spring.cloud.aws.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>${spring.cloud.aws.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```


I wanted to get this working using the `spring.config.import` path as well, but I ran into issues where the application never detected secrets manager as a resolvable property reference.

any guidance here would be great!

**Comment by michalgorka** [comment]
Hi thx for help it's working :)

**Comment by jonhines** [comment]
> Hi thx for help it's working :)

@michalgorka can you share the config/props/pom that got this working?  I'm still not able to see this working yet

**Comment by jonhines** [comment]
I think I've got my issue figured out.  To use the bootstrap approach for using AWS secrets manager, i needed to bring in the old dependency from `org.springframework.cloud`. 

I made a bad assumption that the `io.awspring.cloud` dependencies would be able to handle the property location based on the usage of this property: `spring.config.use-legacy-processing=true`

But that doesnt seem to be the case.

Here is my resulting `pom.xml` that got this working with spring boot parent version: `2.5.2`
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo</name>
    <description>Demo project for Spring Boot</description>
    <properties>
        <java.version>11</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud </groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
            <version>3.0.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
            <version>2.2.6.RELEASE</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

```

**Comment by MatejNedic** [comment]
Hey @jonhines ,
 new project doesn't change old way of loading properties in Bootstrap context. It is still supported so using dependency like below won't change that.
 `<dependency>
    <groupId>io.awspring.cloud</groupId>
    <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
    <version>2.3.1</version>
</dependency>`
 Could you please provide a sample for the not working scenario?

**Comment by jonhines** [comment]
@MatejNedic the config I posted above provides that example:
https://github.com/awspring/spring-cloud-aws/issues/162#issuecomment-878717039

I never got the secrets to pull via bootstrap until I added the legacy secrets manager dependency

**Comment by michalgorka** [comment]
@jonhines Can you show us your pom ?

**Comment by maciejwalkowiak** [comment]
Let me chime in. There are two ways properties can be loaded from Secrets Manager:

1. With `spring.config.import` introduced in Spring Boot 2.4 (and Spring Cloud AWS 2.3)

Sample application: https://github.com/awspring/spring-cloud-aws/blob/2.3.x/spring-cloud-aws-samples/spring-cloud-aws-secrets-manager-sample

2. Legacy mode in Spring Cloud Bootstrap phase. 

Sample application: https://github.com/maciej-scratches/spring-cloud-aws-secrets-manager-legacy-sample

I hope sample code clarifies questions, if there's something not working on your side, please create a Github repo that reproduces this issue.

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback
