### ISSUE TITLE
How to initialize RDS connection during application boostrap with setting stored in AWS SSM Parameter Store / Secrets Manager

### ISSUE THREAD

**Issue by klaphi** [awspring/spring-cloud-aws#163]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
I  am trying to setup a RDS connection during application boostrap from AWS SSM parameter store.  For that I was just trying to store the RDS parameters as key in AWS SSM parameter store. The problem is that square bracket are not allowed within keys. 

Trying to store something like _cloud.aws.rds.instances[0].db-instance-identifier_ as key in parameter store will end up with the following error:
````
_Error: error creating SSM parameter (/config/mySpringApp/cloud.aws.rds.instances[0].db-instance-identifier): ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-__
````
Trying the same in AWS secrets manager is more or less the same:

````
_Error: only alphanumeric characters and /_+=.@- special characters are allowed in "name"_
````

**Describe the solution you'd like**
I would expect that there is way that you can initialize a RDS dynamically during bootstrap. If the square brackets are not allowed there should be a different form to specify those keys which will also respect the limitations of special characters in key for AWS SSM parameter store and AWS secrets manager.

Maybe just introduce a way to store a key such as _/config/mySpringApp/cloud.aws.rds.instances[0].db-instance-identifier_ as /config/mySpringApp/cloud.aws.rds.instances_0_.db-instance-identifier and replace it dynamically during bootstrap into again _/config/mySpringApp/cloud.aws.rds.instances[0].db-instance-identifier_. 

**Describe alternatives you've considered**
-

**Additional context**

**Comment by maciejwalkowiak** [comment]
You can store password in another key that is referenced like this:

```properties
cloud.aws.rds.instances[0].db-instance-identifier=${myRdsPassword}
```

Does it solve your problem?

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback
