### ISSUE TITLE
Prefix for paramstore cannot be empty

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#167]
From spring-cloud-aws created by [JohannesZick](https://github.com/JohannesZick): spring-cloud/spring-cloud-aws#776  

**Type**: Bug

**Component**:
Parameter Store

**Describe the bug**
According to the documentation, the prefix can be either a valid path or empty. This is great, because I want to only have the application name, no static prefix. But in reality, there is a validation that rejects `null` and empty strings.

**Sample**
Simply use `aws.paramstore.prefix: ""` in `bootstrap.yml`. The validation is also easy to find in the `AwsParamStoreProperties.java`, [line 96](https://github.com/spring-cloud/spring-cloud-aws/blob/main/spring-cloud-aws-parameter-store-config/src/main/java/org/springframework/cloud/aws/paramstore/AwsParamStoreProperties.java#L96).

**Comment by maciejwalkowiak** [comment]
Either fix docs, or allow empty (if AWS allows it too).

**Comment by menneske2** [comment]
Bump
