### ISSUE TITLE
Document that cloud.aws.region.static must be set if not running in AWS

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#173]
From spring-cloud-aws created by [Slooz](https://github.com/Slooz): spring-cloud/spring-cloud-aws#784  

**Type**: Feature

**Is your feature request related to a problem? Please describe.**
A lot of people seem to get confused by the following error:

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3': Invocation of init method failed; nested exception is com.amazonaws.SdkClientException: Unable to load region information from any provider in the chain

#272, #251, #148

**Describe the solution you'd like**
While the error clearly points out the issue, the documentation doesn't make any mention of it. It has been said many times on GitHub issues, but it should also be documented:
https://github.com/spring-cloud/spring-cloud-aws/issues/148#issuecomment-218163733, https://github.com/spring-cloud/spring-cloud-aws/issues/272#issuecomment-397757049, https://github.com/spring-cloud/spring-cloud-aws/issues/339#issuecomment-636503818

**Describe alternatives you've considered**
I searched through GitHub for the recommended way to solve this issue, but that's not ideal

**Comment by essepuig** [comment]
Could you also please document what needs to be done in order to use a "custom region" ?

The current documentation for "cloud.aws.region.static" is : 

> Configures a static region for the application. Possible regions are (currently) us-east-1, us-west-1, us-west-2, eu-west-1, eu-central-1, ap-southeast-1, ap-southeast-1, ap-northeast-1, sa-east-1, cn-north-1 and any custom region configured with own region meta data

However, IMHO, it is not clear what needs to be done

**Comment by maciejwalkowiak** [comment]
@essepuig I think that if someone is a bit experienced with Spring Boot it should be clear that this property must be set..? If you have a better idea how to make it self explanatory, feel free to submit a PR.
