### ISSUE TITLE
Can't create a custom PropertySourceLocator that depends on AwsSecretsManagerPropertySourceLocator

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#175]
From spring-cloud-aws created by [petersonbr](https://github.com/petersonbr): spring-cloud/spring-cloud-aws#783  

**Type**: Bug

**Component**:
Secrets Manager

**Describe the bug**
Version: spring-cloud-aws: 2.2.6.RELEASE

I needed to create a custom `PropertySourceLocator`, and this property source needed to be processed after `AwsSecretsManagerPropertySourceLocator`. I've followed [this doc](https://bushkarl.gitbooks.io/spring-cloud/content/cloud_native_applications/spring_cloud_context_application_context_services.html#customizing-the-bootstrap-property-sources).

I debugged the code and found out that the class `PropertySourceBootstrapConfiguration` (`spring-cloud-context` project) is responsible for processing `PropertySourceLocator` classes. Since this class uses `AnnotationAwareOrderComparator.sort(this.propertySourceLocators)` to sort available locators, and `AwsSecretsManagerPropertySourceLocator` has no order defined, it is [always processed last](https://github.com/spring-projects/spring-framework/blob/4357749a63cabf86ef735dc936eef2ad8cbbff42/spring-core/src/main/java/org/springframework/core/OrderComparator.java#L38). 

**Alternative 1 - Didn't work for my scenario)**
Depending on the component you are trying to setup properties, it is possible to use a different approach, but it won't work for all types of components. It worked for `camel-aws2-*` components, but it didn't work for setting spring datasource properties, for example.
```java
@Configuration
@Priority(Ordered.HIGHEST_PRECEDENCE)
public class MyCustomPropertySource implements InitializingBean {

    @Autowired
    private ConfigurableEnvironment env;

    @Override
    public void afterPropertiesSet() throws Exception {
        Properties props = new Properties();
        props.put("my-prop-key", "my-prop-value");
        env.getPropertySources().addLast(new PropertiesPropertySource("my-custom-props", props));
    }
}
```

**Workaround**
I ended up doing the following workaround: I've "replaced" class `AwsSecretsManagerPropertySourceLocator` in my project (copied the class to the project using the same package/class names) and included a `@Priority` annotation in the class:
```java
@Priority(value = 0)
public class AwsSecretsManagerPropertySourceLocator implements PropertySourceLocator {
```

After this change, `PropertySourceBootstrapConfiguration` correctly sorted property locators and my custom property locator could use `AwsSecretsManagerPropertySourceLocator` properties.

**Possible Solution**
A possible and simple solution is to add a `@Priority`, `@Order` or implement `Ordered` interface in class `AwsSecretsManagerPropertySourceLocator`. I don't know if there is another way to create a custom `PropertySource` that depends on `AwsSecretsManagerPropertySourceLocator`.

**Comment by maciejwalkowiak** [comment]
To make it work, for `spring.config.import`, `ConfigDataLocationResolver` for PS and Secret Manager should implement `Ordered` interface and return an order from properties.

**Comment by MatejNedic** [comment]
Since `spring.config.import` takes care of processing `ConfigDataLocation` in order from last specified element in the list to first element. 
Meaning if we would have:
`spring.config.import=aws-secretsmanager:/config/spring,aws-parameterstore:/config/spring/`
First to be resolved would be `aws-parameterstore:/config/spring/` and after that `aws-secretsmanager:/config/spring` would be resolved.

This means that order of processing `ConfigDataLocationResolver` can be controlled by specifying elements in the list. I think we don't need to introduce `Ordered` since it is not bringing anything to the table in this case.
