### ISSUE TITLE
Logging for Parameter Store

### ISSUE THREAD

**Issue by stockf** [awspring/spring-cloud-aws#194]
**Type**: Bug / Help needed

**Component**:
"Parameter Store"

**Describe the bug**
I ran the sample for spring-cloud-aws-parameter-store and tried adding debug logging in order to see which parameters should be retrieved from SSM.

The [Documentation](https://docs.awspring.io/spring-cloud-aws/docs/2.3.0/reference/html/index.html#integrating-your-spring-cloud-application-with-the-aws-parameter-store) states that

>In order to find out which properties are retrieved from AWS Parameter Store on application startup, turn on DEBUG logging on io.awspring.cloud.paramstore.AwsParamStorePropertySource class.
>
>`logging.level.io.awspring.cloud.paramstore.AwsParamStorePropertySource=debug`

I added that to `application.properties` but I can see no debug logs. Can you please explain how to enable debug logging in your sample? Without that debugging will be a nightmare.

Thank you.

**Sample**
See https://github.com/awspring/spring-cloud-aws/tree/2.3.x/spring-cloud-aws-samples/spring-cloud-aws-parameter-store-sample

**Comment by ThalysGomes2020** [comment]
Not sure, but might be helpful 
we use logback as a logging framework, so I just added this on our `logback.xml`:
```xml
<logger name="io.awspring.cloud.paramstore" level="DEBUG"/>

2021-12-21 19:54:31,880 INFO  logger="io.awspring.cloud.paramstore.AwsParamStorePropertySourceLocator" marker="" message="Loading property from AWS Parameter Store with name: hgfdhgfdhgfd, optional: false" thread="restartedMain" 
2021-12-21 19:54:31,993 DEBUG logger="io.awspring.cloud.paramstore.AwsParamStorePropertySource" marker="" message="Populating property retrieved from AWS Parameter Store: xxx.client_id" thread="restartedMain" 
```
it might depend on your log framework
