### ISSUE TITLE
AWS SDK v2

### ISSUE THREAD

**Issue by driverpt** [awspring/spring-cloud-aws#20]
**Type**: Feature

Is Spring Cloud AWS 3.x going to use AWS SDK v2 exclusively ?

**Comment by MatejNedic** [comment]
Hey @driverpt,
3.x should be exclusevly in AWS sdk2. 
If you have any more questions or ideas please don't hesitate to [open a discussion](https://github.com/awspring/spring-cloud-aws/discussions) since it is I believe better way to communicate then issue.

**Comment by driverpt** [comment]
Alright then. Is there any branch I can create a PR on?

**Comment by MatejNedic** [comment]
The branch will be in this Github Repo, but there is no branch yet.  We plan on revisiting some of the integrations in 3.x. so it won't be just an upgrade to sdk2.
You can check the discussion in the old repo https://github.com/spring-cloud/spring-cloud-aws/issues/267 if you already haven't.
Hopefully, @maciejwalkowiak or @eddumelendez can say more.

**Comment by PhantomCaleb** [comment]
Is there someplace where we can view the status on 3.x?

**Comment by dmytrodanilenkov** [comment]
@MatejNedic how migration is going on? I see that no merges for 2 last months in branch v3.

**Comment by MatejNedic** [comment]
Hey @dmytrodanilenkov ,
we are working on rewrites so it will take a little longer than expected. Hopefully, things will start rolling again. 
If you have a desire PRs are welcome! :)

**Comment by dmytrodanilenkov** [comment]
@MatejNedic maybe you could point to small/minor issues I can start working on? Just to start get familiar with code base of project

**Comment by paulcwarren** [comment]
Hey folks, just checking in on this one.  What's the roadmap/timeline expectations for releasing this?

**Comment by migroskub** [comment]
+1

**Comment by lynch19** [comment]
+1

**Comment by migroskub** [comment]
@MatejNedic anywhere we can view the status?

**Comment by kauor** [comment]
@MatejNedic updates?

**Comment by MatejNedic** [comment]
Hopefully, things will start to move faster in 2022. Since in 3.0 we hope to rewrite SQS and SNS integration and potentially more. Currently, 3.0 is missing SQS, SNS, S3, Cognito, and RDS features. (ElastiCache is probably going to be removed). Sadly more answers than that I can't give at this time.

**Comment by driverpt** [comment]
Is there any PR with ongoing work on those components?

**Comment by MatejNedic** [comment]
@driverpt  as I am aware of there are no PRs active. You can check branch 3.x to see progress. There is a ticket for moving s3 to 3.x branch
https://github.com/awspring/spring-cloud-aws/issues/55.

**Comment by driverpt** [comment]
Yes. But are there any created Issues/PRs/Milestones to track?

**Comment by MatejNedic** [comment]
There is a Milestone for 3.0.x https://github.com/awspring/spring-cloud-aws/milestone/4 .
Some issues are missing like SQS and SNS for example since those integrations will be rewritten.

**Comment by roger751** [comment]
Is there any expected due date for the new version?

**Comment by jonathannaguin** [comment]
I believe the CloudWatch integration will need to be updated as well. Is that on the plan? Thanks!

**Comment by migroskub** [comment]
Any news?

**Comment by migroskub** [comment]
I currently see that there any no commits in this repository. Any reason? @MatejNedic Explantations would be very helpful since this is a very anticipated issue.

**Comment by migroskub** [comment]
Anybody here ?!

**Comment by eddumelendez** [comment]
@migroskub so sorry about this. There is a difference with the projects you mentioned, those are maintained by big companies. In this case, the project depends on some volunteers which dedicate their free time to the project which is not only working on the project itself but also experiment such this case which the idea to use aws sdk v2 is to enable and create native images.

**Comment by MazizEsa** [comment]
@MatejNedic  need any more help? If the migration effrot is broken into part it would be easier to contribute?

**Comment by driverpt** [comment]
Continuing discussion from #224, I think we should split `spring-cloud-aws-messaging` into Sync and Async.

I'm already working on migrating Spring Cloud AWS Messaging to the new `SqsClient`. We should create afterwards `spring-cloud-aws-messaging-async`

**Comment by MatejNedic** [comment]
@MazizEsa we are planning to finish a roadmap for 3.0 with issues soon. Need to consult with @maciejwalkowiak and @eddumelendez . Currently, we are working on closing existing PR's and releasing 2.3.4 and 2.4.0. 
We have plans for new integrations as well, some of them are even in the prototype phase. Since we are all doing this in our free time it is hard to make precise deadlines.

**Comment by maciejwalkowiak** [comment]
Integrations already migrated that are going to be released in Spring Cloud AWS 3.0 M1 

- S3
- SES
- SNS
- Parameter Store
- Secrets Manager

Which leaves us few more to be ported from 2.x in further milestones:

- RDS (https://github.com/awspring/spring-cloud-aws/issues/322)
- SQS (https://github.com/awspring/spring-cloud-aws/issues/344)
- CloudWatch (https://github.com/awspring/spring-cloud-aws/pull/237)

Closing this issue, as it's too wide. Look into specific integration issues/PRs to track progress.
