### ISSUE TITLE
Allow disabling profile specific loading of secrets and default secrets ( app name and defaultContext )

### ISSUE THREAD

**Issue by karim-elngr** [awspring/spring-cloud-aws#200]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**

I am currently using the following versions:
```xml
        <!-- Cloud -->
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-context</artifactId>
            <version>2.3.2</version>
        </dependency>
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-autoconfigure</artifactId>
            <version>2.3.2</version>
        </dependency>
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
            <version>2.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
            <version>3.0.4</version>
        </dependency>
```
I'm always frustrated when I need to load a secret from AWS Secrets Manager as an application property and I have to battle with the default behavior of `AwsSecretsManagerPropertySourceLocator` which relies on `AwsSecretsManagerPropertySources` specifically the method `List<String> getAutomaticContexts(List<String> profiles)` which loads profile specific secrets ( `<prefix>/<secret_name>_<profile-name>` while what I am trying to achieve is just loading a simple secret and nothing else because I usually have multiple AWS accounts and each account represents dev / staging / prod environments
```yaml
# I want to load secrets using the import style of spring boot
spring:
  config:
    import: aws-secretsmanager:my-super-simple-secret-and-nothing-else
```
I was tempted to do the following
```java
@BootstrapConfiguration(exclude = AwsSecretsManagerBootstrapConfiguration.class)
```
but as it turned out it was not enough because somehow excluding a bootstrap configuration does not work ( or I cannot get it to work properly ) https://github.com/spring-cloud/spring-cloud-commons/issues/1008

so I had to disable the secrets manager entirely to prevent the default behavior
```yaml
aws:
  secretsmanager:
    enabled: false
```

but this was not what I wanted because of `AwsSecretsManagerConfigDataLocationResolver` specifically the method `isResolvable` relies on having secrets manager enabled which makes sense
```Java
        @Override
	public boolean isResolvable(ConfigDataLocationResolverContext context, ConfigDataLocation location) {
		if (!location.hasPrefix(PREFIX)) {
			return false;
		}
		return context.getBinder().bind(AwsSecretsManagerProperties.CONFIG_PREFIX + ".enabled", Boolean.class)
				.orElse(true);
	}
```

If I wanted the ` import: aws-secretsmanager:` to work, I had to write a new custom `ConfigDataLocationResolver` and add it in spring factories and hack around to get importing using secrets manager to work while having `enabled: false`
```Java
public class EnabledAwsSecretsManagerConfigDataLocationResolver extends AwsSecretsManagerConfigDataLocationResolver {

    public EnabledAwsSecretsManagerConfigDataLocationResolver(Log log) {
        super(log);
    }

    @Override
    public boolean isResolvable(ConfigDataLocationResolverContext context, ConfigDataLocation location) {
        return location.hasPrefix(PREFIX);
    }
}
```

And that was the hack I used to prevent the default secrets loading behavior while maintaining the import style working

**Describe the solution you'd like**
I would like to have a clear way to distinguish between two features
1- Secrets manager enabled flag ( and can be used to import secrets ) ( basically just that secret manager works and no additional work is done )
2- Loading profile specific default opinionated secrets enabled flag ( which can be disabled to avoid a lot of the problems mentioned above )

**Describe alternatives you've considered**
I am not sure if there is a better ways to do this, any ideas?

**Additional context**
N/A

**Comment by maciejwalkowiak** [comment]
I am not sure why `spring.config.import` isn't working for you.  Perhaps you still have `spring-cloud-starter-bootstrap` in your dependencies?

Take a look at Secrets Manager integration sample in this repository. Ideally, please provide a reproducible example where we can debug what is causing the problem.

**Comment by karim-elngr** [comment]
@maciejwalkowiak thanks for your response, Yes I had `spring-cloud-starter-bootstrap` in my dependencies, The problem resolved when I removed it, I will close this issue
