### ISSUE TITLE
Document how to provide custom credentials for Spring config import of aws-parameterstore

### ISSUE THREAD

**Issue by internetstaff** [awspring/spring-cloud-aws#205]
It's unclear how to or if we can provide custom credentials with `spring.config.import`

In 2.2.6, we were defining `org.springframework.cloud.bootstrap.BootstrapConfiguration` in `spring.factories` to a `@Configuration` class that returned an AWSSimpleSystemsManagement with custom credentials.

In 2.3.2, we noticed this method can no longer discover the `spring.application.name` from an `application.yaml`, it must be in the `bootstrap.yaml`. We hoped to just switch to `spring.config.import`, but haven't figured out how to make our custom SSMClient available.

We've fiddled with several permutations of injecting e.g. `ConfigurableBootstrapContext` into our `@Configuration` class so it could register a supplier (or instance) of `AWSSimpleSystemsManagement.class` but it never appears to be in the bootstrap context of the config resolvers.

Is there a known way to achieve this?

Thanks!

**Comment by maciejwalkowiak** [comment]
Apologies for late reply. This is indeed tricky.

In `META-INF/spring.factories` define `BootstrapRegistryInitializer`. For example:

```properties
org.springframework.boot.BootstrapRegistryInitializer=io.awspring.cloud.samples.secretsmanager.CustomBootstrapConfiguration
```

Where in `CustomBootstrapConfiguration` you can configure custom `AWSSecretsManager` bean:

```java
import com.amazonaws.services.secretsmanager.AWSSecretsManager;

import org.springframework.boot.BootstrapRegistry;
import org.springframework.boot.BootstrapRegistryInitializer;

public class CustomBootstrapConfiguration implements BootstrapRegistryInitializer {

	@Override public void initialize(BootstrapRegistry registry) {
		registry.register(AWSSecretsManager.class, context -> {
			// return bean
		});
	}
}
```

Let me know if this helps.
