### ISSUE TITLE
Reactive S3 adapter - Project Reactor support

### ISSUE THREAD

**Issue by roger751** [awspring/spring-cloud-aws#214]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
As specified in https://github.com/spring-cloud/spring-cloud-aws/issues/802 and in https://github.com/spring-projects/spring-integration-aws/issues/198, there should be support for Reactive Streams in the new AWS SDK v2 rewrite. I would be glad if this would be added to the milestone https://github.com/awspring/spring-cloud-aws/milestone/4.

**Describe the solution you'd like**
Enable the usage of Project Reactor with `spring cloud aws`.

**Describe alternatives you've considered**
As previously mentioned, this is a great example of self implementation https://github.com/eugenp/tutorials/tree/master/aws-reactive.

**Comment by ipanimnim** [comment]
@maciejwalkowiak any updates on this?

**Comment by ipanimnim** [comment]
I think it would also be nice if there would be support for Spring Integration with Project Reactor. Something like `ReactiveS3MessageHandler`

**Comment by maciejwalkowiak** [comment]
Not yet, but once https://github.com/awspring/spring-cloud-aws/pull/275 is done, this issue will become open for contributions.

**Comment by jifeiiii** [comment]
Anticipated feature. Also wanted with https://github.com/spring-projects/spring-integration-aws/issues/198 - a Reactive Spring Integration channel adapter.

**Comment by migroskub** [comment]
@maciejwalkowiak can you update the progress? I haven't seen any usage of `S3AsyncClient`

**Comment by maciejwalkowiak** [comment]
In regards to reactive - thinking how to do it right. We can easily auto-configure `S3AsyncClient` but likely we can do more. One is integrating code from Baeldung, another one is wrapping `S3AsyncClient` `CompletableFutures` with `Mono` in `S3ReactiveClient`. Wrapping could be done actually for all async clients. 

If you have more ideas please share, perhaps we can come up here with conclusions and open this issue for contributions.

**Comment by migroskub** [comment]
I think that `S3ReactiveClient` could be great, but only if the user would still have access to the `S3AsyncClient` to configure stuff (like path/ regions specific customizations and more). In general I think this is the best option. Also you can take a look at this [great repo](https://github.com/paulcwarren/spring-content/blob/main/spring-content-s3/src/main/java/internal/org/springframework/content/s3/store/DefaultReactiveS3StoreImpl.java).

**Comment by ipanimnim** [comment]
Yeah wrapping `S3AsyncClient` sounds like the ideal way to go

**Comment by ipanimnim** [comment]
I'd put `S3AsyncClient` as an argument in the constructor of `S3ReactiveClient`

**Comment by jifeiiii** [comment]
Any progress and a tracking issue so people can help?

**Comment by maciejwalkowiak** [comment]
Design work is pending. We are open for suggestion or even PRs but can't guarantee that anything will get merged until we do more research.

**Comment by sgarfinkel** [comment]
The latest versions of the SDK allow you to return an `SdkPublisher<ByteBuffer>` (which extends `Publisher<ByteBuffer>`) which you can use to map to the underlying byte array: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/internal/async/PublisherAsyncResponseTransformer.html.

The main issue with doing this is backpressure management is a bit of a pain here , from what I understand the upstream Publisher will basically buffer endlessly until finished, which for large files with slow consumers isn't necessarily ideal.

**Comment by rolkhas2** [comment]
@sgarfinkel I see that the [Publisher](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/internal/async/PublisherAsyncResponseTransformer.html) you've mentioned is on an `internal` directory. I'm not sure if that's targeted for public use.

**Comment by lynch19** [comment]
@maciejwalkowiak Can you publish the timeline for this issue? Users like me depend on this and cannot use `Spring-Cloud-AWS` at all without this issue being resolved.

**Comment by maciejwalkowiak** [comment]
@lynch19 it's almost certain this will not end up in 3.0. We have still too much work with other integrations to do before we can start working on reactive support. But, we're open for suggestions/contributions - if you have an idea how reactive support could look like, please let us know.

**Comment by lynch19** [comment]
@maciejwalkowiak I can try to take a basic start for this, but I'm not sure what have been already planned, or shall I just open some PR and let the discussion flow

**Comment by maciejwalkowiak** [comment]
Nothing has been planned so far so feel free to open a sketch PR but please keep in mind that it may not get merged.

**Comment by zaredea** [comment]
Would there be any progress on this subjectsoon?

**Comment by maciejwalkowiak** [comment]
@zaredea No unless someone from the community comes up with a sketch PR.

**Comment by maciejwalkowiak** [comment]
Considering the efforts needed to support reactive APIs we took the decision to not develop it in near future. We may embrace in the future async clients more than we do right now, which would make it easier for users to adapt to reactive apis themselves.
