### ISSUE TITLE
Default configuration of AbstractMessageChannelMessagingSendingTemplate leads to Jackson error: "Could not write JSON: Java 8 date/time type `java.time.Instant` not supported by default"

### ISSUE THREAD

**Issue by 0ka** [awspring/spring-cloud-aws#217]
**Type**: Bug

**Component**: SQS

**Describe the bug**
Using Jackson 2.13 and trying to send messages (QueueMessagingTemplate.convertAndSend) that contains fields of Java date/time types lead to the following Jackson error:
"Could not write JSON: Java 8 date/time type `java.time.Instant` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling"

According to this ticket https://github.com/spring-projects/spring-boot/issues/26859 Spring normally configure the ObjectMapper bean correct to support Java date/time during serialization.

But the class io.awspring.cloud.messaging.core.support.AbstractMessageChannelMessagingSendingTemplate creates an own MappingJackson2MessageConverter with a default ObjectMapper without using already configured beans.

I would expect that awspring also configure the ObjectMapper to support date/time types if com.fasterxml.jackson.datatype:jackson-datatype-jsr310 is on the class path or better to use an existing ObjectMapper bean.

**Comment by psharma85** [comment]
Hi, I am facing this issue. /info giving error. I am not using custom ObjectMapper instead using com.fasterxml.jackson.databind.ObjectMapper;
Can someone please help me?

**Comment by maciejwalkowiak** [comment]
We are using default `ObjectMapper` for deserialization, but as `QueueMessagingTemplate` bean is not created by auto-configuration, you must create it properly to get the  support for already registered Jackson modules:

```java
MappingJackson2MessageConverter converter = new MappingJackson2MessageConverter();
converter.setObjectMapper(objectMapper);
converter.setSerializedPayloadClass(String.class);
return new QueueMessagingTemplate(amazonSqs, (ResourceIdResolver) null, converter);
```

I believe we should auto-configure `QueueMessagingTemplate`.
