### ISSUE TITLE
Secrets Manager - Configure a secret whose `name` doesn't contain a slash `/`

### ISSUE THREAD

**Issue by arutsudar** [awspring/spring-cloud-aws#222]
**Type**: Bug

**Component**: Secrets Manager

**Describe the bug**
If I have a `Secret` which doesn't have any prefix, I am not able to configure that properly in the `boostrap.yml` file.
Spring Cloud version `2.3.3`.

**Sample**
For Eg.: If my secret name is `secret1` (Notice that there is no `/` in the name), then, in the `boostrap.yml` file,
- if I mention only the `prefix` to be `secret1`, then it checks for the secret with name `secret1/application`
- if I mention only the `defaultContext` to be `secret1`, then it checks for the secret with name `/secret/secret1`
- Below are the validation errors that I get if I give any of the fields like `prefix` or `defaultContext` with empty values.
    - `prefix should not be empty or null.`
    - `defaultContext should not be empty or null.`
- If I don't even specify those fields, then, it is taking the default value as  `/secret/application` and failing as there is no such secret.

**It would be nice to have a feature where the secret name doesn't contain any slash in it.**
Or, we can have an additional field where we should be able to give the exact secret name in it.
If it already exists, sorry for raising an issue regarding this.
Kindly help me in configuring my app to use such a secret.

Let me know if any other details are needed regarding this.

**Comment by maciejwalkowiak** [comment]
It is already possible - load properties using `spring.config.import` introduced in Spring Cloud AWS 2.3 and Spring Boot 2.4:

```
spring.config.import: aws-secretsmanager: secret1
```

It is not supported if you use legacy `spring-cloud-bootstrap` way of loading secrets and we do not plan to add support for it.
