### ISSUE TITLE
Migrate Spring Cloud AWS Messaging to AWS SDK V2

### ISSUE THREAD

**Issue by driverpt** [awspring/spring-cloud-aws#224]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
As title says

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by driverpt** [comment]
Open Topic for Discussion:

Currently AWS SDK V2 has Sync and Async Versions. Both are not compatible. Should we use Sync version or Async as Base?

Currently `AmazonSQSAsync` is being used everythere but only Sync Calls are being used, with `SqsAsyncClient` only `CompletableFuture` based API is available.

Which one do you suggest we use? IMHO, it makes sense to use the Sync Client to initialize Spring, and Async Client for `SqsListener`.

WDYT?

**Comment by maciejwalkowiak** [comment]
I imagine async client should be used for reactive scenarios (as it is non blocking) and sync client for the regular blocking (like in Spring Cloud AWS 2.x). 

I'll dig into migrating SQS to AWS SDK v2 in upcoming days. For now i am closing this in favour of https://github.com/awspring/spring-cloud-aws/issues/20, but i am open for discussion.

**Comment by sowmyaraghu** [comment]
Is the support for AWS SQS listener added to Spring Cloud AWS 3.x yet?

**Comment by maciejwalkowiak** [comment]
@sowmyaraghu not yet but work is in progress look #374
