### ISSUE TITLE
spring-cloud-starter-aws: setting `configurationSetName`

### ISSUE THREAD

**Issue by kornicameister** [awspring/spring-cloud-aws#234]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**

Ability to specify configuration set when sending emails with `SimpleEmailServiceJavaMailSender`.
It seems like perfectly fine use case that if we use `SimpleEmailServiceJavaMailSender` and as such `SES` client we can control which config set is used. It is impossible because `org.springframework.cloud.aws.mail.simplemail.SimpleEmailServiceJavaMailSender#send(javax.mail.internet.MimeMessage...)` does not expose any way to inject `configurationSetName` into `SendRawEmailRequest` object coming from AWS SDK.

I don't have preference as to implementation but I am included to say that ability to set `configurationSetName` scoped to an instance of `SimpleEmailServiceJavaMailSender` is a solution that I like. For one I don't feel like it would be clear API to allow to set it on `send(...)` method because of incompatibilities with parent class. Another idea to create `protected` method to create `SendRawEmailRequest` would require you to subclass anyway so I would simply add a second constructor that allows to specify configuration set name and later on set on on `SendRawEmailRequest`.

**Describe the solution you'd like**

I want to be able to specify configuration set name.

**Describe alternatives you've considered**

Subclassing `SimpleEmailServiceJavaMailSender` and overriding entire `send` method.

**Additional context**

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-aws</artifactId>
            <version>2.2.4.RELEASE</version>
        </dependency>
```

PS. I might be able to help out.

**Comment by kornicameister** [comment]
Couple of things:
1. component is `ses` and not `sns` :P
2. I've just read you can actually specify configuration set-name per message so wonder if API change is not actually needed to correlate message with configuration set name.

**Comment by maciejwalkowiak** [comment]
1. My bad, thanks for pointing it out.
2. I can see supporting this on the mail sender level, but if its needed per message I don't think we can include it in Spring Cloud AWS, at least not in 2.x. You're welcome to try things out and if you come up with nice solution we can think about integrating it.

**Comment by maciejwalkowiak** [comment]
@kornicameister You're welcome to contribute a PR!

**Comment by maciejwalkowiak** [comment]
Closing due to lost interest ;-)
