### ISSUE TITLE
Getting `QueueDoesNotExistException` with local `cloud.aws.sqs.endpoint` cause `cloud.aws.sqs.region` is not set

### ISSUE THREAD

**Issue by xtaixe** [awspring/spring-cloud-aws#244]
**Type**: Bug

**Component**: SQS

**Describe the bug**
Getting `QueueDoesNotExistException` when testing locally with LocalStack even after setting both `cloud.aws.sqs.endpoint` and `cloud.aws.sqs.region`.

AFAIK, now that LocalStack supports multi region, the region must be provided, but it seems that the `AmazonWebserviceClientFactoryBean` won't set the region if a custom endpoint is provided: https://github.com/awspring/spring-cloud-aws/blob/218a4d1b66d90f4d6e2c76a9b778d71faec14447/spring-cloud-aws-core/src/main/java/io/awspring/cloud/core/config/AmazonWebserviceClientFactoryBean.java#L113-L128

The workaround is to define a properly configured `AmazonSQS` bean, but it would be nice if things would also just work for local endpoints.

**Comment by maciejwalkowiak** [comment]
AWS Java SDK does not allow setting both endpoint and region, so i am not sure really how to make it work. If you have a suggestion you're welcome to draft a PR a a subject to discussion.

**Comment by xtaixe** [comment]
Not sure I follow, do you mean the builder will throw an error if you set both? I'm pretty sure we've done that, but maybe it was the AWS SDK v2...

Anyway, the `AwsClientBuilder.EndpointConfiguration` constructor used above has a `signingRegion` that is being set to `null`. Setting that to the configured region should also work (it's what I did when creating a custom `AmazonSQS` bean as a workaround).

**Comment by maciejwalkowiak** [comment]
Yes indeed builder will throw in such case. I'll look again into setting signing region
