### ISSUE TITLE
Spring cloud aws parameter store config does not work with spring native 0.11.2

### ISSUE THREAD

**Issue by FalkWoldmann6232** [awspring/spring-cloud-aws#250]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
When compiling to a binary with spring native 0.11.2, the application cannot start because of a missing native reflection configuration:

```
Native reflection configuration for io.awspring.cloud.autoconfigure.paramstore.AwsParamStoreConfigDataLocationResolver is missing.

Action:
Native configuration for a class accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.
```

**Describe the solution you'd like**
It would be nice to have a native reflection configuration that is already provided 

**Describe alternatives you've considered**
I could add a custom native hint

**Comment by maciejwalkowiak** [comment]
AFAIK AWS SDK v2 is GraalVM native image compatible, so we are going to try to make Spring Cloud AWS 3.0 (based on AWS SDK v2) Spring-Native compatible. For now, there are no plans to do anything with Spring Native in 2.x
