### ISSUE TITLE
AWS SQS consumer does not consumes messages

### ISSUE THREAD

**Issue by serh-ai** [awspring/spring-cloud-aws#259]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
When @SqsListener count is bigger than the thread available, I want to a see warning/error message. Also, I observe strange behavior, that it consumes only one event on shutdown(maybe because of some threads are become available )

**Sample**
Let's say we have 4 @SqsListener 's for different events. Also, I have some setup of thread pools(usually it set up on project init phase and never changed)
```
    @Bean
    public SimpleAsyncTaskExecutor sqsAsyncTaskExecutor() {
        SimpleAsyncTaskExecutor simpleAsyncTaskExecutor = new SimpleAsyncTaskExecutor();
        simpleAsyncTaskExecutor.setConcurrencyLimit(4);
        return simpleAsyncTaskExecutor;
    }
```
When I add a new @SqsListener(let's say after 1 year, it is number 5), it will not consume any event, because it simply doesn't have thread capacity. On that case it will be nice to log some error/warning message on springboot app startup

**Comment by maciejwalkowiak** [comment]
For 2.x PRs welcome.
For 3.x we just need to make sure that it's not the case in the new implementation cc @tomazfernandes

**Comment by tomazfernandes** [comment]
In 3.0 we create a new task executor instance per container, i.e. per `@SqsListener` annotation. We can't share the same `TaskExecutor` instance between many containers because the containers manage the `TaskExecutor`'s lifecycle.

A `TaskExecutor` can be set in the `ContainerOptions`, then the container won't manage its lifecycle.

**Comment by tomazfernandes** [comment]
One key difference is that we don't use threads to poll, so the pool size only influences the maximum number of messages that can be processed simultaneously.

If too few threads are configured in the pool, it should either be queued or throw an `TaskRejectedException`, depending on how the executor is configured.

**Comment by serh-ai** [comment]
For me it ok in v3, just put this issue so other devs can google it, and not waste their time :)  Unfortunately it's not possible to test v3 on production now. Thanks for your work!
