### ISSUE TITLE
Expiration value doesn't work when using ElastiCache + Redis on a specific cluster

### ISSUE THREAD

**Issue by efumas** [awspring/spring-cloud-aws#260]
**Type**: Bug

**Component**:
ElastiCache

**Describe the bug**
- Spring Cloud AWS Version: 2.4.0
- Spring Boot Starter Data Redis: 2.6.4
- AWS Java SDK ElastiCache: 1.12.172 

We are trying to use AWS ElastiCache + Redis and the "expiration" values don't work.
It seems that the RedisCacheFactory when it creates the cache it uses the default constructor of DefaultRedisCacheWriter when the Duration (TTL) is 0.

  DefaultRedisCacheWriter(RedisConnectionFactory connectionFactory, BatchStrategy batchStrategy) {
    this(connectionFactory, Duration.ZERO, batchStrategy);
  }

So then, when we want to put an item in the cache using @CachePut, the TTL is null and it always put the value without an expiration time. So, if we want to expire the element we need to do manually using @CacheEvict 

If we test the same code with ElastiCache + Memcached the library works perfect and the item expires after the value that we indicate on the properties.

**Sample**

- Application.yaml

cloud:
  aws:
    elasticache:
      clusters:
        - name: redis-01
          expiration: 12

**Comment by maciejwalkowiak** [comment]
Thanks for reporting, but i must close it as 2.x is not maintained anymore.
