### ISSUE TITLE
Provide customization option to enable ForcePathStyleAccess for AmazonS3

### ISSUE THREAD

**Issue by sivaprasadreddy** [awspring/spring-cloud-aws#267]
**Type**: Feature

Currently there is no customization option that we can configure to enable `ForcePathStyleAccess` for `AmazonS3` via `application.properties/yml`. A work around is to define our own `AmazonS3` bean definition, however as this is very commonly used option especially with **LocalStack** it would be nice to have this option.

**Comment by maciejwalkowiak** [comment]
Already in progress in https://github.com/awspring/spring-cloud-aws/pull/275

**Comment by maciejwalkowiak** [comment]
Fixed in #275.
