### ISSUE TITLE
configure whether aws sdk library version 1 oder 2 should be used

### ISSUE THREAD

**Issue by ehmkah** [awspring/spring-cloud-aws#279]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
We are using version 2 of the aws sdk library more or less software.amazon.awssdk:sqs:2.17.88 and configure a awscredentials provider. This credentials provider is of type AwsCredentialsProvider. Then we configure a message consumer which is anotted with '@sqslistener` and the name of the queue.  During startup of the application [DynamicQueueUrlDestinationResolver](https://github.com/awspring/spring-cloud-aws/blob/2.4.x/spring-cloud-aws-messaging/src/main/java/io/awspring/cloud/messaging/support/destination/DynamicQueueUrlDestinationResolver.java) is using AmazonSQS for getting the queue-url. Unfortunately this AmazonSQS is from aws sdk version 1 for which the default credentials configuration is used. Since I configured my credentials provider explicitly for aws sdk version 2 it is not working. 

Pseudocode, because i am away from the IDE:
the following
```
GetQueueUrlResult getQueueUrlResult = this.amazonSqs.getQueueUrl(new GetQueueUrlRequest(queueName));
				return getQueueUrlResult.getQueueUrl();
```

should be changed to (types need to be adjusted and sqsClient needs to be injected)
```
if(awsSdkVersion=="2") {
GetQueueUrlResult getQueueUrlResult = this.sqsClient.getQueueUrl(new GetQueueUrlRequest(queueName));
				return getQueueUrlResult.getQueueUrl()
} else  {
old implementation
};
```

**Describe the solution you'd like**
I would prefer that I could configure which version of the aws sdk should be used under the hood. E.g. useSDKversion=2 At least for the lookup of the queue-urls because this is hurting me.

**Describe alternatives you've considered**
- Current work-around: provide an additional CredentialsProvider for Version 1 of the aws sdk

**Additional context**
-

**Comment by maciejwalkowiak** [comment]
Supporting both v1 and v2 would be insanely expensive. We are already working on Spring Cloud AWS 3.0 that will be based only on AWS SDK v2.

**Comment by ehmkah** [comment]
Thank you for the fast reply. So we wait for spring boot cloud aws 3.0 :-)

Just for curiosity. It would be better if we do not mix the aws sdk v2 with spring cloud aws?

**Comment by maciejwalkowiak** [comment]
Since both can work side by side, there's no issue with mixing them in your project. I only meant that from maintaining Spring Cloud AWS point of view it would be very time consuming to support both v1 and v2.
