### ISSUE TITLE
Publish 3.0 snapshot documentation

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#289]
Configure Github action to publish snapshots docs for 3.0.x branch to https://docs.awspring.io/spring-cloud-aws/docs/

**Comment by neiljbrown** [comment]
Hi @maciejwalkowiak, in case you weren't aware (and assuming you're ready with the 3.0.x snapshot docs) - I get an Access Denied error on attempting to view the docs at https://docs.awspring.io/spring-cloud-aws/docs/ - 
![image](https://user-images.githubusercontent.com/1330794/161628008-ee186177-d064-44ce-a99a-bc5cbcc30f63.png).

Cheers.

**Comment by maciejwalkowiak** [comment]
https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html - this is the correct link. Docs are not up to date though, we will work on it before M1 gets released.
