### ISSUE TITLE
Publish API docs

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#290]
Configure Github action to publish API docs (generated from Javadocs) to https://docs.awspring.io/spring-cloud-aws/docs

**Comment by migroskub** [comment]
https://docs.awspring.io/spring-cloud-aws/docs shows "Access Denied" message

**Comment by maciejwalkowiak** [comment]
@migroskub reference docs are under: https://docs.awspring.io/spring-cloud-aws/docs/2.4.0/reference/html/index.html We still have to change github action to upload Javadocs (they get generated during build, just not uploaded).

**Comment by maciejwalkowiak** [comment]
Surprise surprise they were actually published: https://docs.awspring.io/spring-cloud-aws/docs/2.4.0/apidocs/index.html
