### ISSUE TITLE
IAM Database authentication for RDS

### ISSUE THREAD

**Issue by marcindabrowski** [awspring/spring-cloud-aws#320]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
It is possible to authenticate to DB instance using AWS Identity and Access Management (IAM) database authentication.
It is more secure because you are not using passwords.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html

**Describe the solution you'd like**
Currently, the password is needed in bean configuration defined in spring-cloud-aws-jdbc-1.2.xsd.

**Describe alternatives you've considered**
As for now, MariaDB's JDBC driver has a built-in feature to use it, but PostgreSQL does not.

This feature was already requested in old repository: https://github.com/spring-attic/spring-cloud-aws/issues/256

**Comment by maciejwalkowiak** [comment]
IAM authentication will be possible with Spring Cloud AWS 3.0. At this stage, if you don't need replica sets just want to use IAM authentication consider using https://github.com/awslabs/aws-mysql-jdbc

**Comment by maciejwalkowiak** [comment]
Replaced by #322
