### ISSUE TITLE
Migrate Cognito integration to AWS SDK v2

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#335]
1. Migrate Cognito integration from branch `2.4.x` to `main` using AWS SDK v2.
2. Update docs
3. Provide a sample app
4. Consider implementing https://github.com/awspring/spring-cloud-aws/issues/132

**Comment by maciejwalkowiak** [comment]
cc @eddumelendez @rieckpil

**Comment by eddumelendez** [comment]
cognito auto-configuration doesn't use aws sdk. I have submitted #340

**Comment by maciejwalkowiak** [comment]
Closing as the only thing we need for Cognito is #132
