### ISSUE TITLE
Gitpod Integration Enhancement - Open With Gitpod Button

### ISSUE THREAD

**Issue by anugrahsinghal** [awspring/spring-cloud-aws#358]
The `Open with Gitpod` Button, uses to the upstream repo [spring-cloud-aws](https://github.com/awspring/spring-cloud-aws)/`main`.
Would it be better to have the button open the `fork/branch` for the user/contributor is working on?

The gitpod button can be changed to point to the user-specific fork/branch.

Please let me know if this sounds like a good idea, I'd be willing to work on it.

**Comment by maciejwalkowiak** [comment]
I got a feeling that when users see "Open with Gitpod" they don't expect a fork to be created for them. Ideally, we do not surprise users at all :-) 

When I tried Gitpod & VSCode, when push is made it soft of guides by hand that you don't have rights to push to origin and creates a fork for you - so i don't see this as an issue. But perhaps I am missing something and this can be done better. If it's not too much work for you - perhaps we can take decision when i see it in action?

**Comment by anugrahsinghal** [comment]
Perhaps I could not explain the whole context.

I did not mean that `Open with Gitpod` will create a fork.

I mean as a user that already has an existing fork - when I click on `Open in Gitpod` on my `fork/branch`, it actually checks out my version of the code instead of the upstream one.
i.e. 
say with a user `Alice` has `no fork` of https://github.com/awspring/spring-cloud-aws/

they click on `Open in Gitpod` on https://github.com/awspring/spring-cloud-aws/ it opens the same.

But, later they `create their own fork` of the repo.
On their fork say `alice/spring-cloud-aws` when they click on `Open in Gitpod` it still opens https://github.com/awspring/spring-cloud-aws/ with out current config.

Instead what we want is when they click on `Open in Gitpod` on their fork.
It opens up `alice/spring-cloud-aws` on gitpod.

hope I am making sense 😅 

You can see it in action here.
https://github.com/anugrahsinghal/spring-cloud-aws/tree/gitpod-on-user-fork

Click on the `Open in Gitpod` here and it will open up `myFork+branch` of the codebase on gitpod.

**Comment by anugrahsinghal** [comment]
https://spectrum.chat/gitpod/general/how-to-specify-users-fork-instead-of-main-repository~d4c0e615-511d-409e-9ffc-796869fe4708

**Comment by maciejwalkowiak** [comment]
Ah, definitely makes sense! Please go with a PR.

One thing to note - privacy oriented browsers do not pass the referrer header and this approach does not work. Please add a note about this in https://github.com/anugrahsinghal/spring-cloud-aws/blob/gitpod-on-user-fork/CONTRIBUTING.md

**Comment by anugrahsinghal** [comment]
apologies for the delay.

Opened PR #383, please take a look.
