### ISSUE TITLE
Gitpod Enhancements - use mvnd by default

### ISSUE THREAD

**Issue by anugrahsinghal** [awspring/spring-cloud-aws#359]
The README.md file for the project suggests, using `mvnd` for faster builds.

The gitpod runtime can be configured to provide the `mvnd` runtime out-of-the-box.

Please let me know if this sounds like a good idea, I'd be willing to work on it.

**Comment by maciejwalkowiak** [comment]
I've actually tried it - and added `brew install mvndaemon/homebrew-mvnd/mvnd` in the init phase. The problem is that it takes ages to install. If you find a better/faster way to do it, i am very open!

**Comment by anugrahsinghal** [comment]
what kind of time benchmarks are we expecting?

I tried using sdkman on the gitpod instance and it was pretty fast.

Could you take a look here
https://gitpod.io/#https://github.com/anugrahsinghal/spring-cloud-aws/tree/gitpod-mvnd

**Comment by maciejwalkowiak** [comment]
Ok i am sold! With brew it took minutes to install, here I did not even realise when installation finished. Send PR @anugrahsinghal

**Comment by anugrahsinghal** [comment]
have raised the PR
https://github.com/awspring/spring-cloud-aws/pull/360

Please let me know if this needs any changes.
