### ISSUE TITLE
Path matched S3 resource is not loaded

### ISSUE THREAD

**Issue by dmlogs** [awspring/spring-cloud-aws#370]
**Type**: Bug

**Component**:
S3

**Describe the bug**
Spring Boot 2.7.0-M3
Spring Cloud AWS 2.4.1

Per documentation [`PathMatchingSimpleStorageResourcePatternResolver`](https://github.com/awspring/spring-cloud-aws/blob/2.4.x/spring-cloud-aws-core/src/main/java/io/awspring/cloud/core/io/s3/PathMatchingSimpleStorageResourcePatternResolver.java) should load resources from `S3` with `SimpleStorageProtocolResolver` but instead resources are loaded with the `ResourcePatternResolver` delegated for [resolving common paths](https://github.com/awspring/spring-cloud-aws/blob/a5a03ced8c2dc73fc4f407fa3d8cd2db9da0eb67/spring-cloud-aws-core/src/main/java/io/awspring/cloud/core/io/s3/PathMatchingSimpleStorageResourcePatternResolver.java#L76)

`SimpleStorageProtocolResolver` is never leveraged in this class.

The resolver correctly looks up all objects which match the pattern in S3, but then [delegates](https://github.com/awspring/spring-cloud-aws/blob/2.4.x/spring-cloud-aws-core/src/main/java/io/awspring/cloud/core/io/s3/PathMatchingSimpleStorageResourcePatternResolver.java#L288) to the provided 
`resourcePatternResolverDelegate` instead of a `SimpleStorageProtocolResolver`

**Sample**
```
ResourcePatternResolver resolver = new PathMatchingSimpleStorageResourcePatternResolver(AmazonS3ClientBuilder.defaultClient(), new PathMatchingResourcePatternResolver())

Resource[] resources = resolver.get("s3://mybucket/mypath/*")
```

Expected:
`resources` contains `SimpleStorageResource` objects for each object found in the path

Actual:
`resources` contain `ClassPathContextResource` objects.

**Comment by maciejwalkowiak** [comment]
Have you tried setting it up as [explained in the docs](https://docs.awspring.io/spring-cloud-aws/docs/2.4.1/reference/html/index.html#searching-resources), with passing application context as the second parameter?

**Comment by dmlogs** [comment]
Thanks @maciejwalkowiak , that did resolve correctly. I would request a documentation update, I personally interpret the current language as using this resolver only when it does not resolve an s3 path:

[`@param resourcePatternResolverDelegate - delegate resolver used to resolve common path (file, classpath, servlet etc.)`](https://github.com/awspring/spring-cloud-aws/blob/2.4.x/spring-cloud-aws-core/src/main/java/io/awspring/cloud/core/io/s3/PathMatchingSimpleStorageResourcePatternResolver.java#L76)

**Comment by maciejwalkowiak** [comment]
@dmlogs could you please create a PR with this change to `2.4.x` branch?

**Comment by maciejwalkowiak** [comment]
Closing. @dmlogs feel free to drop a PR.
