### ISSUE TITLE
Fail on startup if sqs queue does not exist

### ISSUE THREAD

**Issue by boolivar** [awspring/spring-cloud-aws#393]
**Type**: Feature

**The problem**
If queue specified for `SqsListener` is not exists at the time of application startup, `SimpleMessageListenerContainer` simply ignores that queue and continue without subscribing, it just puts WARN message in the logs. 

**Possible solution**
It would be nice to have a possibility to fail on startup if queue does not exist.

**Alternative**
Another alternative is to wait for queue and start listening when queue appears in sqs.

**Current workaround**
Workaround is to throw exception from `destinationResolver` that will not be catched by `SimpleMessageListenerContainer`:

```java
public class FailingDestinationResolver<T> implements DestinationResolver<T> {
    
    private final DestinationResolver<T> destinationResolver;

    public FailingDestinationResolver(DestinationResolver<T> destinationResolver) {
        this.destinationResolver = destinationResolver;
    }

    @Override
    public T resolveDestination(String name) {
        try {
            return destinationResolver.resolveDestination(name);
        } catch (DestinationResolutionException e) {
            throw new RuntimeException("Fail to resolve '" + name + "' destination", e);
        }
    }
}
```
Configuration `SimpleMessageListenerContainerFactory` bean with destination resolver:
```java
@Bean
public SimpleMessageListenerContainerFactory sqsListenerContainerFactory(DestinationResolver<String> queueDestinationResolver) {
    SimpleMessageListenerContainerFactory factory = new SimpleMessageListenerContainerFactory();
    factory.setDestinationResolver(queueDestinationResolver);
    return factory;
}
    
@Bean
public DestinationResolver<String> queueDestinationResolver(AmazonSQSAsync sqs) {
    return new CachingDestinationResolverProxy<>(new FailingDestinationResolver<>(new DynamicQueueUrlDestinationResolver(sqs, null)));
}
```
**Note** that spring `cloud.aws.sqs.listener.*` properties ignored for this configuration, additional code is required to pick them up from `SqsProperties`.

**Comment by maciejwalkowiak** [comment]
Fixed in https://github.com/awspring/spring-cloud-aws/pull/394
