### ISSUE TITLE
Spring Boot 2.7 Support

### ISSUE THREAD

**Issue by penguinlab** [awspring/spring-cloud-aws#406]
**Type**: Feature

Are there any plans to support Spring Boot 2.7 ?

**Comment by penguinlab** [comment]
Thanks for the reply. No problem.
I just now saw that there is a note added to README.md about compatibility with Spring Boot 2.7.
I had missed it. Sorry.

**Comment by penguinlab** [comment]
Thanks for the reply. No problem.
I just now saw that there is a note added to README.md about compatibility with Spring Boot 2.7.
I had missed it. Sorry.

**Comment by maciejwalkowiak** [comment]
@penguinlab no worries! If you find any issues please let us know.
