### ISSUE TITLE
Spring Cloud AWS 2.4.1 / SpringBoot 2.6.6 - ParameterStore - File extension is not known to any PropertySourceLoader

### ISSUE THREAD

**Issue by hajdukd** [awspring/spring-cloud-aws#411]
**Type**: Bug

**Component**:
Spring Cloud AWS 2.4.1
SpringBoot 2.6.6 

**Describe the bug**
When specifying `spring.config.import: 'aws-parameterstore:'` application does not even start. Debugging shows that LocationResolver for aws-parameterstore doesn't even exist in the context.

When specifying `spring.config.import: 'aws-parameterstore:/existing/key/prefix/'` application does not start saying that key was not found. Debugging shows AWSParameterstore related classes are not invoked at all. No call to AWS is performed during app start (wireshark).

**Sample**
```build.gradle
plugins {
    id 'java'
    id 'org.springframework.boot' version '2.6.6'
}
dependencies {
    implementation 'io.awspring.cloud:spring-cloud-starter-aws'
    implementation 'io.awspring.cloud:spring-cloud-aws-parameter-store-config'
}
dependencyManagement {
    imports {
        mavenBom "io.awspring.cloud:spring-cloud-aws-dependencies:2.4.1"
    }
}
```

**Comment by maciejwalkowiak** [comment]
No worries @hajdukd :-)

**Comment by hajdukd** [comment]
Thanks [Ducky x]](https://i.imgur.com/8jk4Whg.jpg)
