### ISSUE TITLE
Migrate `PathMatchingSimpleStorageResourcePatternResolver` to AWS SDK v2

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#432]
`PathMatchingSimpleStorageResourcePatternResolver` should be migrated to AWS SDK v2 in 3.0 version (`main` branch).

**Comment by klopfdreh** [comment]
Please can you add this into the migration that this is not supported currently?

We just implemented the functionality and if it works we are going to provide it for the next milestone.
