### ISSUE TITLE
Convert Message Payload in SqsMessagePoller

### ISSUE THREAD

**Issue by tomazfernandes** [awspring/spring-cloud-aws#441]
This should be a tricky one. The [SqsMessagePoller](https://github.com/tomazfernandes/spring-cloud-aws/blob/GH-344/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/listener/poller/SqsMessagePoller.java) uses the `SqsAsyncClient`, which returns the message bodies as `String`. But ideally we'd want to convert this to `T` so that user's `Interceptors`, `ErrorHandlers`, etc, could access the converted payload instead of the `String` body.

The tricky part is figuring out to which type we should convert the payload to - the `MessageListenerContainerFactory` we should be using for auto configuration for example should probably be typed as `<Object>`.

### How we do currently

Currently we do that conversion at method invocation - the `InvocableHandlerMethod` has a number of `MethodArgumentResolvers`, for resolving arguments such as `Header`, `Acknowledgement`, etc. If none of these are able to resolve the method argument, it is assumed that that's the payload type, and a `PayloadMethodArgumentResolver` kicks in with a `MappingJackson2MessageConverter`.

We instantiate these in [SqsListenerAnnotationBeanPostProcessor.java](https://github.com/tomazfernandes/spring-cloud-aws/blob/c685e5fddb260a8c19fed2165f694816dd233409/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/annotation/SqsListenerAnnotationBeanPostProcessor.java#L187-L215)

### How Spring Kafka solves this

`Kafka` only has serializers for simple values such as Integer, String, UUID, etc. I think since `Kafka` is mostly used with `Avro` and `schema registry`, the mapping information is already provided.

`Spring Kafka` offers a `JsonSerializer/Deserializer`. When the message is produced by the framework, a `__TypeId__` header is added with the POJO's class name; such header is then used for deserialization in the other end.

If no such header is provided, it allows some user configurable strategies to define the type mapping, be it a `default type` or dynamically based on e.g. `headers`.

If the mapping strategy is also not defined, it throws an exception: `No type information in headers and no default type provided`

There's code in [MessagingMessageListenerAdapter.java](https://github.com/spring-projects/spring-kafka/blob/596f7d940caa2f562775d3f232be4ce7b58bffe9/spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java#L571-L652) where the type is inferred by exclusion - the listener method only supports limited argument types such as `Consumer`, `Acknowledgement`, `ConsumerRecord`, `@Header` arguments, etc, so the method argument that is not one of these is inferred to be the payload type.

### What we might do

I haven't looked deeply into this yet, but the ways I see would be:

- We could mimic this logic where we add type information to the headers when we send the message. However I wonder if in a cloud-first environment such as `AWS` this will really solve the problem - e.g. I've seen and used lots of patterns where a `lambda function` sends a message to `SQS`, often using other languages such as `python`, so typing information wouldn't be there. We could mitigate this by also implementing user-side configuration capabilities.

- Try to handle this automagically by using the same `MethodArgumentResolvers` for the method's parameters to figure out which `MethodParameter` from the listener method is the payload type. We could either use this to convert SQS's `Message` to Messaging `Message` directly, or use this logic in the `AbstractEndpoint` to extract such `type`, and then pass it along to the `Poller` via the `Container` or `ContainerOptions` and convert the payload directly there . This seems doable - I wonder if there are any obvious drawbacks I might be missing.

**Comment by tomazfernandes** [comment]
I've dug a little deeper into how `Spring Kafka` handles this and updated the description.

**Comment by tomazfernandes** [comment]
Regarding this message conversion issue, I think I may have found a well balanced approach.

It's important to note that this will only be required for users that want to get a properly deserialized `POJO` in `ErrorHandler`, `Interceptor` and `AckHandler` components - if an unknown type is found, users will receive a `Message<String>` in these components and can deserialize themselves if they need to. For the `@SqsListener` methods payloads are deserialized correctly already.

So I think for this first version we can mimic the simplest `Spring Kafka` approaches, which would be:

- Adding a `__typeid__` header to messages sent with this framework - that would make `Spring`-based ecosystems just work OOTB.

- Adding a user-provided mapping function that takes both the `Message`'s `payload` and `headers` and provide the proper class to deserialize the payload to. It's a good practice to add metadata such as `EventType` to the headers, so this should be enough for most `non-spring` use cases.

This has been working well for `Spring Kafka` and I don't see users complaining about this approach.

In the future we can look into trying to figure out the proper type automatically, but as far as I've seen that's less trivial than I'd expect, though I'll still do some digging when I pick up this issue.

Please let me know if you have any different ideas or concerns.

Thanks!

**Comment by maciejwalkowiak** [comment]
@tomazfernandes sounds good to me!

**Comment by tomazfernandes** [comment]
Closed by https://github.com/awspring/spring-cloud-aws/pull/374/commits/cae4311cc6c589be9ed5b24b6320dc8ef0021ee1
