### ISSUE TITLE
Improve documentation to have Java configuration instead of XML only

### ISSUE THREAD

**Issue by tiarebalbi** [awspring/spring-cloud-aws#446]
**Type**: Feature (Documentation)

**Is your feature request related to a problem? Please describe.**
Today, most of the documentation describe how to configure the beans using XML, the request here is to introduce a similar integration as the spring boot doc provides, and support different type of configurations in the doc. 

**Example:**
- https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#jdbc-embedded-database-java

**Describe the solution you'd like**
Keep the XML documentation but support Java configuration and potentially Kotlin.

**Comment by tiarebalbi** [comment]
Thanks @maciejwalkowiak , yes that was going to be my suggestion I'm working on a project where I'm writing the Java config for most of the topics covered in the documentation.

Happy to create a PR with these changes.

**Comment by maciejwalkowiak** [comment]
@tiarebalbi do you think it will happen or should i close it?

**Comment by maciejwalkowiak** [comment]
Closing due to lost interest ;-)
