### ISSUE TITLE
S3 : Ability to get user-defined metadata via S3Resource

### ISSUE THREAD

**Issue by sis-yoshiday** [awspring/spring-cloud-aws#449]
**Type**: Feature

**Describe the solution you'd like**
Add accessor to `io.awspring.cloud.s3.S3Resource`

- add user-defined-metadata field to `io.awspring.cloud.s3.S3Resource.HeadMetadata`
- add `Map<String, String> metadata()` to `S3Resource`

**Comment by maciejwalkowiak** [comment]
@sis-yoshiday shouldn't `metadata()` return `ObjectMetadata`?

**Comment by sis-yoshiday** [comment]
@maciejwalkowiak 
> https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html

if my understanding is correct, metadata can be loaded by `HeadObject` request.

I submitted PR
https://github.com/awspring/spring-cloud-aws/pull/451
