### ISSUE TITLE
Upgrade to LocalStack 1.0

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#463]
Following the 1.0 release https://localstack.cloud/blog/2022-07-13-announcing-localstack-v1-general-availability/, integration tests should be updated to use Localstack 1.0

**Comment by eddumelendez** [comment]
the image size is quite big. is there any issue solving by upgrading. Not saying no, always in favor to the latest but just saying 🙂

**Comment by maciejwalkowiak** [comment]
No, just for the sake of being up to date. We will have to upgrade eventually anyway.
