### ISSUE TITLE
Add SQS sample

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#508]

**Comment by tomazfernandes** [comment]
@maciejwalkowiak, I remember you mentioned you had something for this, is there anything I can help with?

**Comment by maciejwalkowiak** [comment]
I'll submit a PR in upcoming days.

**Comment by maciejwalkowiak** [comment]
I am taking it back. If you have time please take over the sample 😅

**Comment by rajadilipkolli** [comment]
@maciejwalkowiak , does this [sample ](https://github.com/rajadilipkolli/aws-stack/tree/main/aws-sqs-project)fits?

**Comment by maciejwalkowiak** [comment]
@rajadilipkolli it looks like a potential candidate for sample covering more integrations, but in this specific issue we mean a sample tailored for SQS similar to other samples in https://github.com/awspring/spring-cloud-aws/tree/main/spring-cloud-aws-samples. Also it's meant for the new SQS implementation in 3.0 version.
