### ISSUE TITLE
When sqs consumption fails, I want to modify the Visibility, is there a way to modify the Visibility of a single item?

### ISSUE THREAD

**Issue by fengzijk** [awspring/spring-cloud-aws#519]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
Exponential backoff in SQS    for eg:https://ivan-site.com/2018/06/exponential-backoff-in-sqs/

Will this feature be added in the future or is there an example already?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maciejwalkowiak** [comment]
If you mean changing visibility of the received message, it's available in both 2.x and 3.x versions through a `Visibility` method argument that can be added to `@SqSListener` annotated method.

- https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#listener-method-arguments

**Comment by fengzijk** [comment]
This is  I want. Thank you for helping me
