### ISSUE TITLE
Support Spring Boot v3 (3.0.0-M3)

### ISSUE THREAD

**Issue by rauldeheer** [awspring/spring-cloud-aws#523]
**Type**: Feature/Bug

**Is your feature request related to a problem? Please describe.**
When running Spring Boot 3.0.0-M3, we are unable to get the `@SqsListener` annotation to work. Sending a message to a queue works.

**Describe the solution you'd like**
Support for Spring Boot v3

**Additional context**
The application crashes at startup when spring-cloud-aws packages are present, or the `@SqsListener` annotation will not resolve messages from the queue.

**Comment by maciejwalkowiak** [comment]
Yep we are aware and the issue is being discussed behind the scenes. Upgrade to Spring Boot 3.0 is happening here https://github.com/awspring/spring-cloud-aws/tree/spring-boot-3.0

**Comment by rauldeheer** [comment]
Can we help to speed up the process? Please let me know. @maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
At this stage - no. Upgrading to 3.0 on our side is quite straightforward. The problematic at least at this stage is native support and especially ensuring native support works as expected in tests.

**Comment by maciejwalkowiak** [comment]
Done in M3.

**Comment by nitesh0420** [comment]
@maciejwalkowiak Any idea by when you are planning to release the first stable version to support spring boot V3?

**Comment by maciejwalkowiak** [comment]
The plan is: 3rd week of January RC1, then we give 2-4 weeks to get feedback and depending on how it goes release GA.
