### ISSUE TITLE
The documentation of "12. Migration from 2.x to 3.x" seems to be broken

### ISSUE THREAD

**Issue by klopfdreh** [awspring/spring-cloud-aws#531]
**Type**: Bug

**Component**:
Documentation

**Describe the bug**
![image](https://user-images.githubusercontent.com/980773/195040370-cac29741-cdb2-4a4f-8814-d86ff50dbade.png)

I guess the screenshot describes it the best. 😄 I guess the mark down table is broken.

See: https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-M2/reference/html/index.html#migration-from-2-x-to-3-x

**Sample**
No sample required

**Comment by maciejwalkowiak** [comment]
Thanks for reporting, this has been already fixed: https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#migration-from-2-x-to-3-x

**Comment by klopfdreh** [comment]
Yep thanks! 👍
