### ISSUE TITLE
Add aws-secretsmanager-r2dbc

### ISSUE THREAD

**Issue by IRuzhnikov** [awspring/spring-cloud-aws#533]
### Discussed in https://github.com/awspring/spring-cloud-aws/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **eddumelendez** January  6, 2021</sup>
Similar to [aws-secretsmanager-jdbc](https://github.com/aws/aws-secretsmanager-jdbc), a new project can be created to support secretsmanager for [r2dbc](https://r2dbc.io/).</div>

Hi, i have idea for using r2dbc with AwsSecretsManager and shared it in attached discussion
NOTICE: example big just because i didn't access to internal spring-cloud-r2dbc code from my self program.

if you agree with this idea i can will try implement it self

**Comment by maciejwalkowiak** [comment]
At this stage there are no plans to add r2dbc support.

**Comment by maciejwalkowiak** [comment]
@IRuzhnikov I suggest creating this a separate OSS project. Ideally, AWS themselves could provide R2DBC compatible variant of Secrets Manager integration.
