### ISSUE TITLE
Build against Java 17, 18, 19

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#540]
Since we've upgraded `main` to Spring Boot 3 and Java 17, we also need to include Java 18 and Java 19 in Github actions builds.

**Comment by mcruzdev** [comment]
Hi @maciejwalkowiak,

Can I get this issue?

**Comment by maciejwalkowiak** [comment]
@mcruzdev go for it!

**Comment by mcruzdev** [comment]
Hi @maciejwalkowiak,

![image](https://user-images.githubusercontent.com/56329339/197832823-9ec3db8d-3196-400f-aab1-c6cff088592e.png)

There are just version 17 and 19 on `sdkman` version 5.16.0

**Comment by maciejwalkowiak** [comment]
@mcruzdev makes sense! Let's skip 18. I think this PR would be ready for review then, right?

**Comment by mcruzdev** [comment]
I opened the PR #550, thank you :)

**Comment by maciejwalkowiak** [comment]
Closed in #550 

Thanks @mcruzdev!
