### ISSUE TITLE
Migrate S3 resource loader to AWS SDK v2

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#55]
S3 components should be extracted from the core/context module and moved to separate `spring-cloud-aws-s3` module. Code should be based on AWS SDK v2. 

Things to consider - simplify handling loading files from the different region. Research if client caching has not been done yet in the SDK itself.

XML configuration and `@EnableResourceLoader` should be dropped.

**Comment by arunkpatra** [comment]
@maciejwalkowiak , Can I take this up?

**Comment by arunkpatra** [comment]
@maciejwalkowiak Looks like AWS SDK V2 does not yet support client caching for different regions on the AWS SDK side. Some discussions around it exist, but it [doesn't appear to be a top priority](https://github.com/aws/aws-sdk-java-v2/issues/52) for the AWS SDK team.

**Comment by maciejwalkowiak** [comment]
@eddumelendez is working on S3 integration, perhaps he can share his findings

**Comment by eddumelendez** [comment]
The following issues have been created as part of the progress on this topic. See https://github.com/aws/aws-sdk-java-v2/issues/2371 https://github.com/aws/aws-sdk-java-v2/issues/2372

**Comment by maciejwalkowiak** [comment]
Fixed in #275
