### ISSUE TITLE
NPE When `clientProperties` is Null

### ISSUE THREAD

**Issue by akefirad** [awspring/spring-cloud-aws#554]
**Type**: Bug

**Component**:
Core AutoConfigure

**Describe the bug**
In method `AwsClientBuilderConfigurer#configure` (both versions) `clientProperties` is considered nullable, but in the method body there's a not-null assertion.

**Sample**
See the code: https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-autoconfigure/src/main/java/io/awspring/cloud/autoconfigure/core/AwsClientBuilderConfigurer.java#L57

**Comment by maciejwalkowiak** [comment]
Thanks for reporting. Would you like to submit a PR? This assertion should not be there as far as I can see.

**Comment by akefirad** [comment]
https://github.com/awspring/spring-cloud-aws/pull/555
