### ISSUE TITLE
AmazonSQSBufferedAsyncClient adds unexpected 200ms delay to published messages

### ISSUE THREAD

**Issue by kerkhofsd** [awspring/spring-cloud-aws#556]
**Type**: Bug / unexpected behaviour

**Component**:
SQS

**Describe the bug**
Spring Cloud AWS version: 2.4.2

If no AmazonSQS client is provided, the  `SqsAutoConfiguration` will initialize an `AmazonSQSBufferedAsyncClient`. 
From the [JavaDoc of that class](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/buffered/AmazonSQSBufferedAsyncClient.html):

> ...
> After receiving a call, rather than executing it right away, this client waits for a configurable period of time ( default=200ms) for other calls of the same type to come in; if such calls do come in, they are also not executed immediately, but instead are added to the batch.
> ...

If, in practice, multiple events are published from the same thread this actually means a delay of 200ms will be added to each event. Depending of the amount of events to be published, this can add a considerable / painful delay.

Our current workaround, is to provide an `AmazonSQSAsyncClient` (and thereby prevent usage of the default `AmazonSQSBufferedAsyncClient`). See workaround below. 

I'm aware that 2.4.x is not under active development anymore and you are working heavily on 3.x (much appreciated). 
The goal of this report is to get more insight in this behaviour:

* Is this behaviour is expected (and why?)
* Maybe we're using it wrong / are we missing something obvious? 
* Verify 3.x behaves different. I see there the [SqsAsyncClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sqs/SqsAsyncClient.html) is used. Hence I think this behaviour does not apply to 3.x? 

**Workaround**
Provide your own AmazonSQS client, which is not a `AmazonSQSBufferedAsyncClient`. 

```java
    @Bean
    public AmazonSQSAsync amazonSQS() {
        return AmazonSQSAsyncClientBuilder.defaultClient();
    }
```

**Sample**
Can basically be reproduced by publishing events in a for loop. 
If desired and helpful, please show me where I can best add a test and I'll add a test.

**Comment by maciejwalkowiak** [comment]
In 2.x we are using [AmazonSQSBufferedAsyncClient](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/buffered/AmazonSQSBufferedAsyncClient.html) - I would guess this is where the delay comes from. The benefit is that it makes less requests than regular SQS client.

Since buffered client [has not been ported](https://github.com/aws/aws-sdk-java-v2/issues/165) to AWS SDK v2, in 3.0 we are using regular client so the delay should not be there.
