### ISSUE TITLE
No beans of 'SqsAsyncClient' type found

### ISSUE THREAD

**Issue by rauldeheer** [awspring/spring-cloud-aws#557]
**Type**: Bug
**Component**: SQS

**Describe the bug**
When using the latest version for Spring Boot 3 (M3), we are unable to use the SqsAsyncClient as described in [the docs](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-M3/reference/html/index.html#sending-messages). It gives us the following error:

```
required a bean of type 'software.amazon.awssdk.services.sqs.SqsAsyncClient' that could not be found.
```

**Comment by magna25** [comment]
you need to declare the bean.

```
@Bean 
SqsAsyncClient asyncClient(){
 return new SqsAsyncClient.builder().build();
}
```

**Comment by rauldeheer** [comment]
Yes the new M3 compatible version works. @tomazfernandes

**Comment by maciejwalkowiak** [comment]
Awesome. Thanks @tomazfernandes and @rauldeheer for great communication. Closing.
