### ISSUE TITLE
No Info about local build setup

### ISSUE THREAD

**Issue by h1alexbel** [awspring/spring-cloud-aws#559]
Your README doesn't have information about setup a local environment for building application, because it has some weird errors with ```spring-cloud``` parent. E.g: ```Could not find artifact org.springframework.cloud:spring-cloud-dependencies-parent:pom:4.0.0-M5```

I think, would be great to see information in your repo on how to build an app using maven to start working with the repository. So, please fix your README.

**Comment by maciejwalkowiak** [comment]
Instructions are there https://github.com/awspring/spring-cloud-aws#checking-out-and-building

How do you trigger the build and which Maven & Java versions do you use?

You can always look up [how CI builds the project](https://github.com/awspring/spring-cloud-aws/blob/main/.github/workflows/build.yml) - if it works in CI then it should work for you too.

**Comment by h1alexbel** [comment]
Hello @maciejwalkowiak , I'm triggering the build using just ```./mvnw install``` and ```Java 17``` with Maven Wrapper.
But when I reload maven project it notifies me: ```Could not find artifact org.springframework.cloud:spring-cloud-dependencies-parent:pom:4.0.0-M5```

**Comment by h1alexbel** [comment]
@maciejwalkowiak 

```
The following profiles are active:

 - spring (source: io.awspring.cloud:spring-cloud-aws:3.0.0-M3)
 - spring (source: org.springframework.cloud:spring-cloud-build:4.0.0-M4)
 - java8 (source: org.springframework.cloud:spring-cloud-build:4.0.0-M4)
 - java11 (source: org.springframework.cloud:spring-cloud-build:4.0.0-M4)
```

**Comment by MatejNedic** [comment]
Hey  @h1alexbel , what IDE are you using?

**Comment by maciejwalkowiak** [comment]
Ok than it makes it very weird. Since Spring profile is there you should be able to access milestone releases. Another attempt:

Force Maven to update indices:

```
./mvnw install -U
```

**Comment by h1alexbel** [comment]
> Hey @h1alexbel , what IDE are you using?

IntelliJ IDEA

**Comment by maciejwalkowiak** [comment]
After upgrading the dependencies problem should be gone. I tested it by running the build with completely clean local maven repository and nothing in `settings.xml`
