### ISSUE TITLE
SQS should resolve ARN queue names

### ISSUE THREAD

**Issue by chrylis** [awspring/spring-cloud-aws#561]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
The `DynamicQueueUrlDestinationResolver` can handle explicit SQS URLs, and it will perform a `GetQueueUrl` to fetch the URL when provided a simple queue name. When provided an ARN, however, it passes the ARN to Amazon as the queue name, which results in a queue-not-found error.

**Describe the solution you'd like**
The resolver already checks to see whether the `String name` is a valid HTTP or HTTPS URL and uses that if provided. I would like it to also support queue `arn:` URIs. If it is advantageous to fetch the queue URL for some reason (to fast-fail?), then that request can be built parsing the ARN. If it is not so adventageous, the ARN can be converted into the queue URL via string operations.

**Describe alternatives you've considered**
The main alternative, when referring to queues potentially not owned by the running AWS account, would be to provide the URL. This is different from how most AWS resources are usually identified in configuration.

**Additional context**
This is specifically a concern with the existing 2.x series (including 2.4.2). If this functionality is worthwhile and the 2.4 branch is being maintained, I can try to put together a PR to implement it.

**Comment by tomazfernandes** [comment]
Hi @chrylis, thanks for bringing this up.

If I understand correctly, using current logic you can't find a queue from a different owner using the queue name, so you need to provide the full `URL`. And your suggestion is to be able to parse an `ARN` to the `URL` so it can be used instead.

Is that understanding correct?

That sounds interesting - wouldn't you like to submit a PR to the `3.0` version instead?

Anyway, let's see what @maciejwalkowiak thinks of this.

Thanks.

**Comment by chrylis** [comment]
Yes, that's my suggestion. I'd be interested in contributing to 3.0, but we're using Spring Integration, and AWSpring is for us merely a bridge between SNS/SQS and Spring Integration. Spring Integration AWS 3 work won't begin until AWSpring 3 is GA, and it will be some time later before it's ready. I'd like to use ARNs today.

**Comment by techadri** [comment]
I would like to submit a PR for the 2.x branch, as I also recently stumbled upon this missing functionality when using AWSpring. Can I move on or is someone (@chrylis?) already working on this?
