### ISSUE TITLE
Auto-configure an AmazonSNSAsync bean

### ISSUE THREAD

**Issue by chrylis** [awspring/spring-cloud-aws#564]
**Type**: Feature

As of 2.4.2, `spring-cloud-aws-autoconfigure` registers an `AmazonSQSAsync` bean but only a non-async `AmazonSNS` bean. The Spring Integration AWS SNS adapter requires an async client, and the async client is a subclass of the synchronous client. The configuration for the sync and async clients in the SDK appears to be identical. I request that `SnsAutoConfiguration` publish an `AmazonSNSAsyncClient` instead of `AmazonSNSClient`.

This relates to https://github.com/spring-projects/spring-integration-aws/issues/212.

**Comment by MatejNedic** [comment]
Hey @chrylis 2.4.x is not in development anymore, only security and bug fixes. We are working on releasing 3.0 and currently there is 3.0.0-M3 released, you can check it out (sns has been ported there). Just to note 3.0.0.M3 is based on aws sdkv2.

**Comment by chrylis** [comment]
I appreciate that 3.0 is well underway, but it's not going to be an acceptable migration for us or for many of your other users for some time. Spring Integration AWS 3 development will not start until after AWSpring 3.0 is GA.

**Comment by maciejwalkowiak** [comment]
Fixed in https://github.com/awspring/spring-cloud-aws/pull/574
