### ISSUE TITLE
Allow providing custom ChannelInterceptor implementations during SNS autoconfiguration

### ISSUE THREAD

**Issue by sondemar** [awspring/spring-cloud-aws#565]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
The  SnsTemplate  instantiates [TopicMessageChannel](https://github.com/awspring/spring-cloud-aws/blob/89c48d80d3bfef80d0e046f06419cdaa3b718d31/spring-cloud-aws-sns/src/main/java/io/awspring/cloud/sns/core/SnsTemplate.java#L140) before  sending the message when the topic ARN is provided. However, there is no way to apply ChannelInterceptor implementations which can help us to modify the messages before sending out and/or receiving from a Message the channel (for example apply some extra message headers). 

**Describe the solution you'd like**
It could be a similar solution to the [SqsAutoConfiguration](https://github.com/awspring/spring-cloud-aws/blob/v3.0.0-M3/spring-cloud-aws-autoconfigure/src/main/java/io/awspring/cloud/autoconfigure/sqs/SqsAutoConfiguration.java) where we can provide MessageInterceptor implementations (in our case it will be  ChannelInterceptor implementations with [SnsAutoConfiguration](https://github.com/awspring/spring-cloud-aws/blob/v3.0.0-M3/spring-cloud-aws-autoconfigure/src/main/java/io/awspring/cloud/autoconfigure/sns/SnsAutoConfiguration.java)). 

**Describe alternatives you've considered**
As mentioned above, this kinda interceptor could be used. With AWS SDK v2.x I do not see any alternative for now.

**Additional context**
With aws sdk version 1.x probably it was possible to configure [SnsMessageHandler](https://github.com/spring-projects/spring-integration-aws/issues/212) with AmazonSnsClient. 
Please let me know if you need a contribution to the implementation.

**Comment by maciejwalkowiak** [comment]
@sondemar apologies for late reply. You're welcome to contribute a PR.
