### ISSUE TITLE
Cannot get SQS MessageId

### ISSUE THREAD

**Issue by cheaan2000** [awspring/spring-cloud-aws#570]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
My goal is to get the SQS MessageId from the headers, but obviously 
`message.getHeaders().get(ID)` returns null.

I see that "MessageId" is present in the SqsMessageHeaders, so the obvious thing would be to do 
`message.getHeaders().get(MESSAGE_ID_MESSAGE_ATTRIBUTE_NAME )` but MESSAGE_ID_MESSAGE_ATTRIBUTE_NAME is private.

My only option is to do this 
`message.getHeaders().get("MessageId")`

Do you think this is a bug ?

**Comment by tomazfernandes** [comment]
Hi @cheaan2000,

I'd hardly call this a bug since the functionality itself works as expected. I'm not sure we're releasing a new 2.x with this kind of enhancement, but feel free to try out the `3.0.0-M3` version. The `GA` should come soon.

Thanks.
