### ISSUE TITLE
Secrets and Parameters clobber each other when the resource names are the same.

### ISSUE THREAD

**Issue by thorntonrp** [awspring/spring-cloud-aws#573]
**Type**: Bug

**Component**:  "Parameter Store",  "Secrets Manager"

**Describe the bug**

In the code below, I'm importing both secrets from Secrets Manager and parameters from Parameter Store. The name of my secret is "/myapp" and the base name of my parameters are also named "/myapp". When these names are the same, my application breaks because the secret property source ends up being given the same name as the parameter store property resource. Both end of getting called "/myapp" and only one of the property resources will get added to the Spring environment.

```yaml
spring:
  config:
    import:
      - "aws-secretsmanager:/myapp"
      - "aws-parameterstore:/myapp"
```

It is not an error for a parameter base name to have the same name as a secret. My recommendation is that both the secret property resource and the parameter property resource be given the full names of their respective imports to ensure the resource names are unique in the Spring environment. For example, the secret property resource should be named `"aws-secretsmanager:/myapp"` and the parameter store property resource should be named `"aws-parameterstore:/myapp"`. This fix shouldn't affect backward compatibility since the resource names are just an implementation detail.

The benefit of this fix would be twofold. First, the one won't end of clobbering the other in the Spring environment. Second, when viewing the properties on the actuator `/env` endpoint, it will be immediately clear where the properties came from. Currently, it is not clear that the properties came from either secrets manager or parameter store.

**Comment by maciejwalkowiak** [comment]
Just to make sure - this is happening in 3.0, right? Would you like to contribute a fix?

**Comment by thorntonrp** [comment]
Yes, I've verified that this is happening on both 3.0 and 2.x. I'll submit a PR to fix.
