### ISSUE TITLE
Start and stop the sqs listener based on user inputs

### ISSUE THREAD

**Issue by bharatTR** [awspring/spring-cloud-aws#576]
Question

I am working on spring boot application, it uses docker and k8s for deployment. I need to expose endpoints that would start and stop sqs listener based on user inputs, but I am not sure how to perform this job. Is there a way to disable/enable sqs listener based on user inputs?

**Comment by tomazfernandes** [comment]
Hi @bharatTR,

For `@SqsListener` containers you can inject the `MessageListenerContainerRegistry` and call `#start` and `#stop` on it to manage all containers, or on any of the containers themselves.

Please let us know it that works for you or if you have any questions.

Thanks.
