### ISSUE TITLE
Request to introduce SecretBinary available with AWS secretsmanager  

### ISSUE THREAD

**Issue by kishan-Dhrangadhariya** [awspring/spring-cloud-aws#578]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
I have stored binary value on AWS secretsmanager which I need to fetch on Application startup 

**Describe the solution you'd like**
We can introduce optional parameter with every secret to identify whether it is binary or string and load them accordingly

**Describe alternatives you've considered**
Other way to go about this would be store secret in base64 encoded form, which would allow us to store binary data in string format, but this comes with its own tech debt

**Comment by maciejwalkowiak** [comment]
Would you like to contribute a PR?

**Comment by kishan-Dhrangadhariya** [comment]
Yes, I would like to contribute, if we could have a discussion on how best to implement this, it would be helpful.

**Comment by maciejwalkowiak** [comment]
Figuring out how to implement it is probably 80% of work. I currently don't have time for that, but if you research this topic please come back with your ideas I am happy to review them

**Comment by maciejwalkowiak** [comment]
Done in #613
