### ISSUE TITLE
Migrate SES integration to AWS SDK 2

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#59]
Migrate SES integration from AWS SDK v1 to AWS SDK v2 in 3.0.x branch.

SES should be moved completely from the core/context module and all SES related classes should be in `spring-cloud-aws-v3-ses` module.

Consider the following guidelines:

* Create package `io.awspring.cloud.autoconfigure.ses` at `spring-cloud-autoconfigure` which contains `SesProperties`, `SesAutoConfiguration`
* Create module `spring-cloud-aws-ses`
* Create module `spring-cloud-starter-aws-ses` which contains a `pom.xml` with `spring-cloud-autoconfigure` and `spring-cloud-aws-ses` dependencies
* Prefix should be `spring.cloud.aws.ses`

**Comment by driverpt** [comment]
Shouldn't we migrate the `spring-cloud-aws-core` first ?

**Comment by maciejwalkowiak** [comment]
@driverpt core will not be directly migrated as quite a few classes will be either removed or moved to separate modules. Integrations definitely need `autoconfigure` module to be there so that they can use credentials and region providers.

It will become clearer once we have `autoconfigure` and at least single integration migrated.

**Comment by arunkpatra** [comment]
@MatejNedic @maciejwalkowiak Can I give this a shot?

**Comment by eddumelendez** [comment]
Description updated with guidelines to build the module

**Comment by arunkpatra** [comment]
> Description updated with guidelines to build the module

All guidelines have been factored in #84.

**Comment by eddumelendez** [comment]
Closing in favor of #84
