### ISSUE TITLE
Possible to auto reload secret properties on value change with 2.4.x?

### ISSUE THREAD

**Issue by mikelhamer** [awspring/spring-cloud-aws#591]
I see in the 3.0.0-M docs about how to reload the property sources used with secrets manager when the value of a secret changes, but is this possible to do on version 2.4.x? Not seeing it in the docs.

**Comment by maciejwalkowiak** [comment]
No, there's no support for auto-reload in 2.4 and we have no plans to add it. If you want to implement it yourself check this commit for an inspiration https://github.com/awspring/spring-cloud-aws/commit/6a7eb277a4505215b9266e554b0779f9ba8178e3
