### ISSUE TITLE
Auto Configure S3Presigner

### ISSUE THREAD

**Issue by huww98** [awspring/spring-cloud-aws#603]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
I would expect an auto-configured `S3Presigner`, just like `S3Client`, but I got:

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '...' defined in file [...].class]: Unsatisfied dependency expressed through constructor parameter 1: No qualifying bean of type 'software.amazon.awssdk.services.s3.presigner.S3Presigner' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Describe the solution you'd like**
An auto-configured S3Presigner bean. To implement this, I think we need
- an `S3Configuration` bean, which can be used to configure both `S3Presigner` and `S3Client`.
- an interface to customize `S3Presigner` programmatically
- another set of properties for `S3Presigner`, in case it should use different configs from `S3Client`, e.g.: `spring.cloud.aws.s3.presigner.endpoint`

**Describe alternatives you've considered**
Configure an `S3Presigner` in my own configuration class. Currently I use:
```java
// copied from S3AutoConfiguration.java
private S3Configuration s3ServiceConfiguration() {
	S3Configuration.Builder config = S3Configuration.builder();
	PropertyMapper propertyMapper = PropertyMapper.get();
	propertyMapper.from(properties::getAccelerateModeEnabled).whenNonNull().to(config::accelerateModeEnabled);
	propertyMapper.from(properties::getChecksumValidationEnabled).whenNonNull()
			.to(config::checksumValidationEnabled);
	propertyMapper.from(properties::getChunkedEncodingEnabled).whenNonNull().to(config::chunkedEncodingEnabled);
	propertyMapper.from(properties::getPathStyleAccessEnabled).whenNonNull().to(config::pathStyleAccessEnabled);
	propertyMapper.from(properties::getUseArnRegionEnabled).whenNonNull().to(config::useArnRegionEnabled);
	return config.build();
}

@Bean
public S3Presigner s3Presigner(AwsCredentialsProvider awsCredentialsProvider, AwsRegionProvider awsRegionProvider) {
	return S3Presigner.builder()
			.serviceConfiguration(s3ServiceConfiguration().copy(
				b -> b.checksumValidationEnabled(false)
			))
			.endpointOverride(my_s3Properties.getPublicEndpoint())
			.credentialsProvider(awsCredentialsProvider)
			.region(awsRegionProvider.getRegion())
			.build();
}
```

**Additional context**

**Comment by maciejwalkowiak** [comment]
Fixed in #620
