### ISSUE TITLE
spring-cloud-starter-aws-messaging v3 for Spring Boot 3

### ISSUE THREAD

**Issue by zelenkooo** [awspring/spring-cloud-aws#617]
I don't see version of spring-cloud-starter-aws-messaging v3 , all other applications are released with [v3.0.0-M3] but not spring-cloud-starter-aws-messaging . Will it be released ? Or is the functionality moved ? At the moment it looks not compatible with Spring Boot 3

**Comment by maciejwalkowiak** [comment]
The functionality has moved to to `spring-cloud-aws-starter-sns` and `spring-cloud-aws-starter-sqs`. Spring Cloud AWS 3.0 (currently M3) is compatible with Spring Boot 3.0.

Does this answer your question?
