### ISSUE TITLE
cloud.aws.mail.region is not working as expected

### ISSUE THREAD

**Issue by quahkj** [awspring/spring-cloud-aws#625]
**Type**: Bug

**Component**: SES

**Describe the bug**
I am using JDK17, Spring boot (version 2.5.12) and spring cloud aws 2.4.2 for my project. In the spring boot properties file, below are the dependencies in the pom.xml:

       <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-starter-aws-ses</artifactId>
            <version>2.4.2</version>
        </dependency>

   <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>2.4.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

I configure below AWS details in the properties file:
cloud.aws.credentials.access-key=xxxxxxxxxxxxxxxx
cloud.aws.credentials.secret-key=xxxxxxxxxxxxxxxx
cloud.aws.mail.region=ap-southeast-2
spring.cloud.aws.ses.region=ap-southeast-2

This spring boot project is deployed in AWS ECS in ap-southeast-1 region. I have enabled SES production access in the AWS in ap-southeast-2 region - that is the reason why I am pointing the mail region property (above) to ap-southeast-2. The problem/bug is whenever my application tries to send email using JavaMailSender, the spring always looks for SES in ap-southeast-1 region instead of ap-southeast-2 region. I have tried different property combinations and it just doesn't work. Look like either cloud.aws.mail.region or spring.cloud.aws.ses.region didn't override the default region as expected.   

The exception throw is  com.amazonaws.services.simpleemail.model.MessageRejectedException: Email address is not verified. The following identities failed the check in region AP-SOUTHEAST-1: xxxxx@xxxxxx.com (Service: AmazonSimpleEmailService; Status Code: 400; Error Code. From the error message, spring aws was going to ap-southeast-1 region.

**Comment by maciejwalkowiak** [comment]
It is suspicious. Are you sure `spring.cloud.aws.ses.region` does not get overwritten? We have a test for this specific use case https://github.com/awspring/spring-cloud-aws/blob/2.4.x/spring-cloud-aws-autoconfigure/src/test/java/io/awspring/cloud/autoconfigure/mail/SesAutoConfigurationTest.java#L72

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback
