### ISSUE TITLE
Add Secret Name As Prefix

### ISSUE THREAD

**Issue by akefirad** [awspring/spring-cloud-aws#627]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
Add secret name as a prefix to inject secret values.

**Describe the solution you'd like**
Let's say we have `spring.config.import=aws-secretsmanager:/secret/path/foo-secrets`. This will inject the content of `foo-secrets`. The problem is that what would happen if I import two secrets with similar keys. (I suspect it gets overridden.)
For manual secrets this is not a huge issue, since developers can prefix the keys in secrets to avoid collision. But this is not easily possible managed secrets (i.e. RDS Secrets on CloudFormation). You cannot just simple change the key name, specially if you have secret rotation configured.

**Describe alternatives you've considered**
🤷 

**Additional context**
This probably can be an opt-in or opt-out feature.

**Comment by maciejwalkowiak** [comment]
If I understand you well we solved it already in https://github.com/awspring/spring-cloud-aws/issues/621. Take a look please

**Comment by akefirad** [comment]
Ah nice, even better. Thanks.
