### ISSUE TITLE
SimpleStorageResouce createRelative At Root Bucket

### ISSUE THREAD

**Issue by ryanjbaxter** [awspring/spring-cloud-aws#648]
**Type**: Bug

**Component**:
S3

**Describe the bug**
If you create a `SimpleStorageResource` with a `objectName` of the empty string and then call `.createRelative` you get a new `Resource` but the `objectName` contains a `/`.  It seems like that if `objectName` is empty or `null` we should not prepend the `/`

**Sample**
See PR #649

**Comment by maciejwalkowiak** [comment]
Fixed in #649
