### ISSUE TITLE
Migrate Parameter Store to AWS SDK v2

### ISSUE THREAD

**Issue by MatejNedic** [awspring/spring-cloud-aws#65]
Parameter store integration should be moved from AWS SDK v1 to AWS SDK v2 in 3.0.x branch.

Note: we only need to keep loading properties via spring.config.import. Legacy way of importing properties should be removed.

Consider the following guidelines:

* Create package `io.awspring.cloud.autoconfigure.parameterstore` at `spring-cloud-autoconfigure` which contains `ParameterStoreProperties`, `ParameterStoreBootstrapConfiguration`, `ParameterStoreConfigDataLoader`, `ParameterStoreConfigDataLocationResolver`, `ParameterStoreConfigDataResource`
* Create module `spring-cloud-aws-parameter-store` which contains `ParameterStorePropertySource`, `ParameterStorePropertySourceLocator`, `ParameterStorePropertySources`
* Create module `spring-cloud-starter-aws-parameter-store` which contains a `pom.xml` with `spring-cloud-autoconfigure` and `spring-cloud-aws-parameter-store` dependencies
* Prefix should be `spring.cloud.aws.parameterstore`

**Comment by MatejNedic** [comment]
I  will check this one out.

**Comment by eddumelendez** [comment]
Description updated with guidelines to build the module

**Comment by eddumelendez** [comment]
Closing in favor of #91
