### ISSUE TITLE
Change SQS Integration Tests to use SqsTemplate

### ISSUE THREAD

**Issue by tomazfernandes** [awspring/spring-cloud-aws#658]
When the integration tests for the `SQS` integration were created, `SqsTemplate` didn't exist.

Now it's necessary to change them so they use the template instead of the raw `SqsAsyncClient`.

**Comment by rajadilipkolli** [comment]
I will pick this up, please assign to me

**Comment by tomazfernandes** [comment]
Cool, thanks!

**Comment by rajadilipkolli** [comment]
@tomazfernandes , Should I keep current tests as is and add newer ones with SqsTemplate or replace SqsAsyncClient?

**Comment by tomazfernandes** [comment]
For this issue the idea is to stop using the raw client at all - if there’s any use case the Template doesn’t cover please let me know.

If there’s anything you’d like to write a new test for that should be ok too, but perhaps in a separate PR.

**Comment by tomazfernandes** [comment]
@rajadilipkolli, just curious about how this is going. Any issues so far?
