### ISSUE TITLE
Simplify not adding type header in SqsTemplate sent messages

### ISSUE THREAD

**Issue by tomazfernandes** [awspring/spring-cloud-aws#659]
Currently in order to not add type information to messages sent with the `SqsTemplate` it's necessary to do something like this:

```java
SqsTemplate template = SqsTemplate.builder().sqsAsyncClient(this.asyncClient)
		.configureDefaultConverter(converter -> converter.setPayloadTypeHeaderValueFunction(msg -> null))
		.build();
```

We could make it more user-friendly and perhaps have a `TemplateOptions.doNotAddTypeInformationToSentMessages()` method or something similar.

**Comment by levys17** [comment]
May I try this one? Seems to be good to start!

**Comment by tomazfernandes** [comment]
Sounds good @levys17!

Let me know if there's anything you'd like to discuss.

**Comment by levys17** [comment]
Considering that _AbstractMessagingMessageConverter_ is responsible to set headers ( _typeHeader_  included), what do you thing about implement this method in this class?

```java
public void sendMessageWithoutTypeHeader() {
		this.payloadTypeHeaderFunction = message -> null;
}
```

```java
@Test
	void shouldSendAndReceiveRecordMessageWithoutPayloadInfoHeader() {
		SqsTemplate template = SqsTemplate.builder().sqsAsyncClient(this.asyncClient)
				.configureDefaultConverter(converter -> converter.sendMessageWithoutTypeHeader())
				.build();
		SampleRecord testRecord = new SampleRecord("Hello world!",
				"From shouldSendAndReceiveRecordMessageWithoutPayloadInfoHeader!");
		SendResult<SampleRecord> result = template.send(RECORD_WITHOUT_TYPE_HEADER_QUEUE_NAME, testRecord);
		assertThat(result).isNotNull();
		Optional<Message<SampleRecord>> receivedMessage = template
				.receive(from -> from.queue(RECORD_WITHOUT_TYPE_HEADER_QUEUE_NAME), SampleRecord.class);
		assertThat(receivedMessage).isPresent().get().extracting(Message::getPayload).isEqualTo(testRecord);
	}
```

Should I keep going implementing this way or perhaps there is a better way?

**Comment by tomazfernandes** [comment]
Hey @levys17, sorry for the delay!

> what do you thing about implement this method in this class?

This makes sense. I had thought of setting it in the `ContainerOptions` to try to make it more obvious and easier to find, but maybe it'd just add unnecessary complexity.

Regarding the method name, how about `converter.doNotSendTypeHeader()`? Seems a bit more straightforward, but I'm open to suggestions.

Let me know your thoughts, thanks!

**Comment by maciejwalkowiak** [comment]
@tomazfernandes looks like a good candidate for 3.1.1?

**Comment by tomazfernandes** [comment]
> @tomazfernandes looks like a good candidate for 3.1.1?

Yup, definitely!

**Comment by maciejwalkowiak** [comment]
Fixed in https://github.com/awspring/spring-cloud-aws/pull/1066
