### ISSUE TITLE
Add Support for StsAssumeRoleCredentialsProvider

### ISSUE THREAD

**Issue by kamaydeo** [awspring/spring-cloud-aws#666]
CredentialsProviderAutoConfiguration currently supports
1. StaticCredentialsProvider
2. ProfileCredentialsProvider
3. InstanceProfileCredentialsProvider

But it does not support StsAssumeRoleCredentialsProvider. I would like it to be supported or at least provide a way to override CredentialsProviderAutoConfiguration so I can use StsAssumeRoleCredentialsProvider.

**Comment by neiljbrown** [comment]
Hi @kamaydeo, 

Given your reference to CredentialsProviderAutoConfiguration, I assume you're using Spring Cloud AWS 3.x.  If so, you can override the auto-configured default by declaring your own bean of type AwsCredentialsProvider. For more details see https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-RC1/reference/html/index.html#credentials. 

If you're using 2.x then I believe you can also override the default by declaring your own bean of type AwsCredentialsProvider, but it additionally has to be named credentialsProvider.

Regards, Neil.

**Comment by kamaydeo** [comment]
@neiljbrown Although the bean can be overridden as shown in documentation, unfortunately, it doesn't work for my use case. I'm loading config data from SecretsManager i.e. SecretsManagerConfigDataLoader
`spring.config.import=aws-secretsmanager:...`

``` java
@Configuration
class CustomCredentialsProviderConfiguration {

    @Bean
    public AwsCredentialsProvider customAwsCredentialsProvider() {
        return new CustomAWSCredentialsProvider();
    }
}
```
The static method in `CredentialsProviderAutoConfiguration.createCredentialsProvider(...)` is invoked by `AbstractAwsConfigDataLocationResolver. configure(..)` when I use spring.config.import=aws-secretsmanager:...

see line number 126 in `AbstractAwsConfigDataLocationResolver`. Note that at this time, beans are not even initialized so customAwsCredentialsProvider doesn't help me.

**Comment by maciejwalkowiak** [comment]
@kamaydeo Secrets Manager and Parameter Store integration require slightly different approach for configuring credentials provider. Take a look at the example in docs: https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-RC1/reference/html/index.html#customizing-secretsmanagerclient

**Comment by maciejwalkowiak** [comment]
Perhaps we could make it easier by setting a property in `spring.cloud.aws.credentials` namespace. If you have ideas and/or would like to contribute, PRs are welcome!

**Comment by kamaydeo** [comment]
@maciejwalkowiak Thanks for pointing it out. It worked for me.

**Comment by eduanb** [comment]
Assume Role with service accounts and reading from secrets manager are common in EKS, so it would be nice if there were a simpler out of box solution for this.  As far as I could see, all of this is needed to get it working:
```
class SecretsManagerBootstrapConfiguration : BootstrapRegistryInitializer {
    override fun initialize(registry: BootstrapRegistry) {
        registry.register(SecretsManagerClient::class.java) {
            SecretsManagerClient
                .builder()
                .credentialsProvider(
                    StsWebIdentityTokenFileCredentialsProvider.builder()
                        .stsClient(StsClient.builder().region(Region.of(System.getenv("AWS_REGION"))).build())
                        .roleArn(System.getenv("AWS_ROLE_ARN"))
                        .webIdentityTokenFile(Path.of(System.getenv("AWS_WEB_IDENTITY_TOKEN_FILE")))
                        .build()
                ).build()
        }
    }
}
```
And then in `spring.factories`:
```org.springframework.boot.BootstrapRegistryInitializer=com.mycompany.SecretsManagerBootstrapConfiguration```

@maciejwalkowiak Can we open this again and investigate a simpler solution? Maybe something like detecting if the STS dependency is on the classpath?
