### ISSUE TITLE
Spring boot have released version 3.x.x. AwsSpring 2.4.4 is not compatible with that . Any plan for new release?

### ISSUE THREAD

**Issue by SumanMandal** [awspring/spring-cloud-aws#667]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maciejwalkowiak** [comment]
Spring Cloud AWS 3.0 is compatible with Spring Boot 3. We have recently released 3.0 RC1, GA is coming in February. All the details are in project readme.
