### ISSUE TITLE
How to send multiple messages as a batch to SQS queue

### ISSUE THREAD

**Issue by vijayrcse** [awspring/spring-cloud-aws#669]
Question

I would like to know how we can send multiple message as a batch to SQS queue.

Here is how we can do it using AWS SDK

`SendMessageBatchRequest send_batch_request = new SendMessageBatchRequest()
        .withQueueUrl(queueUrl)
        .withEntries(
                new SendMessageBatchRequestEntry(
                        "msg_1", "Hello from message 1"),
                new SendMessageBatchRequestEntry(
                        "msg_2", "Hello from message 2")
                        .withDelaySeconds(10));
sqs.sendMessageBatch(send_batch_request);`

I am trying to find out how we can do something similar using Spring Cloud AWS messaging

I only see the following example

` public void send(String message) {
        this.queueMessagingTemplate.send("physicalQueueName", MessageBuilder.withPayload(message).build());
    }`

Could anyone please advise ?

**Comment by tomazfernandes** [comment]
Hi @vijayrcse, thanks for bringing this up.

It's not possible to send message batches using Spring Cloud AWS 2.x `QueueMessageTemplate`.

In Spring Cloud AWS 3.0 however [we got you covered](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-RC1/reference/html/index.html#sending-messages-2):

`SendResult.Batch<T> sendMany(String queue, Collection<Message<T>> messages);`

We've just released RC1, feel free to try it out and provide feedback!

**Comment by vijayrcse** [comment]
thank you for your response. I will give it a try
