### ISSUE TITLE
Add More Samples to SQS Integration

### ISSUE THREAD

**Issue by tomazfernandes** [awspring/spring-cloud-aws#670]
We currently have only one [simple sample](https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-samples/spring-cloud-aws-sqs-sample/src/main/java/io/awspring/cloud/sqs/sample/SpringSqsSample.java) for the `SQS Integration`.

It would be nice to have more sample examples for more complex use-cases, such as:
- Manual container instantiation and message consumption
- Batch sending and receiving messages
- Manual acknowledgement
- Receive from multiple queues

And a lot more. Not all use cases must be contemplated in a single PR, a PR with one use case is already great.

The project's [Integration Tests](https://github.com/awspring/spring-cloud-aws/tree/main/spring-cloud-aws-sqs/src/test/java/io/awspring/cloud/sqs/integration) can be used as inspiration, and also the [integration's documentation](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-RC1/reference/html/index.html#sqs-integration).

Messages should be sent with `SqsTemplate`.

Please let us know of any issues or difficulties.

**Comment by mcruzdev** [comment]
No @tomazfernandes, can you assign for me?

**Comment by tomazfernandes** [comment]
Cool @mcruzdev, let us know if you run into any issues! Thanks

**Comment by mcruzdev** [comment]
Hi @tomazfernandes, sorry for delay :) 

I added a sample where a listen receives messages from multiple queues.

**Comment by mcruzdev** [comment]
The pull request for manua ack is here #774

**Comment by dottnul** [comment]
Hi @tomazfernandes 

I add a sample for task executor https://github.com/awspring/spring-cloud-aws/pull/839 

thanks :)

**Comment by tomazfernandes** [comment]
I think we're good for now, we may reopen the issue if necessary.

Thank you all for the contributions!
