### ISSUE TITLE
Missing parameters or documentation lagging?

### ISSUE THREAD

**Issue by gsrunion53** [awspring/spring-cloud-aws#671]
**Type**: Bug

**Component**:
ParameterStore SecretsManager

**Describe the bug**
Per [migration guide](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#migration-from-2-x-to-3-x) spring.cloud.aws.parameterstore.enabled and spring.cloud.aws.secretsmanager.enabled should exist. After getting complaints from my IDE about those values not being defined I checked out [the source code for 3.0.0-RC1](https://github.com/awspring/spring-cloud-aws/tree/v3.0.0-RC1) and those values appear to not be defined and challenges updating spring.could.aws to 3 (as per upgrading my application to spring boot 3) is failing as per misconfiguration. Supporting screenshots attached in a zip file because github would not accept my pngs for some reason.

[screenshots.zip](https://github.com/awspring/spring-cloud-aws/files/10733731/screenshots.zip)

**Comment by maciejwalkowiak** [comment]
Thank you for reporting @gsrunion53. Considering we switched from Bootstrap configuration for ParameterStore and SecretsManager and now to use either you must explicitly declare `spring.config.import` property, I don't think `enabled` flags make sense for these integrations anymore. 

I am leaning towards removing them from docs. What do you think? cc @MatejNedic

**Comment by buyukim** [comment]
That should be fine for `enabled`, but could we please keep the `fail-fast` property?

**Comment by maciejwalkowiak** [comment]
Since we don't magically load secrets from profiles, `fail-fast` does not apply anymore. Take a look at Secrets Manager docs in 3.0 https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#spring-cloud-aws-secrets-manager
