### ISSUE TITLE
SQS Listener is not working with Spring boot 3.0. What is the 3.0 release date?

### ISSUE THREAD

**Issue by raj-kindly** [awspring/spring-cloud-aws#679]
<!--
Thanks for raising a Spring Cloud issue. What sort of issue are you raising?

Question

We have moved to spring boot 3.0, but SQS is not working for this. Can you please suggest the required changes that needs to be done for new release 3.0 for this. We are stuck because of this and our planned release is stuck. Please help me with the release date planned for this and if there is any way 3.0.0-RC1 is going to be updated on maven quicker?

**Comment by raj-kindly** [comment]
I have moved to spring boot 3.0, but SQS is not working for this and we are stuck because of this. There is a very critical release planned and is getting delayed. Can you please update if there is any fixed release date for this? Also, is there a chance to put 3.0.0-RC1 on maven and i can use that for the time being?

**Comment by raj-kindly** [comment]
I am not able to use 3.0.0-RC1 in my pom file. Please suggest how can i use this.

**Comment by ramyogi** [comment]
What reason not able to use in your POM ?  I am using RC1., it is working properly.

**Comment by ramyogi** [comment]
<dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>3.0.0-RC1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

**Comment by ramyogi** [comment]
```
<dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>3.0.0-RC1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

**Comment by maciejwalkowiak** [comment]
RC1 is published to Maven central. Perhaps something else is wrong with your project. If you publish a sample project that reproduces this issue I'll take a look

**Comment by raj-kindly** [comment]
Thanks for the answer. I got it resolved.
