### ISSUE TITLE
Run CI build with Java 8, 11, 15

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#68]
Github actions for building should use matrix with Java versions so that we run build against main branch and PRs with Java 8, 11 and 15.

**Comment by sivaprasadreddy** [comment]
@maciejwalkowiak With the fix for Java 11 test failures https://github.com/awspring/spring-cloud-aws/pull/74
the build is running successfully with `8.0.275.hs-adpt`, `11.0.10.hs-adpt`, `15.0.2.hs-adpt`.
For reference https://github.com/sivaprasadreddy/spring-cloud-aws/actions/runs/576656636

**Comment by sivaprasadreddy** [comment]
Java 11 is already added. Adding Java 15 to the build matrix, PR https://github.com/awspring/spring-cloud-aws/pull/75

**Comment by maciejwalkowiak** [comment]
Thanks again @sivaprasadreddy!
