### ISSUE TITLE
GrantedAuthoritiesMapper for AWS Cognito

### ISSUE THREAD

**Issue by poklakni** [awspring/spring-cloud-aws#681]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
If we want to work with cognito groups as granted authorities we need a custom mapper. I've already tried something.
```java
public class CognitoAuthoritiesMapper implements GrantedAuthoritiesMapper {

  private static final String COGNITO_GROUPS = "cognito:groups";

  private static final String OIDC_USER = "OIDC_USER";

  @Override
  public Collection<? extends GrantedAuthority> mapAuthorities(
      Collection<? extends GrantedAuthority> authorities) {
    return authorities.stream()
        .map(OidcUserAuthority.class::cast)
        .filter(grantedAuthority -> OIDC_USER.equals(grantedAuthority.getAuthority()))
        .findFirst()
        .map(this::extractGrantedAuthorities)
        .orElse(Collections.emptySet());
  }

  private Set<GrantedAuthority> extractGrantedAuthorities(OidcUserAuthority oidcUserAuthority) {
    if (!oidcUserAuthority.getAttributes().containsKey(COGNITO_GROUPS)) {
      return Collections.emptySet();
    }
    return ((List<?>) oidcUserAuthority.getAttributes().get(COGNITO_GROUPS))
        .stream()
            .map(role -> new SimpleGrantedAuthority(UserRole.PREFIX + role))
            .collect(Collectors.toSet());
  }
}
```

**Describe the solution you'd like**
An authorities mapper without a need to implement a custom one. See the example above.
Usage in security filter chain:
```java
    http.oauth2Login()
        .userInfoEndpoint()
        .userAuthoritiesMapper(cognitoAuthoritiesMapper);
```

**Comment by maciejwalkowiak** [comment]
@poklakni would you like to contribute this change?

**Comment by maciejwalkowiak** [comment]
That's not an issue I'm happy to guide you. Fork this repository, create a branch `gh-681`, code your change, remember to add tests, run build with `./mvnw install`. Look into contributor guidelines somewhere in readme.

Your PR doesn't need to be perfect, don't stress about it.

If you have any questions, just ask.

**Comment by poklakni** [comment]
I've managed to map the authorities using https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.html

I personally don't need this feature anymore

**Comment by maciejwalkowiak** [comment]
Thanks for an update @poklakni
