### ISSUE TITLE
[Question] Reconsider dependency on Spring Boot 3 for AWS Lambda

### ISSUE THREAD

**Issue by apetrelli** [awspring/spring-cloud-aws#685]
Greetings

AWS Lambda currently is stuck on Java 11. Spring Cloud AWS 3 has the dependency on Spring Boot 3 that depends on Java 17.

This means that, when writing Java-based lambdas, we can only use Spring Cloud AWS 2.4.x and we are stuck to the old v1 versions of the SDK.

Is there any possibility to reconsider this dependency on Spring Boot 3? Or create a 2.5.x version that depends on Spring Boot 2.7.x?

Currently in my project there is a situation in which both the versions of AWS SDK are present, those used directly are v2 and those used by Spring Cloud AWS is v1. Not a big deal, however it is strange.

Thanks a lot

**Comment by neiljbrown** [comment]
Hi, re: min Java 17 baseline for Spring Cloud AWS 3.x (inherited from Boot 3.x) - someone on the AWS team published a comment a few weeks suggesting that Lambda official support for Java 17 may finally be getting closer, with some progress (if not full support) to be announced later this month. See https://github.com/aws/aws-lambda-base-images/issues/29#issuecomment-1414363368. 

In the meantime, as per your other question, I believe Spring Cloud AWS 2.4.x is already compatible with Spring Boot 2.7.x. See the project docs here https://github.com/awspring/spring-cloud-aws#compatibility-with-spring-project-versions and here https://awspring.io/learn/introduction/#versions.  (But you'll still be constrained to using AWS SDK v1). 

Neil.

**Comment by apetrelli** [comment]
Hi and thanks @neiljbrown I am using version 2.4.x version proficiently, but sometimes we use the SDK directly and we would prefer to use AWS SDK V2 all the times to avoid confusion and having to deploy both versions.
About the issue that you mentioned, he said that the base image will be published the end of this month. For the rest (tooling support and Lambda support, in particular SnapStart) we will need to wait more.

Let's hope for the best, thanks again

**Comment by maciejwalkowiak** [comment]
@apetrelli thanks for reaching out. We are not planning to add support for AWS SDK v2 based Spring Cloud AWS for Spring Boot 2.7 - the only reason is it is too much work. If you need temporarily to have such support, I recommend forking Spring Cloud AWS, adjust it to Spring Boot 2.7 (there should be not much work to get it working). Once there is an official support for Java 17 on AWS lambda you can then drop the fork.

**Comment by apetrelli** [comment]
Thanks @maciejwalkowiak in fact I was wondering of forking the project (after all i should scratch my own itches :-D ). I see so many benefits by using version 3, such as SDK v2 and prefixes in Secrets Manager.

Now I only need some time :-D

**Comment by maciejwalkowiak** [comment]
Good luck @apetrelli! :-)
