### ISSUE TITLE
Allow to set the phase for MessageListenerContainer related to the SmartLifecycle interface on 3.0.0+

### ISSUE THREAD

**Issue by estigma88** [awspring/spring-cloud-aws#693]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
With previous versions of Spring Could AWS (No Spring Boot 3), we had troubles with the graceful shutdown process in Spring Boot. We have an application with the following components:
- SqsListener
- Quartz Scheduler

Seems like when the application is shutting down, SQS components and Quartz Scheduler components, have the same `SmartLifecycle.phase`, and they collide, causing Quartz to not shutting down completely, and letting some crons in the database corrupted.

The workaround we found was the following:

```
    @Bean
    fun beanXXXX(
       simpleMessageListenerContainer: SimpleMessageListenerContainer
    ): String {
        /**
         * SQS and Quartz seem having the same shutdown priority,
         * which causes problems with Quartz and cannot shutdown fine.
         *
         * phase = Integer.MAX_VALUE - 1 tells SQS to shutdown before Quartz.
         */
        simpleMessageListenerContainer.phase = Integer.MAX_VALUE - 1
        return "ok"
    }
```
Moving SQS components one phase before, guarantee SQS shutdowns first, and later, Quartz.

**Describe the solution you'd like**
A way to set the phase for the SmartLifecycle interface for 3.0.0+

**Describe alternatives you've considered**
- Testing again the collision with the latest version and see if the cron problem still appears.
- Going the rabbit hole and trying to find what's happening under the hood with this collision.

**Additional context**
I will try to create a minimal project to reproduce the issue, but it is environment dependent, not sure I can make it.

**Comment by tomazfernandes** [comment]
Hi @estigma88, sorry for the delay - I wanted 3.0.0 to be out before making many more modifications to the SQS code.

Would you like to contribute a PR for this feature?

**Comment by estigma88** [comment]
Sure, I can give it a try. Let me come back with one MR for this.
