### ISSUE TITLE
Invalid type of SqsSendOptions.messageGroupId

### ISSUE THREAD

**Issue by jkatnik** [awspring/spring-cloud-aws#694]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
Hi,

I'm in the middle of a migration from SB 2.7 to 3.
I came across a strange limitation, which could be a design bug.

With the new API, it is not possible to send a message to the AWS SQS FIFO queue with any (yet AWS valid) group ID. The API forces to use UUID as an ID.

```
SqsSendOptions<T> messageGroupId(UUID messageGroupId);
```

https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/operations/SqsSendOptions.java

It is very common to use some business key, like customer number, as message group ID.

Please consider fixing it in the next RC or point me to the workaround (maybe I misused the API).

**Sample**
```
private fun sendCheckoutEvent(message: String, customerId: String) {
    sqsTemplate.send {
      it.queue("int-entitlement-commands.fifo")
      it.messageGroupId(customerId) // compilation error here
      it.payload(message)
    }
  }
```

**Comment by maciejwalkowiak** [comment]
@tomazfernandes could you please take care of that?

**Comment by tomazfernandes** [comment]
Sure, let's change it to `String`.

@jkatnik As a workaround, you can add the message group id as a header: `SqsHeaders.MessageSystemAttributes.SQS_MESSAGE_GROUP_ID_HEADER`.

Same goes for `messageDeduplicationId`.

Please let us know if that works for you. Thanks.

**Comment by jkatnik** [comment]
@tomazfernandes 
it is acceptable as a temporary workaround, but in my opinion, it is "not natural" to do it that way. Other API users will stumble on that issue too. I'd prefer to have it fixed with the next RC.

**Comment by tomazfernandes** [comment]
Sure @jkatnik, we'll change the API to `String`. This is a temporary workaround to keep you going until them.
