### ISSUE TITLE
Parameterstore import with 3.0.0-RC1 prepends periods to parameter name?

### ISSUE THREAD

**Issue by gsrunion53** [awspring/spring-cloud-aws#696]
**Type**: Bug

**Component**:
Parameter Store

**Describe the bug**
Working with 3.0.0-RC1 and successfully pulling configuration for AWS seems to prefix all imported value names with a dot. Am I configuring something wrong?

```
spring:
  config:
    activate:
      on-profile: aws
    import: aws-parameterstore:/config/application
```

**Sample**
Our application dumps all spring configuration to the console on startup here is a snipped for values that come from parameter store via Spring Cloud Aws.

```
2023-03-01T19:49:53.331Z  INFO 26 --- [main] c.f.d.s.t.TransactionDatabaseService     : .lambda_cloudwatch_alert_id: AWSLambdaCloudwatchAlert
2023-03-01T19:49:53.331Z  INFO 26 --- [main] c.f.d.s.t.TransactionDatabaseService     : .oauth_b2e_issuer_uri: https://np.b2.sso.45.com
2023-03-01T19:49:53.332Z  INFO 26 --- [main] c.f.d.s.t.TransactionDatabaseService     : .spring-boot-admin-permissions-read: g.food_services_sba_read.stg
```

**Comment by maciejwalkowiak** [comment]
We replace `/` with `.` ([look here for details](https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-parameter-store/src/main/java/io/awspring/cloud/parameterstore/ParameterStorePropertySource.java#L81)) I guess with an assumption that slashes can be in the middle of the parameter name. I guess in your case they are in the front? What are the names of these parameters?

We have covered use cases listen in the integration test: https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-autoconfigure/src/test/java/io/awspring/cloud/autoconfigure/config/parameterstore/ParameterStoreConfigDataLoaderIntegrationTests.java

Perhaps there is something we can improve there.

**Comment by gsrunion53** [comment]
The path for the middle parameter above, for example, is /config/application/oauth_b2c_issuer_uri in parameterstore and we reference it in various places in yaml (and perhaps with $value) as "{oauth_b2e_issuer_uri}" and going to all the places the reference and changing the name is possible but could be a lot.

Our previous import string, with Spring Boot 2.7.7 and Spring Cloud AWS 2.4.2 was 

```
import: optional:aws-parameterstore:, aws-secretsmanager:/secret/${SERVICE_KEY}/rds-v2-pw/owner, optional:vault:// #https://github.com/spring-cloud/spring-cloud-vault/issues/571#issuecomment-791301500
```

This new behavior could very well be my own lack of understanding of how to use your project. But that is why I am asking.

**Comment by maciejwalkowiak** [comment]
I think you're just missing a slash at the end:

```
spring.cloud.config.import: aws-parameterstore:/config/application/
```

Can you give it a try?

**Comment by gsrunion53** [comment]
I certainly will. Thanks for the guidance.

**Comment by gsrunion53** [comment]
It is working as intended. Thanks for the help.

**Comment by gsrunion53** [comment]
Issue resolved. User (me) error.

**Comment by maciejwalkowiak** [comment]
Fantastic!
