### ISSUE TITLE
Configure AWS Region from the profile file with AwsProfileRegionProvider

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#70]
Similar to `CredentialsProviderAutoconfiguration`, `ProfileProviderAutoconfiguration` should be able to configure region using `AwsProfileRegionProvider`.

`AwsProfileProperties` should have a new property `profile` containing name and path and auto-configuration should take it into account similar to how credentials are configured.

**Note**: create a fork from branch `3.0.x` and do changes in the `v3` module.

**Comment by sivaprasadreddy** [comment]
Hi @maciejwalkowiak Can I work on this?

**Comment by maciejwalkowiak** [comment]
@sivaprasadreddy sure it's yours! Thanks!
