### ISSUE TITLE
Usage of the entrypoint and region results in error during Parameter Store initialization

### ISSUE THREAD

**Issue by typekpb** [awspring/spring-cloud-aws#702]
**Type**: Feature

**Component**:

Parameter Store

**Is your feature request related to a problem? Please describe.**
I'd like to use localstack (alternative endpoint: http://localhost:4566) with non-default region.

I'm using java 11.

Having in `build.gradle`:

```
plugins {
    id 'org.springframework.boot' version '2.7.7'
}
apply plugin: 'org.springframework.boot'

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2021.0.5"
    }
}


dependencies {
    implementation 'io.awspring.cloud:spring-cloud-aws-autoconfigure:2.4.4'
    implementation 'io.awspring.cloud:spring-cloud-starter-aws-parameter-store-config:2.4.4'
    ...
}
```
And `application.properties`:
```
aws.paramstore.endpoint=http://localhost:4566
cloud.aws.region.static=eu-central-1
```

Results in the error: 
```
Only one of Region or EndpointConfiguration may be set.
```
due to: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/client/builder/AwsClientBuilder.java#L450

Current workaround is to set in the `application.properties` only the:
```
aws.paramstore.endpoint=http://localhost:4566
```
And adapting the localstack region to `us-east-1`. Which is however not reflecting my AWS deployment region.

**Comment by maciejwalkowiak** [comment]
Since this is an error from the SDK i am not sure what can we do about it? 

It should not happen with 3.0.

**Comment by typekpb** [comment]
@maciejwalkowiak agree, I'm just looking for ideas to overcome it :)
version 3.0 is unfortunatelly not feasable for me, due to java 11 restriction.

**Comment by maciejwalkowiak** [comment]
Closing because i don't think there is something we can do here. I believe that region used in tests doesn't need to match the region in your production envrionment.
