### ISSUE TITLE
Mapping SQS binary attribute results in NPE

### ISSUE THREAD

**Issue by mkoziej-tink** [awspring/spring-cloud-aws#708]
**Type**: Bug

**Component**: SQS

**Describe the bug**
https://github.com/awspring/spring-cloud-aws/blob/a09341d15fd163cb6779e168649cce1a3c963f32/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/support/converter/SqsHeaderMapper.java#L174

`stringValue()` returns `null` for binary attribute, which results in NPE and listener shutdown

**Comment by tomazfernandes** [comment]
Thanks @mkoziej-tink, I’ll take a look.

**Comment by tomazfernandes** [comment]
https://github.com/awspring/spring-cloud-aws/pull/709

@maciejwalkowiak, I used your code from the previous version for resolving numbers, please let me know if I missed something.

**Comment by tomazfernandes** [comment]
Closed by https://github.com/awspring/spring-cloud-aws/pull/709
