### ISSUE TITLE
Configure AWS Region from the instance profile with InstanceProfileRegionProvider

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#71]
Similar to `CredentialsProviderAutoconfiguration`, `ProfileProviderAutoconfiguration` should be able to configure region using `InstanceProfileRegionProvider`.

`AwsProfileProperties` should have a new property `instanceProfile` and auto-configuration should take it into account similar to how credentials are configured.

**Note**: create a fork from branch `3.0.x` and do changes in the `v3` module.

**Comment by mcruzdev** [comment]
Hello, @maciejwalkowiak
Can you assign for me?

**Comment by maciejwalkowiak** [comment]
Sure! Thanks for taking care of this one :-)

**Comment by mcruzdev** [comment]
@maciejwalkowiak, 
Thank you for assigns to me, I am very excited to contribute

I have a question:

> Similar to `CredentialsProviderAutoconfiguration`, `ProfileProviderAutoconfiguration` should be able to configure region using `InstanceProfileRegionProvider`.

Should I create a new class called ProfileProviderAutoconfiguration  for `software.amazon.awssdk.regions.providers.AwsRegionProvider` ? Can I use RegionProviderAutoconfiguration instead verifying if instanceProfile exists like `CredentialsProviderAutoconfiguration`?

**Comment by maciejwalkowiak** [comment]
Use the existing auto-configuration `RegionProviderAutoconfiguration` similar how it's done with credentials.
