### ISSUE TITLE
Health check for Sqs Listener Containers

### ISSUE THREAD

**Issue by jgangemi** [awspring/spring-cloud-aws#711]
i'm interested in a health check that is similar to what is described here: 

https://github.com/spring-attic/spring-cloud-aws/issues/317

however i'm unsure of how to go about that against version 3. i tried injecting a `SqsMessageListenerContainer` into my `HealthIndicator` implementation, similar to what is described in that issue but i get an error saying no beans of that type have been defined.

how would i go about getting a reference to whatever object i need to accomplish this?

thanks!

**Comment by tomazfernandes** [comment]
Hey @jgangemi, thanks for bringing it up. We have already discussed about a health check [here](https://github.com/awspring/spring-cloud-aws/discussions/528).

Please take a look and let us know what you think. Thanks.

**Comment by tomazfernandes** [comment]
> however i'm unsure of how to go about that against version 3. i tried injecting a `SqsMessageListenerContainer` into my `HealthIndicator` implementation, similar to what is described in that issue but i get an error saying no beans of that type have been defined.
> 
> how would i go about getting a reference to whatever object i need to accomplish this?

The object you need is the `MessageListenerContainerRegistry`, that's also described in the link above. Please let us know if that works for you.

**Comment by jgangemi** [comment]
it is, thank you!
