### ISSUE TITLE
SQS back off time equivalent in 3.x.x

### ISSUE THREAD

**Issue by tomazfernandes** [awspring/spring-cloud-aws#714]
### Discussed in https://github.com/awspring/spring-cloud-aws/discussions/713

<div type='discussions-op-text'>

<sup>Originally posted by **timothysugar** March 14, 2023</sup>
While using Starter SQS from 3.0.0-RC1, at times my queue consumer suffers from network connectivity failures with AWS. I see a very large number of errors raised due to reconnection attempts. My immediate issue is that this floods the logs with errors. It appears to me that in the 2.x versions, this behaviour could be affected using the `cloud.aws.sqs.listener.back-off-time` configuration property, but I don't see any equivalent for 3.x.

Is that correct? Is there any suggested way of affecting this behaviour?

Thank you for your contributions to this project.</div>

**Comment by tomazfernandes** [comment]
@timothysugar, we currently don't have such a mechanism in 3.0, but we can look into adding it.

Just to be clear, the expected behavior is being able to configure a back off time to be applied if the polling returns an error, is that correct?

@maciejwalkowiak, please let me know if you have anything to add.

Thanks.

**Comment by maciejwalkowiak** [comment]
@tomazfernandes yes, if polling fails, it's the time that listener should wait until the polling is retried. The default is 10s. It has been introduced long time ago as an answer to following issue: https://github.com/spring-attic/spring-cloud-aws/issues/82

If we have different way to address the same issue we can just document it in the migration guide.

**Comment by timothysugar** [comment]
> Just to be clear, the expected behavior is being able to configure a back off time to be applied if the polling returns an error, is that correct?

@tomazfernandes Yes, that's correct. A default of 10s for this also seems more appropriate and would meet my requirement.

**Comment by tomazfernandes** [comment]
Hey @timothysugar, now that 3.0 is out, would you like to contribute a PR for this feature? We can likely include it in 3.1 if so.

Thanks

**Comment by tomazfernandes** [comment]
@timothysugar, took some time but here you go. Feel free to review the PR in case you have any suggestions or comments. 
https://github.com/awspring/spring-cloud-aws/pull/1008
