### ISSUE TITLE
Unable to create bean SimpleMessageListenerContainer due to not matched signature 

### ISSUE THREAD

**Issue by ct24p** [awspring/spring-cloud-aws#716]
Hello, could you please help? thanks very much.
   We are trying to use spring-cloud-aws (2.3.5) to handle s3 file upload event as following (java + user credentials + aws assume role, role with right permission to retrieve access/secret keys from secret manager):
    @SqsListener(value="${my.sqs.name}", deletionPolicy=SqsMessageDeletionPolicy.ON_SUCCESS)
    public void receiveMessages(S3EventNotification s3Event) { ... }

The spring boot java config file initiate AmazonSQSAsync bean as:

```
@Bean("amazonSQS")
@DependsOn ("awsCredentialsProvider")
public AmazonSQS amazonSqs() throws JsonProcessingException {
    return AmazonSQSAsyncClientBuilder.standard()
          .withCredentials(credentialsProvider())
          .withRegion(Regions.fromName(region))
          .build();
}
```
Where credentialsProvider() will depends on the AWS access/secret keys retrieved from secret manager. AmazonSQS bean creation OK, but failed with following message while create bean SimpleMessageListenerContainer:

```
ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simpleMessageListenerContainer' defined in class path resource [io/awspring/cloud/autoconfigure/messaging/SqsAutoConfiguration$SqsConfiguration.class]: Invocation of init method failed; nested exception is com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AWSSecurityTokenService; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: ....
```

If we directly use aws user credentials instead of retrieving from secret manager, everything works fine.
If we remove spring-aws-cloud (thus no SqsListener but still create AmazonSQS bean), everything works fine.
Googled around and some posts indicating credentials with special characters such as  / or + are the issues, but some claiming no special character credential still failed.

**Comment by maciejwalkowiak** [comment]
Ideally please try with the latest version in 2.x and see if the issue remains. If it does, maybe we can figure it out.

**Comment by ct24p** [comment]
BTW, tried 2.4.2 spring-cloud-aws, same issue. thx

**Comment by ct24p** [comment]
by debugging, issue from com.amazonaws.http.AmazonHttpClient.java (execOneParams.apacheRequest=POST https://sts.amazonaws.com/ HTTP/1.1, Header info: name=Authorization, value=AWS4-HMAC-SHA256 Credential=..., Signature=....): when try to retrieve secrete from secret manager (temporary credentials) and after assume role ( retrieved from secret manager), different credentials make the above POST return 403 Forbidden. Tried modify task definition by adding secrets, failed with same errors. thanks

**Comment by maciejwalkowiak** [comment]
Closing as 2.x is not maintained anymore. If you would like to contribute a fix for that, we will make an exception and release new 2.x version.
