### ISSUE TITLE
SQS retry delay

### ISSUE THREAD

**Issue by schlumpfling42** [awspring/spring-cloud-aws#717]
**Type**: Issue

**Component**:
SQS

**Describe the bug**
I'm trying to implement a SQS listener that is processing a message with 4 retries if the message fails 5 times it gets moved to a DLQ. It's easy to set up and I got the whole flow working.

However if there is an issue processing the message I want to delay the retry (and only the retry - not the original message) for a couple of minutes.
I tried quite a few of things:
 - wrote code to catch the error and creating a new message with a delay - that works, but I lose the ability to automatically move it to the DLQ because a new message resets the delivery counter.
 - created a retry queue with a delay on the queue - I created 2 listeners and have the retry queue set up as the DLQ for the original queue with a count of 1, so if the message fails it gets moved over to the retry queue, but the delay is not working, it processes the message right away/
 - created a retry queue with a delay on the queue - and programmatically send the message from the first queue to the retry queue - that worked for the 1st message, but all the retries are ignoring the delay set up on the queue

I'm out of ideas what to do ... I can't put my finger on where the problem is. Is this a spring-cloud-aws issue on how it deals with retries? Is that an AWS SQS issue?
I don't think this is an unreasonable scenario, I want to delay the retries of the processing of a message, because I might have some environment issues that might be resolved if I wait a few minutes. There has to be an easy way to do this without re-implementing the retry and DLQ functionality.

Any ideas on how to solve or debug this?

**Comment by tomazfernandes** [comment]
Hey @schlumpfling42, thanks for bringing this up.

The usual strategy to achieve this behavior is to set a `visibilityTimeout` to e.g. 5 minutes.

This way if message processing fails the message will remain `invisible` for the remaining time after the error, and will be processed again after that.

With this you can use all `SQS` goodies such as redriving the message to a `DLQ` after retries are exhausted.

How does that sound?

**Comment by schlumpfling42** [comment]
@tomazfernandes I have the visibility time set to 3 minutes, so that has no impact on when the messages are picked up with or without an error. As far as I understand this only has an impact if the consumer doesn't respond.

**Comment by schlumpfling42** [comment]
@tomazfernandes I tested this out with a lambda and the lambda does honor the visibility timeout, most likely because it does not communicate with the queue on error. So that would work for me. How do I prevent the message being put back onto the queue/released when there is an Error? Can I actively take control of that?

**Comment by schlumpfling42** [comment]
@tomazfernandes Ahhh darn it ... I just found the problem. So it is working as designed and the visibility timeout is the way to go. One has just to be sure to not overwrite that timeout in the code. I found that I have set a different timeout in my configuration when setting up the SimpleMessageListenerContainerFactory and that overrides whatever is set in the queue!
