### ISSUE TITLE
Serialization to Java object fails when receiving SQS messages using QueueMessagingTemplate

### ISSUE THREAD

**Issue by kjhok1811** [awspring/spring-cloud-aws#718]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
When sending a message to SQS using QueueMessagingTemplate and receiving it in a method annotated with @SqsListener, an error occurs in the process of converting a JSON string to a Java object.

**Sample**
![image](https://user-images.githubusercontent.com/90641957/226092970-058d35b1-6279-4e48-87dc-fd641b4c546a.png)
Create an SQS for testing in the AWS SQS Console and send the JSON string.

<br>

```java
@SpringBootApplication
public class DemoApplication {
    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @SqsListener(value = "TEST_QUEUE", deletionPolicy = SqsMessageDeletionPolicy.ALWAYS)
    public void receive(Member member) {
        System.out.println("name : " + member.getName());
        System.out.println("age : " + member.getAge());
    }
}
```
This is the code that receives messages in SQS and converts JSON strings to Java objects using MappingJackson2MessageConverter.

<br>

![image](https://user-images.githubusercontent.com/90641957/226093219-a50551c8-d1ab-448a-b048-e74958de9475.png)
Messages sent from SQS Console are successfully converted to Java objects.

<br>

```java
@SpringBootApplication
public class DemoApplication {
    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Bean
    public CommandLineRunner commandLineRunner(AmazonSQSAsync amazonSQSAsync) {
        return args -> {
            QueueMessagingTemplate queueMessagingTemplate = new QueueMessagingTemplate(amazonSQSAsync);

            String payload = """
                    {"name":"kimjonghyun", "age":30}
                    """.trim();
            Map<String, Object> headers = Map.of("contentType", "application/json");

            queueMessagingTemplate.convertAndSend("TEST_QUEUE", payload, headers);
        };
    }

    @SqsListener(value = "TEST_QUEUE", deletionPolicy = SqsMessageDeletionPolicy.ALWAYS)
    public void receive(Member member) {
        System.out.println("name : " + member.getName());
        System.out.println("age : " + member.getAge());
    }
}
```
Now let's send it to the QueueMessagingTemplate.

<br>

![image](https://user-images.githubusercontent.com/90641957/226093403-36bb0c57-61a4-4007-af2b-4bca6e3b26bf.png)
You can see that an exception has occurred. Now let's talk about why this exception was thrown.

<br>

![image](https://user-images.githubusercontent.com/90641957/226093544-c10afdec-1fa7-4710-86bd-e459b9d56be0.png)
In MappingJackson2MessageConverter#convertToInternal, ObjectMapper reads payload and puts it in StringWriter.
If you look closely at the picture, you can see that the results of payload and write.toString() are different.

<br>

![image](https://user-images.githubusercontent.com/90641957/226093788-96804e0a-a7e2-4cd2-89a6-de9c15468595.png)
And convert payload to Java object in MappingJackson2MessageConverter#convertFromInternal.

<br>

![image](https://user-images.githubusercontent.com/90641957/226093828-6530d61b-234f-4a8c-8f23-56b745f05dd5.png)
An exception is thrown at this time.
In the process of putting the payload into the StringWriter in the convertToInternal method, the problem seems to be caused by " being covered at both ends.

<br>

![image](https://user-images.githubusercontent.com/90641957/226094439-56bf9c10-fd4e-417c-bfe7-725400617c19.png)
AbstractMessageConverter#toMessage is called when sending an SQS message using QueueMessagingTemplate.

**Comment by MatejNedic** [comment]
Hey @kjhok1811 ,
Thanks on reporting.
Which version of Spring Cloud AWS are you using?
From code snippets, I would say 2.x, I recommend switching to 3.0.0-RC1 since it has a lot of performance improvements.

**Comment by kjhok1811** [comment]
@MatejNedic 
I am using io.awspring.cloud version 2.3.3.
Spring Boot uses version 2.6.x.

**Comment by MatejNedic** [comment]
Hey @kjhok1811 ,
Please inject `QueueMessagingTemplate` instead of creating your own.
I believe your issue should be resolved then.
If you want to create your own `QueueMessagingTemplate` you can pass your own `ObjectMapper` to it and `MessageConverter `

**Comment by kjhok1811** [comment]
```java
@Configuration
@RequiredArgsConstructor
public class AmazonSQSConfiguration {
    private final ObjectMapper objectMapper;
    .....
    
    @Bean
    public AmazonSQSAsync amazonSQSAsync() {
        return AmazonSQSAsyncClientBuilder.standard()
                .withRegion(Regions.AP_NORTHEAST_2)
                .withCredentials(DefaultAWSCredentialsProviderChain.getInstance())
                .withRequestHandlers()
                .build();
    }
   
    @Bean
    public QueueMessageHandler queueMessageHandler() {
        QueueMessageHandlerFactory queueMessageHandlerFactory = new QueueMessageHandlerFactory();
        queueMessageHandlerFactory.setAmazonSqs(amazonSQSAsync());
        queueMessageHandlerFactory.setMessageConverters(getMessageConverters());

        return queueMessageHandlerFactory.createQueueMessageHandler();
    }

    @Bean
    public SimpleMessageListenerContainer simpleMessageListenerContainer() {
        SimpleMessageListenerContainer simpleMessageListenerContainer = new SimpleMessageListenerContainer();
        simpleMessageListenerContainer.setAmazonSqs(amazonSQSAsync());
        simpleMessageListenerContainer.setMessageHandler(queueMessageHandler());

        return simpleMessageListenerContainer;
    }

    @Bean
    public QueueMessagingTemplate queueMessagingTemplate() {
        QueueMessagingTemplate queueMessagingTemplate = new QueueMessagingTemplate(amazonSQSAsync());

        MappingJackson2MessageConverter mappingJackson2MessageConverter = new MappingJackson2MessageConverter();
        mappingJackson2MessageConverter.setSerializedPayloadClass(String.class);
        mappingJackson2MessageConverter.setObjectMapper(this.objectMapper);
        queueMessagingTemplate.setMessageConverter(mappingJackson2MessageConverter);

        return queueMessagingTemplate;
    }
}
```
After creating custom MappingJackson2MessageConverter in the way you said
I put it when creating a bean of the QueueMessagingTemplate type.

<br>
<br>

```java
@SpringBootApplication
public class DemoApplication {
    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Bean
    public CommandLineRunner commandLineRunner(QueueMessagingTemplate queueMessagingTemplate) {
        return args -> {
            String payload = """
                    {"name":"kimjonghyun", "age":30}
                    """.trim();
            Map<String, Object> headers = Map.of("contentType", "application/json");

            queueMessagingTemplate.convertAndSend("TEST_QUEUE", payload, headers);
        };
    }

    @SqsListener(value = "TEST_QUEUE", deletionPolicy = SqsMessageDeletionPolicy.ALWAYS)
    public void receive(Member member) {
        System.out.println("name : " + member.getName());
        System.out.println("age : " + member.getAge());
    }
}
```

<br>

![image](https://user-images.githubusercontent.com/90641957/227767956-076b85d8-8121-473a-a268-9591a5b3569c.png)
The result is the same exception.

@MatejNedic

**Comment by MatejNedic** [comment]
Hey @kjhok1811 , could you please provide a sample? It will be easier to reproduce an issue and see where the problem is.

**Comment by kjhok1811** [comment]
@MatejNedic 
https://github.com/kjhok1811/demo

I have created a simple Demo application.

Java verison : 17
Spring Boot version : 2.6.8
Spring Cloud  AWS version : 2.4.0

**Comment by MatejNedic** [comment]
Thanks @kjhok1811 ,
Will check the issue in the following days.
Could you please provide a test inside of the repository with a failing json message?

**Comment by kjhok1811** [comment]
Need code that makes your tests fail?

2023년 4월 6일 (목) 오전 3:02, MatejNedic ***@***.***>님이 작성:

**Comment by kjhok1811** [comment]
Need test code for the picture shown above?

**Comment by MatejNedic** [comment]
I checked it a little bit further now. Since Spring Messaging is doing conversion it was never intended to use `queueMessagingTemplate.convertAndSend`  with a String but rather with an object like Member in your case.

If you want to pass JSON as a string you will need to use the method  `queueMessagingTemplate.send` and create `GenericMessage` object.

```
       String payload = """
                    {"name":"kimjonghyun", "age":30}
                    """.trim();
        Map<String, Object> headers = Map.of("contentType", "application/json");
        queueMessagingTemplate.send("TEST_QUEUE", new GenericMessage<>(payload, headers));
```

Now it should work without any issues I ran it multiple times. 
So if you modify your code to this it will work.

Sorry for the delay once again.  :)

**Comment by kjhok1811** [comment]
Thank you for your answer. If you use the convertAndSend method, you need to receive it the same type as payload, and if you use the send method, Jackson will try to deserialize it ?

**Comment by MatejNedic** [comment]
Hey @kjhok1811 ,
Yes, this is how the method was intended to be used. It was created to convert any object into its JSON representation and add all the headers needed. In send method we will send what you pass without trying to convert it to JSON representation.

You had an issue with convertAndSend since your JSON would look like this when it reached SQSListener.

```
"""
                    "{"name":"kimjonghyun", "age":30}"
"""
```
Notice extra `"` before first `{` and after the last `}`. This causes issues and you get the exception you had.
