### ISSUE TITLE
Upgrade AWS SDK

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#724]
- Upgrade AWS SDK v2 to the latest version ([2.20.29](https://github.com/aws/aws-sdk-java-v2/releases/tag/2.20.29) at the time of creating this issue).

- Upgrade AWS SDK v1 to the latest version ([1.12.432](https://github.com/aws/aws-sdk-java/releases/tag/1.12.432) at the time of creating this issue).

Dependency versions are defined in https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-dependencies/pom.xml

The way to implement this change is to bump these versions, and run the build with tests to see if everything is working as expected.

**Comment by kunalvarpe** [comment]
Can I start here?

**Comment by maciejwalkowiak** [comment]
Sure!

**Comment by kunalvarpe** [comment]
Hi @maciejwalkowiak 

After upgrading the AWS SDK's, there is issue in the `S3CrtAsyncClientAutoConfigurationTests`. The private helper method `s3NativeClientConfiguration()` which obtained the `S3NativeClientConfiguration`  from the `CopyObjectHelper` class is failing with below error.

```java
java.lang.IllegalArgumentException: Could not find field 's3NativeClientConfiguration' on target object [software.amazon.awssdk.services.s3.internal.crt.CopyObjectHelper@4cb40e3b] or target class [class software.amazon.awssdk.services.s3.internal.crt.CopyObjectHelper]

	at org.springframework.test.util.ReflectionTestUtils.getField(ReflectionTestUtils.java:275)
	at org.springframework.test.util.ReflectionTestUtils.getField(ReflectionTestUtils.java:217)
	at io.awspring.cloud.autoconfigure.s3.S3CrtAsyncClientAutoConfigurationTests.s3NativeClientConfiguration(S3CrtAsyncClientAutoConfigurationTests.java:97)
	at io.awspring.cloud.autoconfigure.s3.S3CrtAsyncClientAutoConfigurationTests.lambda$setsPropertiesOnClient$0(S3CrtAsyncClientAutoConfigurationTests.java:87)
```

But in aws-sdk2 version 2.20.9 the `CopyObjectHelper` no longer have the instance of `S3NativeClientConfiguration`.  Below is difference between those two classes.

```diff
- public CopyObjectHelper(S3AsyncClient s3AsyncClient, S3NativeClientConfiguration s3NativeClientConfiguration)
+ public CopyObjectHelper(S3AsyncClient s3AsyncClient, long partSizeInBytes)
```

So we will not be able to get the native configuration and assert the properties which are set after auto configuration.
Can you give some pointer here how we tackle this?

**References** :
[AWS SDK S3 2.20.9 JavaDoc] (https://www.javadoc.io/doc/software.amazon.awssdk/s3/latest/index.html) 
[AWS SDK S3 2.19.25 JavaDoc] (https://www.javadoc.io/doc/software.amazon.awssdk/s3/2.19.25/index.html) 

Also Can I raise the draft pull request for this issue?

**Comment by maciejwalkowiak** [comment]
Not really, i guess it is somewhere else accessible with reflection but i don't know where.

**Comment by arunkpatra** [comment]
I think AWS SDK v2 (2.20.29) might be unstable. I see the bom has not been updated to the correct level of `aws-crt` which should have been bumped to `0.21.9` by AWS. I see that 2.20.31 is underway.

**Comment by kunalvarpe** [comment]
@maciejwalkowiak 
Yes indeed it was accessible on the `SdkAsyncHttpClient` on the delegate of the `S3AsyncClinet`. I have fixed the test. Also upgraded the AWS SDK V2 to *2.20.30* which was release latest version.

@arunkpatra You were saying that AWS SDK V2 (2.20.29) is not stable, where did you refere that from?

**Comment by arunkpatra** [comment]
@kunalvarpe I was building it today with 2.20.29 and was getting errors while running tests. It appeared that AWS did not update the aws-crt version to latest in the bom. I had to override the version of aws-crt to latest to make things work.
