### ISSUE TITLE
@RefreshScope in 3.0.0?

### ISSUE THREAD

**Issue by mikelhamer** [awspring/spring-cloud-aws#728]
As far as I know, the @RefreshScope annotation is in the spring-cloud-aws-context, but I don't see that existing in 3.0.0. Am I missing something?

https://mvnrepository.com/artifact/io.awspring.cloud/spring-cloud-aws-context

**Comment by maciejwalkowiak** [comment]
Refresh scope comes from Spring Cloud - the mother project. Spring Cloud AWS now reacts to refresh events in Parameter Store and Secrets Manager integrations

**Comment by mikelhamer** [comment]
Thanks! I am seeing an issue in that when I include Spring Cloud context and commons in my project alongside Spring Cloud AWS secrets manager without specifying the version in Spring Boot 2.7.6 and using spring-cloud-aws-dependencies to control versions, I get an error about incompatible Spring Boot version and have to explicitly downgrade the Spring Cloud dependencies to 3.1.5

**Comment by maciejwalkowiak** [comment]
Spring Cloud AWS 3.0 is compatible with Spring Boot 3.0. you probably can use it with 2.7 but expect the unexpected

**Comment by mikelhamer** [comment]
Ah, perhaps the intro docs are incorrect?

<img width="706" alt="image" src="https://user-images.githubusercontent.com/10012080/227155637-a0da105c-1dfa-4d39-bd62-0b3c28475918.png">


https://awspring.io/learn/introduction/

**Comment by maciejwalkowiak** [comment]
yes, the website is very outdated. it's either going to be re-built for 3.0 release or we will just redirect to Github repo. Apologies for confusion!

**Comment by mikelhamer** [comment]
Thanks for the speedy replies!
