### ISSUE TITLE
Include spring-cloud-aws-test in BOM for Spring Cloud AWS 3.X

### ISSUE THREAD

**Issue by rieckpil** [awspring/spring-cloud-aws#730]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**

As part of Spring Cloud AWS 2.4.X, the "new" `spring-cloud-aws-test` lib was part of the BOM. As of 3.0.0.RC1, it's missing, and when including the library, one has to explicitly add the version.

Was this a deliberate decision or maybe forgotten to copy?

**Describe the solution you'd like**

Include `spring-cloud-aws-test` in `spring-cloud-aws-dependencies`

**Describe alternatives you've considered**

As a workaround when upgrading to 3.X, I'm manually including the version like

```
<dependency>
  <groupId>io.awspring.cloud</groupId>
  <artifactId>spring-cloud-aws-test</artifactId>
  <version>3.0.0-RC1</version>
  <scope>test</scope>
</dependency>
```

**Additional context**

I'm happy to provide a PR if it was forgotten by accident 👍🏻

**Comment by maciejwalkowiak** [comment]
@rieckpil sorry, i'll do it now as I am preparing RC2 release
