### ISSUE TITLE
How can I set SNSTemplate to not auto create SNS Topics?

### ISSUE THREAD

**Issue by mikelhamer** [awspring/spring-cloud-aws#733]
If I try sending a notification to a Topic that doesn't exist, I'd like it error instead of creating it.

The docs mention defining this bean, but `TopicsListingTopicArnResolver` doesn't seem to exist.

``` java 
@Bean
public TopicArnResolver topicArnResolver(SnsClient snsClient) {
    return new TopicsListingTopicArnResolver(snsClient);
}
```

**Comment by maciejwalkowiak** [comment]
`TopicsListingTopicArnResolver` will be released in next iteration (RC2 coming soon). 

I do believe though that non existing topic is rather an edge case, and the application usually does not have permission to create topics so this **would** result in exception.

Listing topics on application adds an overhead, so ideally you don't need to use it. 

Unfortunately, both are hacky workarounds that compensate for missing bits in AWS SDK.
