### ISSUE TITLE
AWS_REGION is being ignored when using custom credentials provider

### ISSUE THREAD

**Issue by ddeath** [awspring/spring-cloud-aws#741]
**Type**: Bug

**Component**: S3,  SQS

**Describe the bug**
Our services are deployed in EKS where we are using  WebIdentityTokenCredentialsProvider as authentication method. Because of that we introduced these beans:
```java
@Bean
  @Primary
  public AmazonSQSAsync amazonSQSAsync() {
    return AmazonSQSAsyncClientBuilder.standard()
        .withCredentials(new WebIdentityTokenCredentialsProvider())
        .build();
  }

  @Bean
  @Primary
  public AmazonS3 getAmazonS3Client() {
    return AmazonS3ClientBuilder.standard()
        .withCredentials(new WebIdentityTokenCredentialsProvider())
        .build();
  }
```

They are needed because `WebIdentityTokenCredentialsProvider()` is not in default provider chain...
I wanted to refactor this a little bit by replacing beans above with this one:

```java
@Bean
  AWSCredentialsProvider getAwsCredentials() {
    return new WebIdentityTokenCredentialsProvider();
  }
```

However when I do that suddenly s3 client is trying to connect to `us-west-2` region instead of region provided in `AWS_REGION` env variable and same goes for SQS - I get just warnings that those queues are ignored as they do not exists....

I also tried to add this bean:
```java
@Primary
  @Bean
  AwsRegionProvider getAwsRegionProvider() {
    return new AwsSystemPropertyRegionProvider();
  }
```
But that does not help :/ 

I am using : `spring-cloud-starter-aws-messaging: 2.2.6-RELEASE`

**Comment by maciejwalkowiak** [comment]
Have you tried setting the region or region provider on the S3 client itself? 

S3 integration has been implemented in a way that it resolves the bucket from S3 URL: https://github.com/awspring/spring-cloud-aws/blob/2.4.x/spring-cloud-aws-core/src/main/java/io/awspring/cloud/core/io/s3/AmazonS3ClientFactory.java#L103

Perhaps you can try the latest version in 2.x, I am also pretty sure this issue does not happen in 3.0 but I realise you may not be able to upgrade as it requires Spring Boot 3 and Java 17.

If problem still exists in 2.4 I would appreciate if you can attach a sample that reproduces this issue as it would make it easier to find the bug and fix it.

Also, feel free to drop a PR with a fix.

**Comment by ddeath** [comment]
Hi, I will try but so far it is not easy 😄 
One thing which I noticed is that I am using different lib - from different repo:
```
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-aws-messaging</artifactId>
      <version>${spring-cloud-version}</version>
    </dependency>
```

Which is older version I guess....

Migrating to lib from this repo is not easy as some components are just missing, it is not 1 to 1 replacement....

I noticed that more issues has potentially same issue - they think they are using this repo lib but actually they are using `org.springframework.cloud` - it could be kind of see from people being confused a lot of time when you suggest to try 2.x version... because we are using 2.x version of `org.springframework.cloud`

**Comment by maciejwalkowiak** [comment]
It's the same project, just moved to a new organisation. 2.2.6 is an extremely old release. We use `org.springframework.cloud` but this points to a mother project - Spring Cloud. Once migrated to 2.4, you should NOT use `org.springframework.cloud.aws` anymore.

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback. If the problem still exists, please comment and we can re-open.
