### ISSUE TITLE
SQS message attributes mapping fails when using custom data type

### ISSUE THREAD

**Issue by npoirier** [awspring/spring-cloud-aws#745]
**Type**: Bug

**Component**:
SQS message attribute mapping

**Describe the bug**

Mapping of SQS message attributes fails when using a  type other than Number with a custom data type.  ex: `String.Json` or `Binary.Protobuf`.

In `SqsHeaderMapper.getMessageAttributesAsHeaders()` it defaults to Number and then fails to parse the value:

```
	private Object getValue(Map.Entry<String, MessageAttributeValue> entry) {
		MessageAttributeValue value = entry.getValue();
		String dataType = value.dataType();
		Assert.notNull(dataType, "dataType must not be null");
		return MessageAttributeDataTypes.STRING.equals(dataType)
			? value.stringValue()
			: MessageAttributeDataTypes.BINARY.equals(dataType)
				? value.binaryValue()
				: getNumberValue(value);
	}
```

Custom data types : https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-metadata.html#sqs-message-attributes

**Comment by tomazfernandes** [comment]
Fixed by #746
