### ISSUE TITLE
S3Resource#getFilename() returns null

### ISSUE THREAD

**Issue by vedgunjan** [awspring/spring-cloud-aws#748]
Type: Bug

Component:
S3Resource#getFilename() returns null

Describe the bug
As discussed in #688 

When using the library version 3.0.0-RC1 within the spring batch application and converting S3Resource Object to [Spring io.Resource](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/Resource.html) for passing it to FlatFileItemReader, we run into NPE as S3Resource#getFilename() is not implemented and it returns null. The exception is thrown when compareTo() api is called.

**Comment by maciejwalkowiak** [comment]
@vedgunjan I'm waiting for a PR! Does not need to be perfect, do the best you can and we will polish it together.

**Comment by vedgunjan** [comment]
Hi @maciejwalkowiak 
Here's the PR for the fix : https://github.com/awspring/spring-cloud-aws/pull/750
