### ISSUE TITLE
SES docs are outdated

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#749]
SES docs suggest using `javax.mail` which is not going to work since the package moved to Jakarta namespace

- https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-RC2/reference/html/index.html#sending-attachments

More context: https://github.com/awspring/spring-cloud-aws/issues/743

**Comment by arunkpatra** [comment]
@maciejwalkowiak I'll update the docs
