### ISSUE TITLE
RC2 - DefaultTopicArnResolver - violates "least privilege IAM policy" best practice

### ISSUE THREAD

**Issue by jkatnik** [awspring/spring-cloud-aws#753]
**Type**: Bug

**Component**:  Choose "SNS", "IAM"

**Version**: 3.0.0-RC2

**Describe the bug**
DefaultTopicArnResolver, when provided with a topic name rather than ARN, tries to create a topic assuming that this operation is idempotent. This is wrong because the application accordingly to the "least privilege IAM policy" rule should not be granted to do it. From a security perspective, the app should rather list available topics and search for ARN ending with `":" + topicName`.

**Sample**

**Comment by maciejwalkowiak** [comment]
We have also `TopicsListingTopicArnResolver`, but the downside of using it is that it adds more to the startup time.

https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-RC2/reference/html/index.html#sns-template

**Comment by jkatnik** [comment]
Hi @maciejwalkowiak 

thanks for pointing me to that resolver. I missed it, however, it contains a bug. I've described it and fixed in this PR: https://github.com/awspring/spring-cloud-aws/pull/756

Please feel free to close this issue.
