### ISSUE TITLE
Upgrade to Testcontainers 1.18.0

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#754]
https://github.com/testcontainers/testcontainers-java/releases/tag/1.18.0

This includes removing the list of services to start when starting Localstack container.

It may also include upgrading to Localstack v2 - but I am not sure how much changes it would require on our side so lets keep it optional.

**Comment by sbouhaddi** [comment]
Hello,
I can take This one

**Comment by Harsh4902** [comment]
@sbouhaddi can I collaborate with you?

**Comment by sbouhaddi** [comment]
@Harsh4902 let me check first if the task needs more then one person efforts then i will get back to you

**Comment by Harsh4902** [comment]
Sure, thank you

**Comment by rajadilipkolli** [comment]
> @Harsh4902 let me check first if the task needs more then one person efforts then i will get back to you

You need to remove awssdk v1 version dependency as well as localstack 2 is compatible with awssdk 2  only.

**Comment by sbouhaddi** [comment]
> > @Harsh4902 let me check first if the task needs more then one person efforts then i will get back to you
> 
> You need to remove awssdk v1 version dependency as well as localstack 2 is compatible with awssdk 2 only.

Yes will do, i will check that today

**Comment by MatejNedic** [comment]
Closed by #755
