### ISSUE TITLE
Add Acknowledgement Mode to @SqsListener Annotation

### ISSUE THREAD

**Issue by oleksandr-skoryi** [awspring/spring-cloud-aws#761]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
I am using spring boot 3, the V2 SqsListener simply doesn't work, I have to migrate to V3 SqsListener
The V2 lib has the following declaration of the SqsListener
```
  @SqsListener(
      value = "${queue.name}",
      deletionPolicy = SqsMessageDeletionPolicy.ON_SUCCESS)
```
The same annotation in V3 library doesn't have deletionPolicy
**Describe the solution you'd like**
I would like to have it there, or having alternative.

**Describe alternatives you've considered**
Currently do @Scheduled annotation and manual polling

**Comment by maciejwalkowiak** [comment]
Message deletion in v3 is done through "acknowledging": https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#acknowledging-messages

Perhaps we can bring the acknowledge option to the annotation itself? @tomazfernandes

**Comment by oleksandr-skoryi** [comment]
> https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#acknowledging-messages

But it is a global configuration, what about making it more granular, per SqsListener?

**Comment by tomazfernandes** [comment]
> But it is a global configuration, isn't it? What about making it more granular, per SqsListener?

You can configure different acknowledgement strategies for different factories, and specify the factory you want to use in the `@SqsListener` annotation.

> Perhaps we can bring the acknowledge option to the annotation itself? @tomazfernandes

Yeah, we can look into that. I may be wrong, but I believe the main reason this was in the annotation in 2.x is that given you could not configure separate factories for each annotation any customization had to be in the annotation itself.

**Comment by tomazfernandes** [comment]
I guess you edited your comment about the same time I was writing mine.

> And for the 99% of cases, dev doesn't care about other options except acknowledgment type

3.0 has a lot of other configurations available that might be interesting. For example, for acknowledgement you can define whether to batch acks or not, the thresholds to acknowledge a batch, etc. But yeah, maybe that's a more advanced topic that most users might not look into.

> I think the V2 lib users are also got used to it.

I think this is a good point.

**Comment by iparadiso** [comment]
I would +1 on having support in the annotation.  This is a very widely used deletion policy parameter.  While the factory route technically opens up a lot more flexibility, it also adds quire a lot more boilerplate.  If there are generic factory deletion policies users can reference in the library to prevent rewriting the wheel over and over,  that would also be an agreeable solution to me.

**Comment by tomazfernandes** [comment]
I agree users coming from 2.x will probably miss the annotation route. Given this has a simple workaround and our time constraints I think it should be ok to include it in 3.1 rather than 3.0 though. Does that sound ok?

**Comment by tomazfernandes** [comment]
Hey @iparadiso, now that 3.0 is out, would you like to contribute a PR with this feature?

Thanks

**Comment by rl1m4** [comment]
Hi @tomazfernandes ,
I didn't find in this [acknowledging docs](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#acknowledging-messages) how to set received messages to not be automatically deleted from a queue after they have been processed by the listener. eg: previous way: deletionPolicy = SqsMessageDeletionPolicy.NEVER, how do I use the acknowledging to set something similar?

**Comment by tomazfernandes** [comment]
Hey @rl1m4, that's the same as setting `AcknowledgementMode.MANUAL` as per the docs.

We're missing a proper migration guide, sorry about that.

Let me know if you have any further questions.

**Comment by jvcalassio** [comment]
Hey @tomazfernandes. 

I'd like to contribute with this feature. I'll send a PR soon

**Comment by agustin-vieta** [comment]
hi @tomazfernandes. You mention this
> You can configure different acknowledgement strategies for different factories, and specify the factory you want to use in the @SqsListener annotation.

But I can't figure it out how to do it, where I can find more information about it?

**Comment by ariekiswanto** [comment]
Hi,
if I am gonna use simple `@SqsListener` annotation leveraging auto-configuration by Spring Boot what is the `acknowledgementMode` that will be used as default?

**Comment by tomazfernandes** [comment]
@agustin-vieta , let me know if this helps:
https://docs.awspring.io/spring-cloud-aws/docs/3.0.2/reference/html/index.html#specifying-a-messagelistenercontainerfactory

**Comment by tomazfernandes** [comment]
> if I am gonna use simple @SqsListener annotation leveraging auto-configuration by Spring Boot what is the acknowledgementMode that will be used as default?

[Default acknowledgement mode](https://docs.awspring.io/spring-cloud-aws/docs/3.0.2/reference/html/index.html#sqscontaineroptions-descriptions) is `ON_SUCCESS`
