### ISSUE TITLE
'The AWS Access Key Id you provided does not exist in our records' when using S3 resource

### ISSUE THREAD

**Issue by kylecdrck** [awspring/spring-cloud-aws#763]
I'm currently using Spring Boot 3.0.5 with AWS Spring 3.0.0-RC2. Migrated from spring boot 2.7.x and aws spring 2.x

I'm trying to read an S3 object as Resource via `resource.getInputStream()` but I am getting the error `The AWS Access Key Id you provided does not exist in our records`

I already set the access and secret keys and region via property

```
spring.cloud.aws.credentials.access-key=X
spring.cloud.aws.credentials.secret-key=Y
spring.cloud.aws.region.static=ap-southeast-1
```

I tried manually retrieving the file via AWS SDK 2.x `S3Client` and `GetObjectRequest`. I created an `AwsBasicCredentials` with the same keys and it returned the same error. When I created instead a `AwsSessionCredentials` with a session token, the action proceeded. 

How can I replicate the handling of the session credential in aws spring s3?

**Comment by maciejwalkowiak** [comment]
Take a look at documentation: https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#credentials

If you don't set access key and secret key, the default credentials provider will be used that includes the Web Identity Token provider.

If you need something more custom, you can create your own `AwsCredentialsProvider` bean. 

Let me know if it helps

**Comment by kylecdrck** [comment]
Got it. I think I had a misunderstanding on my end. It's already working now. Thank you

**Comment by maciejwalkowiak** [comment]
Awsesome!

**Comment by oyee91** [comment]
> Got it. I think I had a misunderstanding on my end. It's already working now. Thank you

How did you solve it?
