### ISSUE TITLE
AutoConfiguration for AWS DynamoDB

### ISSUE THREAD

**Issue by dz-adman** [awspring/spring-cloud-aws#764]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
While using the Spring Cloud AWS project, I noticed that there is no autoconfiguration support for AWS DynamoDB. This makes setting up and configuring DynamoDB in Spring Boot applications more complex than it could be with autoconfiguration.

**Describe the solution you'd like**
I propose adding autoconfiguration support for AWS DynamoDB to simplify the process of integrating DynamoDB in Spring Boot applications. I have already implemented this feature in my personal repository, which you can review here:
[aws-dynamodb-autoconfiguration](https://github.com/dz-adman/dynamodb-autoconfiguration)

**Describe alternatives you've considered**
An alternative would be to manually configure DynamoDB in each Spring Boot application, but this can be time-consuming and error-prone. Autoconfiguration would streamline this process and improve the developer experience.

**Additional context**
I would like to contribute this feature to the main project and submit a pull request if the maintainers are interested in having this feature in the repository. Please let me know if you have any suggestions or guidelines for submitting a pull request. Thank you for your time and consideration!

**Comment by maciejwalkowiak** [comment]
Have you had a look at https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-RC2/reference/html/index.html#spring-cloud-aws-dynamoDb ?

**Comment by dz-adman** [comment]
@maciejwalkowiak my bad.
Thanks for pointing out the existing ```amazon-dax-client``` for DynamoDB. I apologize for overlooking it before creating this issue. I appreciate your help in directing me to the correct implementation.

Since the feature I proposed is already available, we can close this issue. If I find any improvements or additional features related to DynamoDB autoconfiguration in the future, I will create a new issue or submit a pull request.

Thanks again!

**Comment by maciejwalkowiak** [comment]
No need to apologize! If you come up with any ideas and PRs we're happy to take a look!
