### ISSUE TITLE
Introduce SES sample once SES is migrated to AWS SDK v2

### ISSUE THREAD

**Issue by MatejNedic** [awspring/spring-cloud-aws#77]
Since there is no SES sample for 2.3.x branch it could be a good thing once #59 is done to introduce SES sample. This can be a good first issue. Spring Cloud AWS sample [module](https://github.com/awspring/spring-cloud-aws/tree/2.3.x/spring-cloud-aws-samples) can be used as a reference for creating SES sample.

**Comment by arunkpatra** [comment]
@MatejNedic @maciejwalkowiak Let me pick this up once I'm done with #59 if its ok with you.

**Comment by arunkpatra** [comment]
I'm considering creating this sample inside `V3` module. `v3/spring-cloud-aws-v3-samples/spring-cloud-aws-v3-ses-sample`. I'm assuming that all `V3` modules once done will replace the existing ones in a major refactoring effort en-masse.

**Comment by arunkpatra** [comment]
Once #84 is merged, I can take this up.
