### ISSUE TITLE
CloudWatchRegistryProperties has wrong configuration prefix

### ISSUE THREAD

**Issue by thake** [awspring/spring-cloud-aws#776]
**Type**: Bug

**Component**:
Autoconfigure Cloudwatch 

**Describe the bug**
With spring boot 3, the configuration prefixes for metric provider have been changed (see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#actuator-metrics-export-properties). I expect that io.awspring.cloud.autoconfigure.metrics.CloudWatchRegistryProperties would follow the same rule for configuration prefixes. This is currently (3.0.0-RC2) not the case. It still uses `management.metrics.export.cloudwatch`. It should be `management.cloudwatch.metrics.export`.

**Comment by maciejwalkowiak** [comment]
Thanks! Would you like to submit a PR?

**Comment by thake** [comment]
Sure, I'll give it a try.
