### ISSUE TITLE
[Question]: What is the recommended approach for using Lambda?

### ISSUE THREAD

**Issue by mikelhamer** [awspring/spring-cloud-aws#790]
**Type**: Question

I don't see a `spring-cloud-aws-starter-lambda` project, and am wondering, what is the recommended way to integrate Lambda that is compatible with Spring Cloud AWS 3.x?

**Comment by maciejwalkowiak** [comment]
Which integration specifically do you have in mind? Have you had a look at https://github.com/spring-cloud/spring-cloud-function?

Let me convert this issue to discussion
