### ISSUE TITLE
CrossRegionS3Client doesn't implement utilities()

### ISSUE THREAD

**Issue by cbreezier** [awspring/spring-cloud-aws#794]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
Unable to get resource url when using `CrossRegionS3Client`.

The "correct" way to do this appears to be `client.utilities().getUrl(...)`, however the `utilities()` method is not implemented on `CrossRegionS3Client`.

**Describe the solution you'd like**
Implement `utilities()` on the `CrossRegionS3Client`.

**Describe alternatives you've considered**
Avoid using the `CrossRegionS3Client` and use the `DefaultS3Client` instead. However, `spring-cloud-aws-autoconfigure:3.0.0-RC2` configures `CrossRegionS3Client` by default.

Edit: and `spring-cloud-aws-starter-s3` includes `spring-cloud-aws-s3-cross-region-client` and `autoconfigure` by default.

**Additional context**
None.

**Comment by maciejwalkowiak** [comment]
@cbreezier PR submitted, but utilities won't work in cross-region manner. The hope is that cross region S3 support finally comes in AWS SDK: https://github.com/aws/aws-sdk-java-v2/pull/3937
