### ISSUE TITLE
SqsTemplate uses randomUUID breaking Fifo deduplication functionality

### ISSUE THREAD

**Issue by jwilmoth-nc** [awspring/spring-cloud-aws#796]
**Type**: Bug

**Component**: SQS

**Describe the bug**
The [SqsTemplate.addMissingFifoSendHeaders](https://github.com/awspring/spring-cloud-aws/blob/a09341d15fd163cb6779e168649cce1a3c963f32/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/operations/SqsTemplate.java#L258-L263) method adds a random UUID deduplication ID which results in Fifo Queues that have the `ContentBasedDeduplication` attribute set to true to not behave as expected, delivering the same content multiple times vs. deduplicating. 

**Sample**
With a SQS queue configured for content based deduplication the following code will result in two messages being delivered when only 1 is expected.

```
String identicalPayload = "test";
queueMessagingTemplate.send(
        to ->
            to.queue("content-deduping-queue")
                .messageGroupId("default-message-group")
                .payload(identicalPayload));

queueMessagingTemplate.send(
        to ->
            to.queue("content-deduping-queue")
                .messageGroupId("default-message-group")
                .payload(identicalPayload));
```

**Comment by tomazfernandes** [comment]
Thanks for reporting @jwilmoth-nc!

Would you like to contribute a PR with a fix?

**Comment by jwilmoth-nc** [comment]
@tomazfernandes is it ok to simply remove the header default deduplication ID when it's not specified?

**Comment by tomazfernandes** [comment]
I'm not so sure about this one - it'd break existing functionality.

I think the simplest way to fix this is having a `SqsTemplateOption` such as a boolean `addMissingFifoHeaders` which defaults to `true`. In some upcoming version we can change the default to `false`.

Or instead we might have a `setFifoQueueHeaderFunction` in the options, which users could use to override the original logic with anything they'd like for `FIFO` queues. But I think this solution might overcomplicate things for not so much benefit.

What do you think?

@maciejwalkowiak and @MatejNedic, feel free to pitch in if you'd like.

**Comment by maciejwalkowiak** [comment]
> I think the simplest way to fix this is having a SqsTemplateOption such as a boolean addMissingFifoHeaders which defaults to true. In some upcoming version we can change the default to false.

I think the current behavior can be considered as a bug as there's no way to opt out from it right? In such case i think we can add such option and set it by default to false. It is somewhat a breaking change but since it's changing a buggy behavior I think it's fine to release such change in 3.0.1

**Comment by jwilmoth-nc** [comment]
It seems odd that AWS requires the dedup id header if the queue is NOT configured for content based deduplication (`If you don't provide a MessageDeduplicationId and the queue doesn't have ContentBasedDeduplication set, the action fails with an error.`), but I have confirm it is as the docs say.  So, I think the solution might be to enable configuration that indicates if content based deduplication is set or not and react as follows:

- if content based deduplication is not set AND fifo -> add random UUID
- if content based deduplication is set AND fifo AND deduplication ID present -> use provided deduplication ID
- if content based deduplication is set AND fifo AND deduplication ID not present -> do not add header

The additional configuration in the template that it's using a content based deduplication queue is redundant to the actual queue configuration and could be error prone, so alternatively the template could use the client to get the queue attributes to determine if the queue has the `ContentBasedDeduplication` attribute set to true, eliminating the need to add additional config.  This would need to be cached to avoid unnecessary overhead.  The lookup could be done at initialization or lazily, not sure what would be preferable.

**Comment by tomazfernandes** [comment]
> Looking further, there's already a `queueAttributesCache` which is lazy loaded per `endpointName`, so I'm inclined to automatically add the `ContentBasedDeduplication` to `getQueueAttributes` and use it instead of adding additional config which may be out-of-sync w/ the actual queue definition.

Sounds great! Thanks!

> It seems odd that AWS requires the dedup id header if the queue is NOT configured for content based deduplication

Yeah, I think the point is always having a way to dedup messages, if it's not content-based then the user has to inform one.


> * if content based deduplication is not set AND fifo -> add random UUID
> * if content based deduplication is set AND fifo AND deduplication ID present -> use provided deduplication ID
> * if content based deduplication is set AND fifo AND deduplication ID not present -> do not add header

Maybe:

* if content based deduplication is not set AND deduplication ID not present AND fifo -> add random UUID
* if content based deduplication is not set AND deduplication ID present AND fifo -> use user provided dedup ID

Right? Or am I missing something?

> The additional configuration in the template that it's using a content based deduplication queue is redundant to the actual queue configuration and could be error prone, so alternatively the template could use the client to get the queue attributes to determine if the queue has the `ContentBasedDeduplication` attribute set to true, eliminating the need to add additional config. This would need to be cached to avoid unnecessary overhead. The lookup could be done at initialization or lazily, not sure what would be preferable.

Yup, already there!

**Comment by maciejwalkowiak** [comment]
@tomazfernandes sounds good to me

**Comment by jwilmoth-nc** [comment]
@tomazfernandes my user doesn't have permissions to push a feature branch to this repo.  How would you like the change + tests update?

**Comment by tomazfernandes** [comment]
Hey @jwilmoth-nc, you should fork the project and push to a branch in your own fork, then create a PR for this project.

GitHub should help you do that - I’m not sure if we have any guide, but let me know if you have any problems.

**Comment by jwilmoth-nc** [comment]
Opened https://github.com/awspring/spring-cloud-aws/pull/799
