### ISSUE TITLE
version 3.0.0 has not been published yet

### ISSUE THREAD

**Issue by niels1voo** [awspring/spring-cloud-aws#797]
Version 3.0.0 has been "released" but has not been published to sonatype yet.

**Comment by poklakni** [comment]
I am using it already @niels1voo

**Comment by maciejwalkowiak** [comment]
@niels1voo we did publish it to Maven central. Can you be more specific about your issue? Perhaps we missed something

**Comment by niels1voo** [comment]
I should have been more specific.
I'm specifically looking for version 3.0.0 of spring-cloud-starter-aws-parameter-store-config

our gradle/libs.versions.toml:
[versions]
spring-cloud-aws = '3.0.0'
[libs]
awspring-cloud-bom = { module = 'io.awspring.cloud:spring-cloud-aws-dependencies', version.ref = 'spring-cloud-aws' }
awspring-cloud-aws-autoconfigure = { module = 'io.awspring.cloud:spring-cloud-aws-autoconfigure' }
awspring-cloud-starter-parameterstore = { module = 'io.awspring.cloud:spring-cloud-starter-aws-parameter-store-config' }

our build.gradle
runtimeOnly platform(libs.awspring.cloud.bom)
runtimeOnly libs.awspring.cloud.aws.autoconfigure
runtimeOnly libs.awspring.cloud.starter.parameterstore

when 
spring-cloud-aws = '2.4.4' it finds the dependency
when
spring-cloud-aws = '3.0.0' it does not

> Could not resolve all task dependencies for configuration ':helium-app:runtimeClasspath'.
   > Could not find io.awspring.cloud:spring-cloud-starter-aws-parameter-store-config:.

I searched on the sonatype repo referenced in your pom and did not find version 3.0.0 of spring-cloud-starter-aws-parameter-store-config
https://oss.sonatype.org/#nexus-search;quick~spring-cloud-starter-aws-parameter-store-config

**Comment by MatejNedic** [comment]
It is a major version upgrade that was mostly a rewrite of an old Spring Cloud AWS. I would expect changes like this to happen, if you consider what was done, also we aligned the namings to follow the same pattern as other Spring integrations (such as spring cloud gcp for example).

We can specify it within a readme that name of artifact has changed.

**Comment by maciejwalkowiak** [comment]
@niels1voo unfortunately we did not manage to write proper migration guide so for the moment as @MatejNedic wrote, please take a look into reference docs.
