### ISSUE TITLE
Parameter Store - Property Source reload does not detect newly added properties.

### ISSUE THREAD

**Issue by griffygruffy** [awspring/spring-cloud-aws#803]
**Type**: Bug

**Component**:
Parameter Store

**Describe the bug**
PollingAwsPropertySourceChangeDetector does not detect new properties added to the AWS Parameter Store (modify/delete of existing properties works as expected).
ConfigurationChangeDetector.changed method only checks if the values of existing property names have changed. It should also return true if the "left.getPropertyNames()" is not equal to the "right.getPropertyNames()". Assuming the order of the property names is consistent then can use something like:
```
if (Arrays.equals(left.getPropertyNames(),right.getPropertyNames()){
   return true;
}
```

awspring: 3.0.0-RC2
springCloud: 4.0.1

**Sample**
Start up an application with the refresh config. Add a new property to AWS Param Store. PollingAWSPropertySourceChangeDetector should detect the change and refresh the context.

**Comment by MatejNedic** [comment]
Hey @griffygruffy ,

Thank you on reporting, would you like to contribute and make a PR?

**Comment by maciejwalkowiak** [comment]
FYI Secrets Manager is not affected.

**Comment by griffygruffy** [comment]
Wow guys, I was coming back on here to submit the PR, to find its been fixed already. Not only that, its already available in a release. Amazing, thanks very much @maciejwalkowiak!
