### ISSUE TITLE
FIFO queues support does not guarantee FIFO order

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#81]
Under the hood, SQS integration uses `AmazonSQSBufferedAsyncClient` to reduce amount of requests sent to AWS and same time reduce the costs. Unfortunately, [it does not support FIFO queues](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-client-side-buffering-request-batching.html). 

Ideally in case of FIFO queue we should fall back to regular SQS client.

**Comment by tekener** [comment]
Because you are already planning to move forward to AWS SDK V2 you could also do the quick fix by just using the unbuffered client for everything. 🤔 That would be a quick fix and i think a little quickness is needed because else the people are blocked to update Spring Boot to 2.4 🙈 Sorry, to pressure here 😂

**Comment by tekener** [comment]
Hi @maciejwalkowiak, i don't think that updating the docs is a solution for this. At least you should then do an argument check when somebody is using a fifo queue with the AmazonSQSBufferedAsyncClient.

**Comment by maciejwalkowiak** [comment]
@tekener it is a better temporary solution than dropping buffered client completely and risking our users getting surprise bills from AWS. You are welcome to contribute a proper fix for this 🙂

**Comment by tekener** [comment]
@maciejwalkowiak if you want i can create a PR with the assertion as a kind of fix.
Did you introduce the AmazonSQSBufferedAsyncClient with 2.3.x or was this client there before?

**Comment by maciejwalkowiak** [comment]
Buffered client was there already. 

If you have a good solution in mind with the assertion (it should be warning log though, not something preventing app from starting) please go ahead.

**Comment by tekener** [comment]
Hi @maciejwalkowiak have a look at my PR please

**Comment by eddumelendez** [comment]
I think for now is good to add documentation and highlight during the release notes. Just throwing an idea, it would be great to specify queue type with support for STANDARD (DEFAULT) and FIFO and use the proper implementation behind.
