### ISSUE TITLE
Parameters not found

### ISSUE THREAD

**Issue by penunes** [awspring/spring-cloud-aws#813]
**Type**: Bug

**Component**: Parameter Store

**Describe the bug**
The latest version of class ParameterStorePropertySources does not handle exception properly, for example if the credentials used to request parameter has not suitable policies the message received is that the parameter was not found
```
Description:

Config data resource '[ParameterStoreConfigDataResource@198c7a4b context = '/config/app', optional = false]' via location 'aws-parameterstore:/config/app' does not exist

Action:

Check that the value 'aws-parameterstore:/config/app' is correct, or prefix it with 'optional:'
```

**Sample**
To reproduce this issue please create a user and a parameter on aws console, set suitable policies to user. Create a simple project with dependencies:
```
spring-cloud-starter-bootstrap
spring-cloud-aws-autoconfigure
spring-cloud-aws-starter
spring-cloud-aws-starter-parameter-store
```
On application.yml configure spring.config.import and spring.cloud.aws.region.static keys.
Run the application and the message "...does not exist" comes up.

Using localstack this issues does not happen.

I think that could be cool if the exception reflects the main reason for missing key, permissions or whatever other reason.

There are a strange behavior while debugging application on this scenario, if you put a breakpoint at ParameterStorePropertySource.getParameters line 80 sometimes is able to retrieve the parameter, but this behavior is intermittent

**Comment by maciejwalkowiak** [comment]
@penunes thanks for reporting. I remember we did improve error handling but perhaps there's still space to make it better. Would you like to dig deeper and contribute a PR?

**Comment by penunes** [comment]
Wow! @maciejwalkowiak It will be an honor to contribute with a PR for the project.

**Comment by ascopes** [comment]
is there any update on this one? This'd be super valuable as it is a bit of a nightmare at the moment when using cloud systems and having to redeploy with a bunch of debug flags to trace through exactly what is going on with this 😅

**Comment by penunes** [comment]
Sorry guys! I had a lot of problems in the meanwhile. Indeed this is not an issue. In my case I found out what was wrong when creating a class that implements FailureAnalysisReporter interface. The interface FailureAnalysisReporter is responsible for display the infamous message APPLICATION FAILED TO START with a poor description, you can improve the message with more details using FailureAnalysis object, this object contains a Throwable object which I think can put light on issues.

In my case the problem was related to a SecurityGroup configuration that was blocking the communication between my instance with ssm
