### ISSUE TITLE
Support SqsListener true/false autoStartup

### ISSUE THREAD

**Issue by JevgeniaB** [awspring/spring-cloud-aws#818]
**Type**: Feature update

**Is your feature request related to a problem? Please describe.**
I have encountered the issue when i need @SqsListener bean to be initialized but not process messages automatically. I use spring-cloud-aws-sqs version 3.0.1, but autoStartup is set to be always true, so no option to choose false. The problem is that this behavior is not preferable.

**Describe the solution you'd like**
Could be good to have the opportunity to choose true/false autoStartup

**Describe alternatives you've considered**
1. I checked the SmartLifecycle#isAutoStartup, but it is also true by default
2. I also checked if any factory can be used, and the only factory that includes configurable autoStartup is io.awspring.cloud.messaging.config.SimpleMessageListenerContainerFactory, but i use 
io.awspring.cloud.sqs.config.sqsMessageListenerContainerFactory that lacks autoStartup configuration

**Additional context**
I have found that this topic was already raised recently, but the new issue was not created.
https://github.com/awspring/spring-cloud-aws/issues/723

**Comment by tomazfernandes** [comment]
Hi @JevgeniaB, thanks for bringing this up and opening the issue.

Would you like to contribute a PR with this feature?

Thanks.

**Comment by tomazfernandes** [comment]
Closed by https://github.com/awspring/spring-cloud-aws/pull/827.

**Comment by tomazfernandes** [comment]
Closed by https://github.com/awspring/spring-cloud-aws/pull/827.
