### ISSUE TITLE
Allow override to returned sqs endpoint url 

### ISSUE THREAD

**Issue by mam8270** [awspring/spring-cloud-aws#822]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
In the old SQS handler, I could extend "DynamicQueueUrlDestinationResolver" to override the returned sqs url. I was looking for an equivalent in the new sqs v3 code. The use case is we run an internal service mesh which handles ssl , so we would like to call within our app to sqs on a http url (which the service mesh would upshift to https with instrumentation). There is no clear way to override the returned url from the sqs api in the current code that i could find.

**Describe the solution you'd like**
 Would like either documented or added a mechanism to override the returned sqs url

**Describe alternatives you've considered**
I have looked through the source code and documentation and looked for a potential solution to this problem without luck

**Additional context**
If this feature is available, apologies. I would instead suggest then an update the documentation

**Comment by tomazfernandes** [comment]
Hi @mam8270, thanks for bringing this up.

This looks interesting, can you clarify the use case a bit more please?

First thing that comes to mind is - can't you specify the http url instead of the queue name? Or is it something that needs to be done dynamically at runtime?

I've never used such an internal service mesh, so if you can provide some more details or a step-by-step of how you'd like this to work it'd be great.

Thanks.

**Comment by mam8270** [comment]
Hey @tomazfernandes  , thanks for your work on the new version. A lot of the library changes are awesome!

I actually didn't realize we could pass the raw queue url to sqs listener . I tested your suggestion out and seems to work, and will solve the problem.  I might recommend updating the docs though. It also might be helpful in the future to consider allowing the library user to be able to set their own subclassed version of QueueAttributesResolver via config so the end user has the option to modify some of the behavior there.  Anyway, thanks for your prompt response and your work on the library.

**Comment by tomazfernandes** [comment]
>Hey @tomazfernandes , thanks for your work on the new version. A lot of the library changes are awesome!

Thanks for the feedback @mam8270! I'm really glad you're enjoying the changes.

>I actually didn't realize we could pass the raw queue url to sqs listener. I tested your suggestion out and seems to work, and will solve the problem. I might recommend updating the docs though.

Sure, would you like to open a PR with the change you have in mind? That would help a lot.

> It also might be helpful in the future to consider allowing the library user to be able to set their own subclassed version of QueueAttributesResolver via config so the end user has the option to modify some of the behavior there. Anyway, thanks for your prompt response and your work on the library.

That's a good idea. Again, PRs are very welcome.

Thanks!

**Comment by tomazfernandes** [comment]
@mam8270, I'll close this issue as it seems your problem was solved, but we can reopen it if you want to look into creating those PRs or anything else.

Thanks.
