### ISSUE TITLE
Spring Cloud AWS Messaging > 3.0

### ISSUE THREAD

**Issue by rl1m4** [awspring/spring-cloud-aws#825]
**Type**: Spring Cloud AWS Messaging > 3.0

**Is your feature request related to a problem? Please describe.**
According to the Spring blog post published on May 2, 2023 (link: https://spring.io/blog/2023/05/02/announcing-spring-cloud-aws-3-0-0), the new version of Spring Cloud AWS, version 3.0.0, has been announced.

However, it appears that the messaging dependency for version 3.0.0 is currently unavailable in the Maven repository (link: https://mvnrepository.com/artifact/io.awspring.cloud/spring-cloud-aws-messaging).

I am interested in knowing the ETA for the messaging dependency to be available. At the moment we are having problems trying to upgrade services that require the messaging dependencies.

**Describe the solution you'd like**
Be able to use AWS Messaging > 3.0 because this is the only way to update services using JDK17, Spring 6 and Spring Boot 3.
io.awspring.cloud:spring-cloud-aws-messaging:3.0.0

**Describe alternatives you've considered**
This is a blocker. There is no alternative

**Additional context**

**Comment by neiljbrown** [comment]
Hi @rl1m4, as part of the changes made for Spring Cloud AWS 3.0, the spring-cloud-aws-messaging module has been replaced with two separate modules supporting SQS and SNS integrations. There are corresponding libraries and starter dependencies for each. The starter dependencies are documented in the 3.0 reference guide - https://docs.awspring.io/spring-cloud-aws/docs/3.0.0/reference/html/index.html#getting-started. 

Neil.

**Comment by rl1m4** [comment]
Thank you for the prompted answer. Cheers

**Comment by maciejwalkowiak** [comment]
@rl1m4 unfortunately we did not manage to provide a list of breaking changes and a migration guide. 3.0 in terms of SQS is like a new framework, so I would recommend really going through the new reference docs in details.
