### ISSUE TITLE
Parameter store names need hyphens : KEY5 must have a hyphen if "/KEY1/KEY5" must be retrieved by ${KEY1.KEY5}

### ISSUE THREAD

**Issue by AshwiniV-PhilipsAccount** [awspring/spring-cloud-aws#830]
**Type**: Bug

**Component**:
"Parameter Store"

**Describe the bug**
We are facing an issue while fetching the parameters from the AWS parameter store within Spring application properties.
Artifacts:

- Spring Boot version : `2.6.3`
- Spring cloud for AWS parameter store config : 
`'io.awspring.cloud:spring-cloud-starter-aws-parameter-store-config:2.4.4'`

Please help us with information on the below. We tried retrieving the parameters in the Spring Boot app using the AWS SDK library and then it worked for all use cases.               However, we are looking for a way to retrieve the parameters from the AWS parameters store using application properties. Happy to know that Spring cloud supports this! But as we are facing the below issues, kindly provide the information on the reason for this / how we can get this to succeed.

### ISSUE 1

**Details**

1. Error when the parameter store name hierarchy has **no hyphen** (KEY5) in the last level and we are trying ${KEY1.KEY5}. If we have 2 parameters /sample-application/KEY1/KEY5 and /sample-application/KEY2/KEY5, then we can only import /sample-application and then retrieve ${KEY1.KEY5} and ${KEY2.KEY5}. But if KEY5 is not having atleast 1 hyphen ("-"), then it fails:

Spring application.properties:
```yaml
spring:
  config:
    import: aws-parameterstore:/sample-application
```

Parameters stored in AWS :
```cmd
aws ssm put-parameter --name "/sample-application/KEY1/KEY5" --value "Value5" --type String
```

Printing parameters:

```java
@Configuration
public class Demo{
	@Value("${KEY1.KEY5}")
	private String key5Value;

	@PostConstruct
	private void postConstruct() {
	    System.out.println(key5Value);
	}
}
```

Result : 
`Could not resolve placeholder value "${KEY1.KEY5}"`

> Why does this error appear? Please help us with this.

### ISSUE 2
**Details**
There is no error when the parameter store name hierarchy has a **hyphen** (KEY-5) in the last level and we are trying ${KEY1.KEY-5}
However, in this case, ${KEY1.KEY5} also reads the parameter with name /KEY1/KEY-5. 
/KEY1/KEY5 and /KEY1/KEY-5 are 2 different paramaters in AWS.
But Spring Cloud resolves /KEY1/KEY-5 to ${KEY1.KEY5}.
Is this intended to respond this way?

Spring application.properties:
```yaml
spring:
  config:
    import: aws-parameterstore:/sample-application
```

Parameters stored in AWS :
```cmd
aws ssm put-parameter --name "/sample-application/KEY1/KEY-5" --value "Value5" --type String
```

Printing parameters:

```java
@Configuration
public class Demo{
	@Value("${KEY1.KEY-5}")
	private String key5WithoutHyphen;
        
        @Value("${KEY1.KEY5}")
	private String key5WithHyphen;

	@PostConstruct
	private void postConstruct() {
	    System.out.println(key5WithoutHyphen);
	    System.out.println(key5WithHyphen);
	}
}
```

Result : 
Value5
Value5

### The ISSUE 1 doesn't appear if we use the following workaround. No error when the parameter store name hierarchy has zero or more hyphens (/KEY1/KEY4, /KEY/KEY-5) in the last level and we are trying ${KEY4} OR ${KEY-5}

Spring application.properties:
```yaml
spring:
  config:
    import: aws-parameterstore:/sample-application/KEY1
```

Parameters stored in AWS :
```command
aws ssm put-parameter --name "/sample-application/KEY1/KEY4" --value "value4" --type String
aws ssm put-parameter --name "/sample-application/KEY1/KEY-5" --value "value5" --type String
```
Printing parameters:

```java
@Configuration
public class Demo{
	@Value("${KEY4}")
	private String key4Value;

        @Value("${KEY-5}")
	private String key5Value;

	@PostConstruct
	private void postConstruct() {

	    System.out.println(key4Value);
            System.out.println(key5Value);
	}
}
```

Result : 
`Value4`
`Value5`

**Comment by MatejNedic** [comment]
Hey @AshwiniV-PhilipsAccount , thank you for reporting will check it out in following days.

**Comment by MatejNedic** [comment]
Hey @AshwiniV-PhilipsAccount , sorry for the delay I didn't buy the schedule.

You are missing a / in first case. 
Instead:
```
spring:
  config:
    import: aws-parameterstore:/sample-application
```

Try :

```
spring:
  config:
    import: aws-parameterstore:/sample-application/
```
I tried with spring.cloud.aws 3.0.1 and it works like a charm.
If you specfy /sample-application

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback
