### ISSUE TITLE
Check for `null` and ZERO when deciding between ImmediateAcknowledgementProcessor and batchingAcknowledgementProcessor

### ISSUE THREAD

**Issue by 5V715** [awspring/spring-cloud-aws#834]
**Type**: Bug

**Component**:
 SQS

**Describe the bug**
default value for acknowledgementInterval in the options is `null` not Duration.ZERO if not pro activly configured batchingAcknowlagement always wins

**Sample**
add missing null check to https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/listener/StandardSqsComponentFactory.java#L69

**Comment by tomazfernandes** [comment]
Sure @maciejwalkowiak, I should be able to take a look later today.

**Comment by tomazfernandes** [comment]
Hi @5V715, thanks for bringing this up.

As stated in the [documentation](https://docs.awspring.io/spring-cloud-aws/docs/3.0.1/reference/html/index.html#standard-sqs), the standard acknowledgement configuration for Standard SQS Queues is to batch acknowledgements.

You can confirm this by looking at this part of the code:
https://github.com/awspring/spring-cloud-aws/blob/83811beb6a5f8026dbd532dde4c76ad3fd3f2b97/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/listener/StandardSqsComponentFactory.java#L41-L43

If you want immediate acknowledgement, yes, you need to proactively set both `acknowledgementInterval` and `acknowledgementThreshold`  to `Duration.ZERO` and `0`  respectively.

May I ask what's your use case and why would you need immediate acknowledging for a Standard SQS queue?

Thanks.

**Comment by tomazfernandes** [comment]
By the way, mind that the default acknowledgement behavior for `FIFO` queues is indeed immediate acknowledgement, as you can also see in the [documentation ](https://docs.awspring.io/spring-cloud-aws/docs/3.0.1/reference/html/index.html#fifo-sqs) and in the code:

https://github.com/awspring/spring-cloud-aws/blob/83811beb6a5f8026dbd532dde4c76ad3fd3f2b97/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/listener/FifoSqsComponentFactory.java#L51-L53

**Comment by tomazfernandes** [comment]
@5V715, I'll close this issue since it seems the framework is working as expected, but we can reopen if you think we need to discuss it further. Thanks.
