### ISSUE TITLE
SQS Integration samples to complex AsyncTaskExecutor implementation

### ISSUE THREAD

**Issue by rl1m4** [awspring/spring-cloud-aws#835]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
The Spring Cloud AWS 2.x messaging module was replaced with two separate modules supporting SQS and SNS.
The SQS library and starter dependency has lots of features that are not compatible with previous version and not enough complex samples.
I am frustrated when I have to refactor this complex code and I can't find the replacement in the new sqs module.
As an example, the previous SimpleMessageListenerContainerFactory had `setAutoStartup` and `setTaskExecutor`. The new SqsMessageListenerContainerFactory is impossible to set the autoStartup. More imporant, I can't make it work the componentsTaskExecutor to receive a  ThreadPoolTaskExecutor with a custom configuration. Passing the custom task executor in the custom configuration doesn't work and I can't find proper solution and [sample documentation](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0/reference/html/index.html#providing-a-taskexecutor) for the same.
```
SqsMessageListenerContainerFactory
            .builder<T>()
            .sqsAsyncClient(sqsClient)
            .configure {
                it.componentsTaskExecutor(customDefaultTaskExecutor())
            }
            .build()

private fun customDefaultTaskExecutor(): AsyncTaskExecutor {
        val threadPoolTaskExecutor = ThreadPoolTaskExecutor()
        // custom executor
        return threadPoolTaskExecutor
    }
```
 
Any help would be appreciated.

**Comment by maciejwalkowiak** [comment]
@tomazfernandes could you please take a look?

**Comment by tomazfernandes** [comment]
Hi @rl1m4, thanks for bringing this up.

> As an example, the previous SimpleMessageListenerContainerFactory had setAutoStartup and setTaskExecutor. The new SqsMessageListenerContainerFactory is impossible to set the autoStartup.

The `setAutoStartup` feature has a PR open and should be merged soon: https://github.com/awspring/spring-cloud-aws/pull/827

> More imporant, I can't make it work the componentsTaskExecutor to receive a ThreadPoolTaskExecutor with a custom configuration. Passing the custom task executor in the custom configuration doesn't work and I can't find proper solution and [sample documentation](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0/reference/html/index.html#providing-a-taskexecutor) for the same.

For a matter of avoiding excessive thread hopping that led to other issues, you must provide a `TaskExecutor` with a `MessageExecutionThreadFactory`.

You can use this part of the code for guidance:

https://github.com/awspring/spring-cloud-aws/blob/83811beb6a5f8026dbd532dde4c76ad3fd3f2b97/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/listener/AbstractPipelineMessageListenerContainer.java#L240-L257

We do have an issue open for adding more samples, would you like to contribute one with the custom `TaskExecutor`?
Please take a look at https://github.com/awspring/spring-cloud-aws/issues/670

Please let me know if this answer your questions.

Thanks.

**Comment by dottnul** [comment]
Hi @tomazfernandes I add the sample for us :) https://github.com/awspring/spring-cloud-aws/pull/839

**Comment by rl1m4** [comment]
Thanks @tomazfernandes for looking into it. I'm back to finish migrating this next week when I will try the approach you sent.

**Comment by tomazfernandes** [comment]
Hey @rl1m4, any news on this front? Thanks

**Comment by rl1m4** [comment]
Hi @tomazfernandes , sorry for delay 

yeap, it worked! Thank you for looking into it!

**Comment by tomazfernandes** [comment]
Cool @rl1m4!
