### ISSUE TITLE
Parameter store refresh strategy does not work

### ISSUE THREAD

**Issue by dominik-kovacs** [awspring/spring-cloud-aws#836]
**Type**: Bug

**Component**:
Parameter Store

**Describe the bug**
I am trying to use aws parameter store reload strategy in my spring boot app. When I change the property value in AWS console, no changes are detected in the app. Using springboot v3.1.0

**Sample**
```java
@EnableScheduling
@SpringBootApplication
public class DemoApplication {

  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }
}

@Component
class MyBean {

  @Autowired private MyConfig config;

  @Scheduled(fixedDelay = 5000)
  public void hello() {
    System.out.println("The message is: " + config.getMessage());
  }
}

@Configuration
@ConfigurationProperties(prefix = "bean")
class MyConfig {

  private String message = "a message that can be changed live";

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }
}
```

```yml
spring:
  config:
    import:
      - aws-parameterstore:/myapp/

  cloud:
    aws:
      parameterstore:
        reload:
          strategy: refresh
          period: 10s

bean:
  message: ${TEST}

```

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>3.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-starter-parameter-store</artifactId>
        </dependency>
    </dependencies>
```

the scheduled method prints always the same value, even If I change it in the aws console. This is the exact example taken from [the documentation](https://docs.awspring.io/spring-cloud-aws/docs/3.0.1/reference/html/index.html#propertysource-reload-2)

What am I missing?

**Comment by maciejwalkowiak** [comment]
Thanks for reporting, I'll take a look

**Comment by poklakni** [comment]
@maciejwalkowiak looks like it works if I add actuator, cloud context and cloud commons dependencies. Is it desired behaviour to only work in this case?

**Comment by maciejwalkowiak** [comment]
As far as I remember - yes, they must be there. We should document it properly.

**Comment by MatejNedic** [comment]
True Actuator is needed reason behind this is that the class we use to do an update (be that restart or refresh) is `RefreshEndpoint`.
This class is autoconfigured by `RefreshEndpointAutoConfiguration` which depends on the actuator class `EndpointAutoConfiguration`.

I will change this from bug to documentation, tnx on reporting.

**Comment by brunoventurazup** [comment]
Hi, guys!

I am with the same issue that @poklakni reported. 

I added `spring-cloud-commons` and `spring-cloud-context` dependencies on my application and i still having the same error.

Can you share a sample application with Parameter store refresh working?

**Comment by poklakni** [comment]
@brunoventurazup also actuator is needed

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>

```

**Comment by alexgutjahr** [comment]
> Hi, guys!
> 
> I am with the same issue that @poklakni reported.
> 
> I added `spring-cloud-commons` and `spring-cloud-context` dependencies on my application and i still having the same error.
> 
> Can you share a sample application with Parameter store refresh working?

I made a sample application here https://github.com/axgr-dev/aws-systems-manager - it's written in Kotlin, but should be reasonably easy to adapt to Java. Essential pieces are the dependencies and the application.properties.

**Comment by brunoventurazup** [comment]
> I made a sample application here https://github.com/axgr-dev/aws-systems-manager - it's written in Kotlin, but should be reasonably easy to adapt to Java. Essential pieces are the dependencies and the application.properties.

@alexgutjahr, can you share the repository with me? I receive a 404 error when i try to access the repository link :(

**Comment by alexgutjahr** [comment]
> > I made a sample application here https://github.com/axgr-dev/aws-systems-manager - it's written in Kotlin, but should be reasonably easy to adapt to Java. Essential pieces are the dependencies and the application.properties.
> 
> @alexgutjahr, can you share the repository with me? I receive a 404 error when i try to access the repository link :(

My bad; I had made it private for some reason. It should work now!

**Comment by brunoventurazup** [comment]
Thank you, @alexgutjahr!

I take a look in your sample application and applied the configuration on mine. 

Now everything works as expected ❤️

**Comment by lovababu** [comment]
Is **spring.cloud.aws.parameterstor.reload** supported by_io.awspring.cloud:2.4.4_, _spring-boot: 2.7.13_ and _Spring Cloud Config 3.1.7_?
@maciejwalkowiak @alexgutjahr

**Comment by maciejwalkowiak** [comment]
@lovababu reloading was introduced in 3.0
