### ISSUE TITLE
Feature requests similar to spring data for dynamoDB

### ISSUE THREAD

**Issue by pranavakkian-dev** [awspring/spring-cloud-aws#843]
**Type**: Spring data like features for dynamoDB

**Is your feature request related to a problem? Please describe.**
We are using spring data before in our project but now we want to migrate to this library but we are struggling with below operations:
- Unable to find a method similar to saveAll in spring data.
- Unable to find a method similar to findAll in spring data.

**Describe the solution you'd like**
We need a similar method for saveAll and findAll as present in spring data. Also, the sample unit testing code will be helpful.

**Describe alternatives you've considered**
We have used dynamoDbEnhancedClient for batch operation but unit testing the same is a nightmare as most of the classes we are unable to mock due to private constructor.

**Additional context**
NA

**Comment by MatejNedic** [comment]
Hey @pranavakkian-dev , problem with this is that Spring Cloud AWS is simple wrapper around `dynamoDbEnhancedClient` and it resolved table names out of the box with help of few side classes. We can only support -> `BatchWriteItemEnhancedRequest` and have it in that way.
Other than that I am afraid we cannot do more. Only way to do what you want is to write proper Spring Data DynamoDb, but this should be project on its own and is out of scope of Spring Cloud AWS

**Comment by pranavakkian-dev** [comment]
Hi, is there any plan to create spring-data-dynamodb similar to spring-data-mongodb?

**Comment by MatejNedic** [comment]
I am closing this issue since we won't be implementing it.
Problem is that we don't have capacity on writing spring data DynamoDB since we maintainers do this in our free time.
