### ISSUE TITLE
Configuration property spring.cloud.aws.endpoint has no effect

### ISSUE THREAD

**Issue by bikerp** [awspring/spring-cloud-aws#850]
Version: 3.0.1

It seems that configuration property `spring.cloud.aws.endpoint` has no effect. I always have to set the endpoint programatically e.g.

```
        SnsAsyncClientBuilder builder = SnsAsyncClient.builder()
                .endpointOverride(URI.create(endpointUri));
```

**Comment by MatejNedic** [comment]
Hey @bikerp , the reason behind this is that we don't autoconfigure `SnsAsyncClient` but rather `SnsClient`, since all of our clients are blocking.
If you would use `SnsClient` it would configure it.

**Comment by bfbay315** [comment]
I'm seeing the same issues, but I'm using SNSTemplate

**Comment by MatejNedic** [comment]
@bfbay315 I have wrote new test and I am getting endpoint set correctly. Could you please provide sample of your application that sets endpoint differently?

**Comment by miles-po** [comment]
This issue should not have been closed. Setting `spring.cloud.aws.endpoint` even in our default `application.properties` file has no effect. Using v3.1.0 (Spring Boot 3.2.2). Going through my debugger, I never see it read. The endpoint never changes.
