### ISSUE TITLE
Work done in PR https://github.com/awspring/spring-cloud-aws/pull/248 for 2.4.1 missing from 3.x

### ISSUE THREAD

**Issue by zampettim** [awspring/spring-cloud-aws#852]
**Type**: Bug

**Component**:"Parameter Store"

**Describe the bug**
The work done in PR https://github.com/awspring/spring-cloud-aws/pull/248 and released in tagged version 2.4.1 seems to have been lost or removed from 3.x. As far as I can tell, this was not intentional and should be easy to re-implement.

**Comment by MatejNedic** [comment]
Thanks on pointing this out @zampettim ,
Are you willing to make PR :) ?
