### ISSUE TITLE
New SQS Fifo Queue support is not working because of empty MessageAttributes

### ISSUE THREAD

**Issue by tekener** [awspring/spring-cloud-aws#86]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
I tested the RC2 with localstack and elasticmq and in both cases the "MessageGroupId" is returned as an attribute and not as an messageAttribute. That is the reason why the following line is throwing a NullpointerException:

https://github.com/awspring/spring-cloud-aws/blob/b201f0ca65bc2ccd9f2b723b19072ea76ea25876/spring-cloud-aws-messaging/src/main/java/io/awspring/cloud/messaging/listener/SimpleMessageListenerContainer.java#L376

The functionality was introduced with: https://github.com/awspring/spring-cloud-aws/pull/40

The aws documentation is also saying that the MessageGroupId is part of the structures and not of the messageAttributes. See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html

**Sample**

**Comment by tekener** [comment]
Add PR with fix https://github.com/awspring/spring-cloud-aws/pull/87

**Comment by maciejwalkowiak** [comment]
Fixed in https://github.com/awspring/spring-cloud-aws/pull/87
