### ISSUE TITLE
SQS create permission required

### ISSUE THREAD

**Issue by swagregorio** [awspring/spring-cloud-aws#861]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
Using STS to assume roles on AWS env thrown the error bellow:
`Caused by: software.amazon.awssdk.services.sqs.model.SqsException: User: {the user ARN} is not authorized to perform: sqs:createqueue on resource: {the queue ARN} because no identity-based policy allows the sqs:createqueue action (Service: Sqs, Status Code: 403, Request ID: 78c99551-dfbc-5dea-ae56-c81aa731ab40)`

From the docs ([here](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#iam-permissions-5)), the permission `sqs:createqueue` isn't required. 

I wondering if something is missing to tell awsspring-sqs to not try to create the queue or if this behavior is a bug or something.

Worth to mention, if I use an account with the required permission (via assume role, same config just change the login user) everything works fine.

**Sample**
Can't provide a sample since basically I'am trying to start the application with assume role configs for authorization, using configs described [here](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#stswebidentitytokenfilecredentialsprovider)

**Comment by tomazfernandes** [comment]
Hi @swagregorio. 

The framework will try to create the queue if the queue is not found at startup and `ContainerOptions#queueNotFoundStrategy` is set to `CREATE` (which is the default).

If you don't have permissions to create queues, you can set it to `FAIL` for a more descriptive error.

Let me know if that works for you.

Thanks.

**Comment by swagregorio** [comment]
Uhm, thats the point, the queue was there, created but the only thing missing was the permission. 

After added the permission to the role everything worked fine, same happened for an SNS topic, it already exists but the role I was assuming didn't have create permission. I was relaying in the docs again to use the required ones described there.

I will have a look in the class you've mentioned to try to figure out what could be happening.

**Comment by tomazfernandes** [comment]
Hi @swagregorio, that's strange - the 2.x version did use the `createQueue`  method to get information from the queue, but the 3.x version purposely does it differently and only uses the createQueue method if the queue does not exist and the framework is configured to do so.

It'd be great if you could take a look into it and confirm if this was really the case, or if the queue might have been missing at the time for any reason.

**Comment by swagregorio** [comment]
I can ensure the Queue is already created, the only thing was missing was the createQueue/createTopic role. I will try to create a test scenario to reproduce it since using localstack I could not do it.

**Comment by tomazfernandes** [comment]
> I can ensure the Queue was already created, the only thing was missing was the createQueue/createTopic role. I will try to create a test scenario to reproduce it since using localstack I could not do it.

Thanks @swagregorio. 

You can see here that we use the `getQueueUrl` method, and only if a `QueueDoesNotExistException` is thrown we use the `createQueue` method.

https://github.com/awspring/spring-cloud-aws/blob/a45e735ea24686152717683cd524ebd3f2fa9ced/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/QueueAttributesResolver.java#L99-L119

I don't see in this logic how the create queue permission might be required, but I might be missing something.

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback

**Comment by dezzak** [comment]
Just in case anyone else should come across this while searching for this error as we did -

In our case we hit this issue when we had been using a queue name in our config. Once we switched to using the queue URL instead, the issue went away. Presumably this is due to the URL containing the account number and region, while the name doesn't.

**Comment by tomazfernandes** [comment]
Hey @dezzak, after you successfully ran it the first time, did you still need to have the url instead of the name?

**Comment by dezzak** [comment]
Hi @tomazfernandes in our case we can't start the application with just a queue name, we need the full url. Our case may be further complicated with it involving cross-account access (the application runs in one AWS account, but the queue is in another)

**Comment by 15520529** [comment]
I encountered the same issue and I realized that my application was not granted permission GetQueueUrl, to fix that, I added permission but had to restart the service as well. Because `doResolveQueueUrl` was only called at the first time sending the message.

**Comment by enobil** [comment]
This is still reproducing with 3.0.1 and it is a bug. Because the error message should be e.g. "Failed to resolve queue url from the queue name" whereas, apparently the aws sdk call is made for GetQueueUrl and that is responding with 403 if that permission is not given, and this library is silencing that exception and proceeding to the queue creation code path, just like if it received a "queue doesn't exist" response, but that's not the case, it just received a 403 forbidden error from the sdk. I wish I had time to create a pr to fix this. But at least just taking down what is the bug here. Might be fixed in later versions, we tested with 3.0.1 today.

**Comment by sravibasker** [comment]
I had the same problem with 3.1.1. Had to 

> I encountered the same issue and I realized that my application was not granted permission GetQueueUrl, to fix that, I added permission but had to restart the service as well. Because `doResolveQueueUrl` was only called at the first time sending the message.

Same here.
