### ISSUE TITLE
SQS Listeners are not shutting down gracefully 

### ISSUE THREAD

**Issue by prasanthgopalakrishnan1412** [awspring/spring-cloud-aws#877]
**Type**: Bug

**Component**: SQS

**Describe the bug**
I'm using spring-cloud-starter-aws-messaging:2.4.4 to receive messages from SQS. It works fine for most of the cases but sometimes when deploying new application, old application is not gracefully shutting the SQS Listeners. Just before the instance termination, sqs listeners picking up new messages and with in few milliseconds, instance getting terminated leaving the message half processed. (Though the message is appearing again, causing issues since it is half processed.)

**Sample**
The issue is so random and could not reproduce all the time.

My SimpleMessageListenerContainer has waitTimeout of 10s and queueStopTimeout of 20s.

Running on Springboot 3.1.2 and it has graceful shutdown enabled with 30s timeout.

Consuming messages from 15 different queues.

Quick note, I'm running APM agent in the same instance, based on logs I'm sure apm agent received the shutdown signal 10seconds before the instance termination.

**Comment by tomazfernandes** [comment]
Hi @prasanthgopalakrishnan1412, Spring Cloud AWS 2.4.4 is not compatible with Spring Boot 3.1.2

Can you confirm the versions please?

Thanks.

**Comment by prasanthgopalakrishnan1412** [comment]
@tomazfernandes Yeah! I'm currently in Spring boot 3.1.2. But faced the same in 3.0.x as well. Is 2.4.4 not compatible with Spring boot 3 itself?

**Comment by msosa** [comment]
here is a [compatibility chart](https://github.com/awspring/spring-cloud-aws#compatibility-with-spring-project-versions) for aws spring and spring boot @prasanthgopalakrishnan1412 

it looks like you will need to either upgrade aws spring, or downgrade spring boot
