### ISSUE TITLE
Non profile settings used to fecth Secrets when starting the app with a profile

### ISSUE THREAD

**Issue by Frantch** [awspring/spring-cloud-aws#88]
**Type**: Bug

**Component**:
"Secrets Manager"

**Describe the bug**
Not entirely sure this is a bug or I'm missing something very trivial but when starting my app with a profile the secret manager still tries to fetch a secret with the values it finds in the application.yml which makes it impossible to test the app locally.

**Sample**
Spring Boot 2.4.2
spring-cloud-starter-aws-secrets-manager-config 2.3.0-RC2

Two property files

 - application.yml
 - application-dev.yml

I just need to fetch one secret entry from AWS Secret Manager so I have defined this in the `application.yml` 

    spring.config.import: aws-secretsmanager:/secret/my-app

And I'm amending the endpoint for the dev profile (in `application-dev.yml`) in order to use localstack

    `aws.secretsmanager.endpoint: http://127.0.0.1:4566`

When I start the app with the `-Dspring.profiles.active=dev` the library tries to fetch the secret first using the value in `application.yml` and off course fails because the endpoint will be the default aws one.

I have tried using only `spring.config.import: 'aws-secretsmanager:'` since the doc says it will fetch the secret for the active profile but it still tries to fetch the secret using the endpoint in the `application.yml` file 

Why is the library still trying to load the secret using the application.yml  when the app is started with the dev profile ?
Is there a way to 'only' fetch the secret for the profile that is currently active ?

(I'm not having this issue with Spring Boot 2.3.8 and spring-cloud Hoxton SR10)

**Comment by MatejNedic** [comment]
Hey @Frantch ,
Spring Boot 2.4 changed the ways how files are loaded. That is why you can't load from application-dev.yml
You can use Multi Document property something like this for Application.properties:

`
spring.config.import=aws-parameterstore:/config/spring/
#---
spring.config.activate.on-profile=dev
spring.config.import= aws-parameterstore:/other/path/
`

Or something like this in Application.properties:

`spring.config.import= application-dev.properties`

And in  Application-dev.properties

`
spring.config.import= aws-parameterstore:/other/path/
spring.config.activate.on-profile=dev
`
You can add more properties and just separate them with a comma.

More can be read on https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4

**Comment by Frantch** [comment]
Oh wow... yes I just read about the way 2.4 has completely redone how the properties file are getting loaded... 
this explain what I was seeing. 

Not sure I'm a big fan of putting the equivalent of 6 different profiles (yes our app uses 7 differents profile for 7 diff environment) into one single application.yaml file separated by that new `#---` thing..

I'm gonna give a try thought but pretty sure it will fix it

**Comment by MatejNedic** [comment]
@Frantch you are not overriding default `spring.config.import=aws-secretsmanager:/config/spring` for test profile that is why  /config/spring is used.  That is why the Unit test is failing for the 'test' profile.
If you want to define one `spring.config.import=aws-secretsmanager:/config/spring` for few profiles you can chain it like.
`spring.config.activate.on-profile=prod,test,dev`
