### ISSUE TITLE
@SqsListener doesn't pick up every message from the queue

### ISSUE THREAD

**Issue by jndietz** [awspring/spring-cloud-aws#890]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
Basically, if I submit a barrage of messages to an SQS queue via the AWS admin console, only a handful are picked up by `@SqsListener`.  It appears that something is acknowledging them, because if you poll for the messages, they aren't on the queue anymore.

Spring Boot 3.1.3
Spring Cloud 2022.0.4
AWS SDK 3.0.4

**Sample**
To reproduce, set up an `@SqsListener`.  Run the app, then set a breakpoint on the first line of the method.  I would expect the break point to get hit however many times a message was submitted.

[Sample app located here](https://github.com/jndietz/sqs-listener/tree/spring-cloud-aws-issue-890)

**Comment by tomazfernandes** [comment]
Hi @jndietz, hitting breakpoints is not really a good measure for the amount of messages being received, because the IDE may decide to skip some when they're received concurrently as is the case with SqsListener.

You can log the messages in you listener, and then count them to see if the number is correct, or add a counter variable of some sort to your listener method.

Makes sense?

Thanks.

**Comment by jndietz** [comment]
Breakpoints or not, the `@SqsListener` doesn't pick up all of the messages.

**Comment by jndietz** [comment]
I set up a counter and submitted ten messages, and it only picked up two of them.

**Comment by tomazfernandes** [comment]
Hi @jndietz. 

Can you update your sample project to include the counter and preferably having code to send the messages as well? That'd be of great help, thanks.

**Comment by tomazfernandes** [comment]
Hi @jndietz,

The issue there is that you're using a non-thread safe object `Integer` in multi-threaded environment. Each message is processed in parallel, so that's why you're not seeing all messages.

If you update the code to use an `AtomicInteger` instead, the count will be ok.

Thanks.

**Comment by tomazfernandes** [comment]
I'll close due to lack of feedback. We can reopen if necessary.
