### ISSUE TITLE
[S3] How to use spring.cloud.aws.s3.path-style-access-enabled (or is it broken?)

### ISSUE THREAD

**Issue by IngoStrauch2020** [awspring/spring-cloud-aws#896]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
The documentation at https://docs.awspring.io/spring-cloud-aws/docs/3.0.2/reference/html/appendix.html describes the property `spring.cloud.aws.s3.path-style-access-enabled` as

> Option to enable using path style access for accessing S3 objects instead of DNS style access. DNS style access is preferred as it will result in better load balancing when accessing S3.

My understanding is that an entry like this would switch from DNS style access to path style access:

```
spring.cloud.aws.s3.path-style-access-enabled=true
```

In my Java Spring Boot 2.x application I have a local test setup that uses a `minio` docker container to emulate S3. My `pom.xml` contains
```
<dependency>
	<groupId>io.awspring.cloud</groupId>
	<artifactId>spring-cloud-aws-starter-s3</artifactId>
	<version>3.0.2</version>
</dependency>
``` 

My bean for the `S3Client` looks like this

```
  @Bean
  public S3Client s3Client(AwsClientBuilderConfigurer awsClientBuilderConfigurer, S3Properties s3Properties) {
    return awsClientBuilderConfigurer
        .configure(S3Client.builder(), s3Properties, null)
        .build();
  }
```

When I then test my app and want to write something to the "bucketname" bucket of my local minio S3, I get an exception with the following cause:

> Caused by: java.net.UnknownHostException: bucketname.localhost

Maybe here's my misunderstanding, I thought `path-style-access-enabled=true` would make the SDK **not** use the DNS style access.

I get the desired result by changing my Bean like this:

```
  @Bean
  public S3Client s3Client(AwsClientBuilderConfigurer awsClientBuilderConfigurer, S3Properties s3Properties) {
    S3ClientBuilder builder = awsClientBuilderConfigurer
        .configure(S3Client.builder(), s3Properties, null);
    if (Boolean.TRUE.equals(s3Properties.getPathStyleAccessEnabled())) {
      builder.forcePathStyle(true);
    }
    return builder.build();
  }
```

**Describe the solution you'd like**

I could imagine two possible solutions:

1. If the existing property is supposed to make S3 calls use path style access, I think it's broken and should be fixed
2. Add a new property `force-path-style=true` and its handling in the `AwsClientBuilderConfigurer` that would make my explicit if-statement plus `builder.forcePathStyle(true)` obsolete

**Describe alternatives you've considered**
For now I'm using the above code that basically maps a property name of spring-cloud-aws to the "real" property name of the AWS SDK v2.

**Comment by maciejwalkowiak** [comment]
@IngoStrauch2020 sorry for late reply. This is happening because you create custom S3Client bean. If you rely on autoconfigured one, all properties are applied to `S3ClientBuilder`. If you need to create custom S3Client you may also want to rely on autoconfigured builder bean:

```java
@Bean
public S3Client s3Client(S3ClientBuilder builder) {
    // ...
    return builer.build();
}
```

I don't think there's anything missing from the Spring Cloud AWS side?
