### ISSUE TITLE
Checking if a bucket exists using S3Template

### ISSUE THREAD

**Issue by straurob** [awspring/spring-cloud-aws#901]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
For checking if a bucket exists, I'm using the `S3Client` from the AWS Java SDK  v2. I can then use its `headBucket()` method. However, this requires an additional injection in my class which could be avoided if the `S3Template` provided a wrapper function.

**Describe the solution you'd like**
The `S3Template` could provide a method which checks if a given bucket name exists. Its return value could be a simple boolean. Optional: As an add-on the bucket could get created if it doesn't exist by some configuration parameter.

**Describe alternatives you've considered**
Currently, I'm using the `S3Client.headBucket()` method from the AWS Java SDK  v2.

**Comment by MatejNedic** [comment]
Hey @straurob , interesting feature. Would you like to contribute to Spring Cloud AWS?

**Comment by straurob** [comment]
> Hey @straurob , interesting feature. Would you like to contribute to Spring Cloud AWS?

I'd be happy to contribute, though I've neder done it before. But I will fork the repo and try my best :wink:
