### ISSUE TITLE
io.awspring.cloud.core.env.ResourceIdResolver - .ClassNotFoundException

### ISSUE THREAD

**Issue by erickjhorman** [awspring/spring-cloud-aws#903]
**Type**: Bug

**Component**:
Aws-cloud-aws-core-3.0.2, Spring boot 3.1.2 , spring-cloud-aws-messaging:2.4.4

**Describe the bug**
I had to update my current proyect to Spring boot 3.1.2 and also update Aws-cloud-aws-core spring-cloud-aws-messaging from io.springframework to io.awspring.cloud and i'm getting this exception  Caused by: java.lang.ClassNotFoundException: io.awspring.cloud.core.env.ResourceIdResolver. 
I noticed that my applicaction can't resolve this class import io.awspring.cloud.core.env.ResourceIdResolver;
 
```
@Bean
	public QueueMessagingTemplate queueMessagingTemplate () {
		return new QueueMessagingTemplate(amazonSQSAsync());
	}
	
	@Bean
	public AmazonSQSAsync amazonSQSAsync () {
		return AmazonSQSAsyncClientBuilder.standard()
				.withRegion(region)
				.withCredentials(new DefaultAWSCredentialsProviderChainCustom())
				.build();
	}
	
	@Bean
	public SimpleMessageListenerContainer simpleMessageListenerContainer () {
		SimpleMessageListenerContainer msgListenerContainer = simpleMessageListenerContainerFactory()
				.createSimpleMessageListenerContainer();
		msgListenerContainer.setMessageHandler(queueMessageHandler());
		return msgListenerContainer;
	}
	
	@Bean
	public SimpleMessageListenerContainerFactory simpleMessageListenerContainerFactory () {
		SimpleMessageListenerContainerFactory msgListenerContainerFactory = new SimpleMessageListenerContainerFactory();
		msgListenerContainerFactory.setAmazonSqs(amazonSQSAsync());
		msgListenerContainerFactory.setMaxNumberOfMessages(MAX_NUMBER_OF_MESSAGES);
		return msgListenerContainerFactory;
	}
	
	@Bean
	public QueueMessageHandler queueMessageHandler () {
		QueueMessageHandlerFactory queueMsgHandlerFactory = new QueueMessageHandlerFactory();
		queueMsgHandlerFactory.setAmazonSqs(amazonSQSAsync());
		QueueMessageHandler queueMessageHandler = queueMsgHandlerFactory.createQueueMessageHandler();
		List<HandlerMethodArgumentResolver> list = new ArrayList<>();
		HandlerMethodArgumentResolver resolver = new PayloadArgumentResolver(new MappingJackson2MessageConverter());
		list.add(resolver);
		queueMessageHandler.setArgumentResolvers(list);
		return queueMessageHandler;
	}
```

![image](https://github.com/awspring/spring-cloud-aws/assets/31042386/c7d28843-d2d6-4e10-b15c-ccfa7877f677)
Thanks for your help

**Comment by JNKessel** [comment]
Hi @MatejNedic!
I am having the same problem as @erickjhorman here.

According to [this repository](https://mvnrepository.com/artifact/io.awspring.cloud/spring-cloud-aws-messaging) it looks like the newest version of Spring Cloud AWS messaging is 2.4.4, is there a 3.x.x version compatible with Spring Boot 3.x?

Thank you!

**Comment by MatejNedic** [comment]
Hey @JNKessel 
Spring Cloud AWS messaging is only compatible with Spring Cloud AWS 2.x.x versions.
We released new version of Spring Cloud AWS 3.0.0 + which removed Spring Cloud AWS messaging.
Now you have `spring-cloud-aws-sqs` and `spring-cloud-aws-sns`. With the latest version being 3.0.2

The repository you linked is old repository, we moved github repositories. Check [here](https://mvnrepository.com/artifact/io.awspring.cloud/spring-cloud-aws-sqs)

Please check the [releases](https://github.com/awspring/spring-cloud-aws/releases)

**Comment by JNKessel** [comment]
Thank you so much for the clarification @MatejNedic! I hope this helps erick as well.
I will take a look at spring-cloud-aws-sqs documentation to figure out how to adapt my project.

I will still read the repository, but are there equivalent classes to the old Messaging module?

For example, these are some of the main ones i remember:
io.awspring.cloud.messaging.config.QueueMessageHandlerFactory
io.awspring.cloud.messaging.core.QueueMessagingTemplate
io.awspring.cloud.messaging.listener.SimpleMessageListenerContainer

Thank you!!

**Comment by maciejwalkowiak** [comment]
SQS architecture has changed and there are no 1 to 1 equivalent classes. Please take a look at the reference documentation and start [discussion](https://github.com/awspring/spring-cloud-aws/discussions) if you'll encounter any issues.

**Comment by VaibhavTheVicar** [comment]
@JNKessel SqsMessageListenerContainer is for SimpleMessageListenerContainer and similarly the factory. @maciejwalkowiak you could have answered it.

**Comment by tomazfernandes** [comment]
@VaibhavTheVicar, unfortunately we hadn't been able to create a proper migration guide from 2.x to 3.x, so you'll need to look for new features that will correspond to your application's need rather than have a 1 to 1 feature mapping.

> setWaitTimeOut and FailOnMissingQueue.
You can find similar options in `ContainerOptions`, please refer to the documentation.

> DestinationResolver
What do you use the `DestinationResolver` for?

**Comment by VaibhavTheVicar** [comment]
@tomazfernandes I cant share exactly what we use destination resolvers for, company code.

But a common use case could be resolving a Kubernetes client key value pair.

Currenly I have had to override the .createInstance method in the sqsListnerFactory class, and plug a lambda for our purposes of resolution there.

**Comment by VaibhavTheVicar** [comment]
@tomazfernandes but this poses problem, I had to copy and override the WHOLE builder :/

**Comment by ailsoncgt** [comment]
@erickjhorman & @VaibhavTheVicar how did you solve the compatibility problem? Can you please share your final solution/ideia ?
