### ISSUE TITLE
Retrieve a parameter from AWS Systems Manager Parameter Store with Decryption

### ISSUE THREAD

**Issue by HenriqueDelben** [awspring/spring-cloud-aws#921]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
There is a parameter of type "SecureString" and I need to be able to retrieve it unencrypted, I know I have to create a custom Property Source, but it isn't trivial and I'd like to do that using the support of Spring Cloud AWS

**Describe the solution you'd like**
A application.properties property to be able to customize this behavior, to set the strategy if decryption must be on or off. Something like "spring.cloud.aws.parameterstore.decryption.strategy"

**Describe alternatives you've considered**
Just provide a guide on how to integrate a custom parameter store property source (on this case with a simply "GetParameterRequest" instance with "withDecryption(true)" with the spring cloud AWS

**Comment by maciejwalkowiak** [comment]
I think it makes sense. What do you think @MatejNedic?

**Comment by MatejNedic** [comment]
Hey, we already include this in Parameter Store since we load by path.
Check [here](https://github.com/awspring/spring-cloud-aws/blob/76dcb9fe6450ea0cad2cecc7bff0f04207bf887b/spring-cloud-aws-parameter-store/src/main/java/io/awspring/cloud/parameterstore/ParameterStorePropertySource.java#L55)

**Comment by maciejwalkowiak** [comment]
Oh true, I misread that retrieving it in encrypted form is what @HenriqueDelben is asking for. If it's about decrypted value, why is current implementation missing @HenriqueDelben?

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback
