### ISSUE TITLE
[Parameter Store] Strip leading dot from imported parameters

### ISSUE THREAD

**Issue by matthias-seibert-tng** [awspring/spring-cloud-aws#923]
**Type**: Bug

**Component**: Parameter Store

**Describe the bug**
The library adds a leading dot (`.`) to imported variables, when using the setup as suggested in the readme (`spring.config.import=aws-parameterstore:/config/spring`)

This leads to problems when importing variables stored in a nested hierarchy. For example, if a variable stored at `/config/spring/my/message`, it is imported as `.my.message`, and cannot be accessed via `@Value("${my.message}")`.

Changing the config to  `spring.config.import=aws-parameterstore:/config/spring/` resolves this problem, but it would be a nice feature to strip the leading dot in the library.

**Comment by MatejNedic** [comment]
Hey @matthias-seibert-tng , since we are loading by path it is important to end with the `/` .
It only makes sense since you want all on the path.

**Comment by matthias-seibert-tng** [comment]
I can understand that, but then it would be great if you could update the docs, because in the examples there, there is no slash at the end. See this screenshot:

![Screenshot](https://github.com/awspring/spring-cloud-aws/assets/61148008/6f8dccf5-9108-473a-8ef1-6cdd28a2d453)

**Comment by maciejwalkowiak** [comment]
Closed in #1086
