### ISSUE TITLE
Cannot send message to cross account FIFO SQS queue

### ISSUE THREAD

**Issue by ZhongXiLu** [awspring/spring-cloud-aws#938]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
Whenever I try to send messages to a FIFO SQS queue in another AWS account, it results in following error:
`Value ContentBasedDeduplication for parameter Attribute.Name is invalid. Reason: Only owners can access specified attribute.`

It seems retrieving the `ContentBasedDeduplication` queue attribute does not work for a cross-account SQS queue, see https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/operations/SqsTemplate.java#L265.

I'm using spring cloud version 3.0.2.
The bug seems to be introduced since 3.0.1 through this PR: https://github.com/awspring/spring-cloud-aws/pull/799.

**Sample**
```java
SqsTemplate sqsTemplate = SqsTemplate
                .builder()
                .sqsAsyncClient(SqsAsyncClient.create())
                .build();
        
sqsTemplate.send("<other_aws_account_sqs_queue_url>", "test");
```

**Comment by maciejwalkowiak** [comment]
@tomazfernandes perhaps we can give users option to configure the value for `ContentBasedDeduplication` - in such case SQS integration instead of checking the value from real queue attributes would just believe in what user provided?

**Comment by tomazfernandes** [comment]
> @tomazfernandes perhaps we can give users option to configure the value for ContentBasedDeduplication - in such case SQS integration instead of checking the value from real queue attributes would just believe in what user provided?

Sure. From the top of my mind, we could have a `ContentDeduplication` enum, such as:

`ContentDeduplication.ENABLED`
`ContentDeduplication.DISABLED`
`ContentDeduplication.AUTO`

And then AUTO would be the default so it's not a breaking change.

Makes sense?

**Comment by maciejwalkowiak** [comment]
It does!

**Comment by tomazfernandes** [comment]
> It does!

Cool!

@ZhongXiLu, what do you think? Would you be interested in opening a PR with this change?

**Comment by ZhongXiLu** [comment]
@tomazfernandes Sure, I'll take a look 👍

**Comment by tejashwinisubbanna** [comment]
Hi All, After migrating from Spring cloud 2 to 3.0.3.I am getting below error

2023-12-08T11:29:14.838+11:00 ERROR 1 --- [nio-8080-exec-1] c.g.t.d.s.s.SqsDataLoaderMessageSender   : Error in calculation java.util.concurrent.CompletionException: io.awspring.cloud.sqs.QueueAttributesResolvingException: Error resolving attributes for queue tie-super-calc20230716111832302200000001.fifo with strategy CREATE and queueAttributesNames [ContentBasedDeduplication]


With spring cloud  2,it was working fine.But after migration,getting above error does anyone has any idea?

**Comment by tejashwinisubbanna** [comment]
Hi Team,
Could you please let us know when these changes would be available for use?
which version ?
