### ISSUE TITLE
How to solve: java.util.concurrent.CompletionException: io.awspring.cloud.sqs.listener.AsyncAdapterBlockingExecutionFailedException: Error executing action in BlockingMessageListenerAdapter

### ISSUE THREAD

**Issue by kev205** [awspring/spring-cloud-aws#963]
**Type**: Bug

**Component**:

**Describe the bug**
Get this issue when using @SqsListener to listen for sqs messages in a reactive app

**Sample**
Just using @SqsListener without any futher configurations. But everything work well if i use messageContainer to handle incomming message. Need help please

**Comment by SalyczeQ** [comment]
You should provide more information and mainly full stack of exception message.
Because this exception may be the result of something deeper

**Comment by tomazfernandes** [comment]
@kev205 this exception is simply a wrapper to any exception thrown in the listener method, so as @SalyczeQ you'd need to give us more details.

One thing though is this framework does not support `Project Reactor`, so YMMV.

**Comment by tomazfernandes** [comment]
Closed due to lack of feedback and also Reactor is not supported.
