### ISSUE TITLE
SQS ErrorHandler called incorrectly when JavaType header is missing

### ISSUE THREAD

**Issue by jelmerk** [awspring/spring-cloud-aws#999]
**Type**: Bug

**Component**:
SQS

**Describe the bug**

I have method annotated with `@SqsListener` that references a factory defined in spring config that looks like this

```
    @SqsListener(
        queueNames = ["queue"],
        factory = "workflowSqsListenerContainerFactory",
    )
    fun listen(message: Message<WorkflowResultMessage>) {
      ...
    } 
```

The config looks like this

```
@Configuration
class SqsConfig {

    @Bean
    fun errorHandler(metricReporter: MetricReporter): WorkflowCompletionErrorHandler {
        return WorkflowCompletionErrorHandler(metricReporter)
    }

    @Bean
    fun workflowSqsListenerContainerFactory(
        sqsAsyncClient: SqsAsyncClient,
        errorHandler: ErrorHandler<WorkflowResultMessage>,
        objectMapper: ObjectMapper,
        @Value("\${`aws.sqs-datascience.visibility:10}") messageVisibilityMinutes: Long,
    ): SqsMessageListenerContainerFactory<WorkflowResultMessage> {
        val messageConverter = SqsMessagingMessageConverter()
        messageConverter.setObjectMapper(objectMapper)

        return SqsMessageListenerContainerFactory
            .builder<WorkflowResultMessage>()
            .configure { options: SqsContainerOptionsBuilder ->
                options
                    .listenerMode(ListenerMode.SINGLE_MESSAGE)
                    .acknowledgementMode(AcknowledgementMode.ON_SUCCESS)
                    .messageVisibility(Duration.ofMinutes(messageVisibilityMinutes))
                    .acknowledgementOrdering(AcknowledgementOrdering.ORDERED)
                    .messageConverter(messageConverter)
            }
            .errorHandler(errorHandler)
            .sqsAsyncClient(sqsAsyncClient)
            .build()
    }
}
```

And finally the error handler looks like this

```
class WorkflowCompletionErrorHandler(private val metricReporter: MetricReporter) : ErrorHandler<WorkflowResultMessage> {

    override fun handle(message: Message<WorkflowResultMessage>, t: Throwable) {
      ....
    }
}
```

When the message on the topic contains a  `JavaType` header set to `com.miro.datadiscovery.messaging.datascience.WorkflowResultMessage` everything works fine in case processing the message inside of the listener somehow fails and the WorkflowCompletionErrorHandler gets called with the parsed message

However when this header is missing calling the WorkflowCompletionErrorHandler will fail with  a ListenerExecutionFailedException caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class com.miro.datadiscovery.messaging.datascience.WorkflowResultMessage 

This is because when the JavaType header is missing the json does not get converted in `AbstractMessagingMessageConverter.convertPayload` but this conversion happens further down the line in `InvocableHandlerMethod`

The only workaround that seems to work is to subclass SqsMessagingMessageConverter and override createMessageConversionContext like so

```
        val messageConverter = object : SqsMessagingMessageConverter() {
            override fun createMessageConversionContext(): MessageConversionContext {
                val context = SqsMessageConversionContext()
                context.setPayloadClass(WorkflowResultMessage::class.java)
                return context
            }
        }
```

but this is not very nice. I would very much prefer not to set the header on the producer side because because then refactoring the data classes will be difficult

**Comment by tomazfernandes** [comment]
Hey @jelmerk, nice to see so many features being used in your config.

As you noticed, there are two places where deserialization can occur - the first is when message is received, and the second in the `InvocableHandlerMethod`. 

For the payload to get deserialized to the Error Handler, the message converter has to have a way of knowing to which class the payload should be converted to.

Now, there are a number of ways to do that - maybe the simpler would be the `setPayloadTypeMapper` method in `SqsMessagingMessageConverter`. In this function you will get the `Message` with the payload as `String` and can use any part of it or any header to let the framework know the target class.

Let me know if that works for you. Thanks.

**Comment by tomazfernandes** [comment]
Closing due to lack of feedback.
